### PR TITLE
Avoid crash if player jumps to next system

### PR DESCRIPTION
**Pull request by robothauler**
This is a workaround. Maybe this can be removed after transitation to pigui.

### CODE REVIEW

**Comment by ecraven** [comment]
Wouldn't it be easier to *not* call the lobby code if the player isn't in fact in the lobby?

**Comment by fluffyfreak** [comment]
What crash? I haven't been able to get one to happen.

**Comment by impaktor** [comment]
@fluffyfreak I think the IRC conversation was that it triggers a crash when jumping into (an uninhabited?) system.

**Comment by fluffyfreak** [comment]
Merged as it fixes current problem.

**Pull request merged**
