### PR TITLE
Remove old vs2015 & 17 projects

### PR DESCRIPTION
**Pull request by fluffyfreak**
Removes the vs2015 and vs2017 projects, these can be generated by CMake.

It fixes up the vs2019 project as this is still useful for the time being due to #4658, having a more familiar project layout and separation etc.

I'm sure it'll go away in time but right now I'm mostly working out what can be useful from it in development terms. So it gets to live a little longer.

There is a corresponding PR https://github.com/pioneerspacesim/pioneer-thirdparty/pull/28 to go with this.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
@jaj22 I think you're one of the few still using Visual Studio as well, any comments or thoughts?

**Comment by craigo-** [comment]
Hi -

Using COMPILING.txt as a base, I've been trying to compile Pioneer for the past 7-10 days. I've tried various combinations:

- VS2017 and VS2019
- Visual Studio: solution vs cmake (CMakeLists.txt)
- pioneer and pioneer-thirdparty repositories: side by side vs the latter inside the former
- MSYS2 & MinGW-x64 with cmake

...all with little success.

What finally got me across the line with a compiled executable was some advice from IRC user 'svamp':

> visual studio 2017 using this commit worked fine for me, https://github.com/pioneerspacesim/pioneer-thirdparty/tree/7267847ba5cd6fd99823b7c18825ed34fd5552a0, latest in master was broken, the pull request maybe fixes that issue

Using the VS2017 solution with the indicated older commit level of pioneer-thirdparty resulted in my first successful build. Yay! I managed to build Debug x86, Release x86, and Release x64.

So I hear you're deprecating the VS2017 stuff. I'm happy to retry VS2019, but are both repositories ready for that? I'm guessing I'll have to wait for commits for pioneer and/or pioneer-thirdparty to be merged first..?

Also happy to use cmake rather than a VS solution inside VS2019... Is there a best-practice way to do that? e.g. (what I've been doing) open the project folder, right-click "CMakeLists.txt" and selecting "Build"?

Advice appreciated... I will report back with my findings - either here, or in separate issues (whatever you prefer).

Right on, commanders.

**Comment by fluffyfreak** [comment]
@craigo- it seems there's still some problems using the CMake file directly from vs2019, but I've been generating vs2019 solution and project using CMake and then working from that.

With this PR, and the thirdparty one, merged in it should be as simple as opening the vs2019 project, or you can generate one using CMake.

Apparently we got our wires crossed about some things like the location of `pioneer-thirdparty`, that should be in a sibling folder next to your pioneer folder checkout like:
> ./pioneer/
> ./pioneer-thirdparty/

I'm going to merge this shortly, so you'll have the optin of using either. You can also generate a vs2017 solution and project using CMake.

**Comment by craigo-** [comment]
@fluffyfreak, I've refetched both repositories and tried building with Visual Studio 2019 two different ways. Both are failing with the same two errors. Do you have any insight into what's going on?

**CMake-Generated VS2019 Solution:**

| Severity | Code | Description | Project | File | Line |
| ----- | ----- | ----- | ----- | ----- | ----- | 
| Error | C3848 |  expression having type 'const ModelNameComparator' would lose some const-volatile qualifiers in order to call 'bool ModelNameComparator::operator ()(SceneGraph::Model *,SceneGraph::Model *)' (compiling source file C:\src\pioneer\src\CityOnPlanet.cpp) | pioneerLib | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\xtree | 1730 |
| Error | C3848 |  expression having type 'const ModelNameComparator' would lose some const-volatile qualifiers in order to call 'bool ModelNameComparator::operator ()(SceneGraph::Model *,SceneGraph::Model *)' (compiling source file C:\src\pioneer\src\CityOnPlanet.cpp) | pioneerLib | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\xtree | 1720 |
| Error | LNK1181 | cannot open input file 'Release\pioneerLib.lib' | pioneer | C:\src\pioneer\build\LINK | 1 |
| Error | LNK1181 | cannot open input file 'Release\pioneerLib.lib' | modelcompiler | C:\src\pioneer\build\LINK | 1 |

**Repository-Supplied VS2019 Solution (pioneer\win32\vs2019\pioneer.sln):**

| Severity | Code | Description | Project | File | Line |
| ----- | ----- | ----- | ----- | ----- | ----- | 
| Error | C3848 |  expression having type 'const ModelNameComparator' would lose some const-volatile qualifiers in order to call 'bool ModelNameComparator::operator ()(SceneGraph::Model *,SceneGraph::Model *)' (compiling source file ..\..\src\CityOnPlanet.cpp) | pioneer | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\xtree | 1730 |
| Error | C3848 |  expression having type 'const ModelNameComparator' would lose some const-volatile qualifiers in order to call 'bool ModelNameComparator::operator ()(SceneGraph::Model *,SceneGraph::Model *)' (compiling source file ..\..\src\CityOnPlanet.cpp) | pioneer | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\xtree | 1720 |

**Comment by fluffyfreak** [comment]
@craigo- ah I know that one, I see it on my laptop but not my desktop... no idea why the difference. I'll do a PR to fix it now, thanks!

**Comment by fluffyfreak** [comment]
@craigo- PR is #4665, just a simple thing so I'll merge it once the build tests pass

**Comment by craigo-** [comment]
Thanks, @fluffyfreak. That worked: I can now build with VS2019 against the latest source from both repositories, using:

- The VS2019 solution supplied by the pioneer project
- A VS2019 solution created with the command line version of CMake shipped with VS2019
- A VS2019 solution created with standalone CMake

Three things:

**(1) Updating COMPILING.tx**t

Based on comments from yourself and others in the community, and my own experiences, I'm thinking of editing the Windows section of COMPILING.txt such that it reflects a more current build best-practice, e.g.:

- The deprecation of Visual Studio versions prior to 2019
- The deprecation of Visual Studio solutions and the move towards CMake

Would that be useful? If so, I'll get a PR going (once I figure out how - my first!)

**2. modelcompiler.exe**

 I've seen [reference](https://youtu.be/lh8Y4K1gf1k) to running modelcompiler.exe to speed up the load time. Is this still relevant?

**(3) +1 Windows Builder**

Lastly, it seems you're low on people compiling with Visual Studio. I'm new to it (as you've probably guessed) but am more than happy to help with testing... e.g. if it's of use, troubleshooting getting CMake builds to work directly from within the Visual Studio IDE. Would that be of use? If so, I'll create a new issue (don't want to get too off-topic).

**Pull request merged**
