### PR TITLE
System overview icon upscale and update

### PR DESCRIPTION
**Pull request by nozmajner**
@Gisteron and @Keeper1st made a nice set of icons for the system overview screen:
screenshot-20230212-132850
I'm also adding them to the Authors.txt (Keeper should have been added long ago)

### CODE REVIEW

**Comment by impaktor** [comment]
Cool.
the ojbect_brown_dwarf still looks a bit more fuzzy than the reset, I guess that's beyond salvage?

**Comment by zonkmachine** [comment]
Looks great!

Q - Why is there an asteroid icon on top of the asteroid icon? It didn't happen in this PR but you can see it in the picture above if you zoom into one of the smaller moons like Phobos and Deimos.

**Comment by zonkmachine** [comment]
> Q - Why is there an asteroid icon on top of the asteroid icon?

Excuse the noise. The connect with this PR seem to be that it makes the second icon redundant with the crisp model of asteroid Bennu. I'm removing it in a separate PR.

**Comment by Keeper1st** [comment]
> Cool. the ojbect_brown_dwarf still looks a bit more fuzzy than the reset, I guess that's beyond salvage?

I just upscaled the original brown dwarf icon and added a bit of noise so it's better than the old one, but it's not an original texture. It was just an experiment. I might do the same with others in lieu of having actual new high-res textures to work with.

**Comment by Keeper1st** [comment]
Oops. Seeing these in the PR, I realize I didn't reduce the size of some of them correctly (or at all in one case!).

**Comment by Web-eWorks** [comment]
Are there any further changes to these icons @nozmajner / @Keeper1st? If not, I'd like to merge this in soonish.

**Comment by nozmajner** [comment]
Good to go in my opinion.

**Comment by Keeper1st** [comment]
I probably should at least change the size of one or two of them into the standard aspect ratio and reduce the size of the one I forgot to, but it's not deal-breaking for them to be the size they are.

**Comment by zonkmachine** [comment]
Even though this is an improvement from before I have some thoughts.
* The wave stuck on top of the gas giant image is a bit odd compared to known gas giants and other imaginations. Looks a bit more like cracks from a segment of a larger glacier.
* Maybe Bennu isn't a good representation for asteroids in general. Especially so since it was recently the subject of a sample return mission and is known for that reason. No hating on 101955 Bennu intended.
* As I mentioned above the icon on top of the asteoid is annoying. I suggest removing it.
```diff
--- elseif forWorld and not isOrrery and obj.ref.superType ~= "STARPORT" and obj.ref.type ~= "PLANET_ASTEROID" then
+++ elseif forWorld and not isOrrery and obj.ref.superType ~= "STARPORT" then
```

**Comment by Keeper1st** [comment]
I could make one from a different, less round asteroid, if desired.

**Comment by impaktor** [comment]
Regarding icon upscale, how's 140 Mega pixel image of the sun?

**Comment by Web-eWorks** [comment]
Are there any blockers to merging this PR?

**Comment by impaktor** [comment]
> I probably should at least change the size of one or two of them into the standard aspect ratio and reduce the size of the one I forgot to

@Keeper1st I interpret this as we hold on merging this until it's done? Ideally, we try to keep iterating binary files down, i.e. don't merge binary things we know will shortly need change. (Maybe "we" = "I"?)

**Comment by Keeper1st** [comment]
Someone just needs to resize those two or three that I forgot to. I no longer have access to Photoshop, alas. I can try to learn to use GIMP at some point...

**Comment by impaktor** [comment]
@nozmajner I assume we want this in master prior to pioneer day? 
1 year old almost.
So this needs a fix-up commit that re-scales some of the assets, then a rebase? I could do that, if given instructions which assets need fixing.

**Comment by impaktor** [comment]
@Keeper1st Alternative if you'd like to do it In GIMP, go to the Image menu, select Scale Image. Then File -> "Export As" or "Export".

**Comment by nozmajner** [comment]
I'd say it is good to go. I was using it for quite a while on my install, and did not spot anythig sore. And it is a really nice step up i quality. And if anythig sticks out later, it an be fixed then.

**Comment by RacerBG** [comment]
I have been tinkering around with GIMP lately and I need your opinion about my approach:

planet

Note: This is just a test image and I'm NOT a graphical designer.

PS: Also what should be the default resolution of those images?

**Comment by Web-eWorks** [comment]
While we do eventually plan to replace these icons entirely with real-time rendered versions of the planets in question, these are a quite nice step up from the previous versions. Thank you very much @Gisteron and @Keeper1st!

**Pull request merged**
