### PR TITLE
Restore a lost feature

### PR DESCRIPTION
**Pull request by mike-f1**
Game can again show no icons and no label,
show only icons or show both.

### CODE REVIEW

**Comment by Web-eWorks** [comment]
@mike-f1 as a suggestion, have you tried using the `if` statement to conditionally call the `ui.addStyledText` that displays the label? Seems to me like it'd be much better to not call that at all instead of calling it with an empty string to display.

**Comment by mike-f1** [comment]
Done.

Please keep commit history, thank's

**Comment by Web-eWorks** [comment]
Looks good to me, thanks @mike-f1! I'll give this a thorough testing tomorrow and hopefully it'll be good to merge.

**Comment by Web-eWorks** [comment]
Sorry about the testing delay, I had an unexpected hardware failure. Seems very straightforward and I uncovered no bugs.

**Pull request merged**
