### PR TITLE
Fix build under OSX

### PR DESCRIPTION
**Pull request by pcercuei**
Two commits to fix building of Pioneer under OSX.

### CODE REVIEW

**Comment by impaktor** [comment]
Nice. Will Appveyor be able to build OSX after this is merged, me wonders?

**Comment by pcercuei** [comment]
AppVeyor only builds Windows stuff. But we could make OSX builds on Travis.

**Comment by Web-eWorks** [comment]
Give me some time to reverse-engineer the OS X build script and I'll see what I can do about getting Travis to build our OSX builds.

**Comment by impaktor** [comment]
> AppVeyor only builds Windows stuff. But we could make OSX builds on Travis.

Ops, that's what I meant.

> Give me some time to reverse-engineer the OS X build script and I'll see what I can do about getting Travis to build our OSX builds.

Did "we" ever get Travis to do an OSX build? I'm getting senile. I think it came pretty far, but I don't think any OSX user verified if it worked?

**Comment by impaktor** [comment]
If anyone needs a tag pushed to test build system, just say the word (I've been afk for a few days).

**Pull request merged**
