### PR TITLE
Include decouple

### PR DESCRIPTION
**Pull request by mike-f1**
Speed up compile time decoupling includes
and using forward declaration.

### CODE REVIEW

**Comment by Web-eWorks** [comment]
You will need to run clang-format on your changed code and squash your commits before we can merge this.

Clang-format will only reorder includes in the same block, so if header reordering is causing issues for you, you can place a blank line between blocks of includes.

**Comment by fluffyfreak** [comment]
@Web-eWorks Can we disable the header reordering, I don't see a case where it's the correct behaviour.

@mike-f1 you removed the file `pioneer`, can your restore that please. It needs updating for use CMake (_which someone else can do, you don't have too_) rather than removing it.

**Comment by Web-eWorks** [comment]
@fluffyfreak We can do that. I'll disable that in a new PR, and update the pioneer script in #4511.

**Comment by mike-f1** [comment]
Should I do something about conflict?

**Comment by pcercuei** [comment]
@mike-f1, you should rebase on top of master, and fix the conflicts, yes.

**Comment by fluffyfreak** [comment]
@mike-f1 if you can resolve it and push the fixes that'd be helpful.
Either via rebase or merge. I don't mind but @impaktor might have a suggestion/preference.

**Comment by mike-f1** [comment]
Well, probably I did something wrong when I run "clang-format" on my own local
branch and I will amend that commit.

But I note it Travis fail because `#endif //something` is not conform to actual rules...
It shouldn't be the opposite or this is what you want?
(I say this only because AFAIK this tool seems just introduced)

**Pull request merged**
