### PR TITLE
Bugfix to avoid damaging ships when you have permission to dock and fly trough spacestation (#3997)

### LINKED ISSUE #3997: Collision at the orbital gates (landing collision damages ship)
### Observed behaviour
On current master ([9c8c112](https://github.com/pioneerspacesim/pioneer/commit/9c8c11276eaa10b7db020790093798ce150143c2)) orbital station and ground station docking collision meshes also do damage to the ship. 
That might be expected from a hard landing to a ground station, but collision sounds even play if you drop from a cm or so above the pad. And you also get damaged when you are flying trough the gates of the orbitals.

### Steps to reproduce
Ask for docking permission and fly into the station. Without permission you will fly trough unharmed, with permission you get damage (based on your speed, as in any other collision). It happens with the autopilot too, but that slows down the ship upon docking, so it's not that noticable. But try flying trough fast:
stationcollision
(Cropped awkwardly, because I wanted to show the hull gauge appearing. I'm flying towards the center of the hole, no collision is happening to the station itself)

Doesn't happen on the current release (2017-0415).
Maybe the [37aac98](https://github.com/pioneerspacesim/pioneer-thirdparty/commit/37aac98f00ed634739ccc464284e2fcbd07924e0) libassimp update on Thirdparty?

My rig is Win7 64 bit, builded with VS2015.

### PR DESCRIPTION
**Pull request by mike-f1**
closes #3997

### CODE REVIEW

**Comment by impaktor** [comment]
Could you please edit your first post and say "closes #3997", or "fixes #3997", so it will [auto-close](https://help.github.com/articles/closing-issues-via-commit-messages/ ) the issue when this is merged?


(Yes, I could do it, but this way you're more aware of it).

**Comment by mike-f1** [comment]
@impaktor : like that?

**Comment by nozmajner** [comment]
The title was fine, impaktor refered to the description text.

**Comment by impaktor** [comment]
Well, it's right now, after @nozmajner comment and your fix.

For future, this doesn't stop you from adding more text if needed. You can look at old closed/merged pull requests. I was going to use #3973 as an example, but I think that second/last sentence in the opening message is actually an edit/addition by me, if I remember right, not that it shows, though.

Yeah, so I have no more comments on this. Thanks!

**Pull request merged**
