### PR TITLE
Introduce Tech Level to stations - makes them more unique

### PR DESCRIPTION
**Pull request by impaktor**
# Tech Levels

Here I go again with one of my "limit game content exposure to player", but I'm very happy with this one as it really improves the game I think, making each station a bit more unique. This implements what I discussed in the top post on the dev-forum [Tech Levels for ship equipment](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=235), by giving each station a tech level, with some distribution (the [convolution](https://en.wikipedia.org/wiki/Convolution) of two square waves), which then influences what equipment is supported (bought/sold) on in the equipment market. (Note: this does not affect the Second Hand market module on the BBS, which I think is as it should be).

Tech levels lead to more interesting game play I think (pretty much exactly like in Frontier):
- "Oh, this was a good station!"
- "Wow, there's an _Advanced_ ECM as well? Never seen that before!"
And of course:
- "Blast! This station doesn't have <gadget> I desperately need, maybe one city over has it?"

Caveat: last commit adds a "Military" tech level, just like in frontier. And just like in frontier it's "Tech Level 11" that is "special" in being "military", thus no station will show "tech level 11 in the Lobby", since they will instead show "military installation" or what ever (see screen shot).

screenshot-20151027-150622
(I think the text doesn't fit on my 640x800 resolution, but you get the idea.)

## Table of levels

I used the system from Frontier as base mainly because it was (in my opinion) a well constructed system, and also it's what many/most of the pioneer players are used to, and how they expect it to work. So at tech level 12 all equipment is available except those with level "MILITARY" ("MIL" in table below), which are only available at tech level 11 stations. A bit quirky, that Military drive class 2 is only available at these military installations. Just like Frontier. I liked it, so I kept it like that.

```
| Equiptype             | Description                                | pioneer | frontier |
|                       |                                            |    tech |     tech |
|-----------------------+--------------------------------------------+---------+----------|
| MISSILE_UNGUIDED      | unguided rocket (MISSILE)                  |       1 |        - |
| MISSILE_GUIDED        | guided missile (MISSILE)                   |       5 |        5 |
| MISSILE_SMART         | smart missile (MISSILE)                    |      10 |       10 |
| MISSILE_NAVAL         | naval missile (MISSILE)                    |     MIL | 11 / MIL |
| ATMOSPHERIC_SHIELDING | atmospheric shielding (ATMOSHIELD)         |       3 |        3 |
| ECM_BASIC             | basic ECM system (ECM)                     |       9 |        9 |
| SCANNER               | scanner (SCANNER)                          |       3 |        4 |
| ECM_ADVANCED          | advanced ECM system (ECM)                  |     MIL | 11 / MIL |
| UNOCCUPIED_CABIN      | unoccupied passenger cabin (CABIN)         |       1 |        1 |
| PASSENGER_CABIN       | occupied passenger cabin (CABIN)           |       1 |        1 |
| SHIELD_GENERATOR      | shield generator (SHIELD)                  |       8 |        8 |
| LASER_COOLING_BOOSTER | laser cooling booster (LASERCOOLER)        |       8 |        8 |
| CARGO_LIFE_SUPPORT    | cargo bay life support (CARGOLIFESUPPORT)  |       2 |        2 |
| AUTOPILOT             | autopilot (AUTOPILOT)                      |       6 |        6 |
| RADAR_MAPPER          | radar mapper (RADARMAPPER)                 |       9 |        9 |
| ADVANCED RADAR_MAPPER | Advanced radar_mapper                      |      11 |        - |
| fuel_scoop            | fuel scoop (FUELSCOOP)                     |       4 |        4 |
| CARGO_SCOOP           | cargo scoop (CARGOSCOOP)                   |       5 |        5 |
| MULTI_SCOOP           | multi scoop                                |       9 |        - |
| HYPERCLOUD_ANALYZER   | hyperspace cloud analyser (HYPERCLOUD)     |      10 |       10 |
| HULL_AUTOREPAIR       | hull auto-repair system (HULLAUTOREPAIR)   |     MIL | 11 / MIL |
| SHIELD_ENERGY_BOOSTER | shield energy booster unit (ENERGYBOOSTER) |      11 |       11 |
| DRIVE_CLASS1          | class 1 hyperdrive (ENGINE)                |       3 |        5 |
| DRIVE_CLASS2          | class 2 hyperdrive (ENGINE)                |       4 |        7 |
| DRIVE_CLASS3          | class 3 hyperdrive (ENGINE)                |       4 |        9 |
| DRIVE_CLASS4          | class 4 hyperdrive (ENGINE)                |       5 |       10 |
| DRIVE_CLASS5          | class 5 hyperdrive (ENGINE)                |       5 |       12 |
| DRIVE_CLASS6          | class 6 hyperdrive (ENGINE)                |       6 |       12 |
| DRIVE_CLASS7          | class 7 hyperdrive (ENGINE)                |       8 |       12 |
| DRIVE_CLASS8          | class 8 hyperdrive (ENGINE)                |       9 |        - |
| DRIVE_CLASS9          | class 9 hyperdrive (ENGINE)                |      10 |        - |
| DRIVE_MIL1            | class 1 military drive (ENGINE)            |      10 |       11 |
| DRIVE_MIL2            | class 2 military drive (ENGINE)            |     MIL | 11 / MIL |
| DRIVE_MIL3            | class 3 military drive (ENGINE)            |      11 |       12 |
| DRIVE_MIL4            | class 4 military drive (ENGINE)            |      12 |        - |
| PULSECANNON_1MW       | 1MW pulse cannon (LASER)                   |       3 |        4 |
| PULSECANNON_DUAL_1MW  | 1MW dual-fire pulse cannon (LASER)         |       4 |        - |
| PULSECANNON_2MW       | 2MW pulse cannon (LASER)                   |       5 |        - |
| PULSECANNON_RAPID_2MW | 2MW rapid-fire pulse cannon (LASER)        |       5 |        - |
| PULSECANNON_4MW       | 4MW pulse cannon (LASER)                   |       6 |        5 |
| PULSECANNON_10MW      | 10MW pulse cannon (LASER)                  |       7 |        - |
| PULSECANNON_20MW      | 20MW pulse cannon (LASER)                  |     MIL | 11 / MIL |
| MININGCANNON_17MW     | 17MW blast-mining cannon (LASER)           |       8 |        8 |
| SMALL_PLASMA_ACCEL    | small plasma accelerator (LASER)           |      10 |       12 |
| LARGE_PLASMA_ACCEL    | large plasma accelerator (LASER)           |      12 |       12 |
| TRADE_ANALYZER        | Trade Computer                             |       9 |        - |
```

## Tech level distribution in Frontier

I don't know where I got the data for this from, but it shows that most stations in Frontier were just level 2 stations.

histrogram

## Tech level distribution in Pioneer

(I first thought a Poisson distribution would be fun (dashed line), but turns out the probability for stations above 8 was next to zero. Ideally, I'd like to make low tech level stations a bit more common. But this (full line) will do for now)
tech_level

Which is what you get when you add two independent random numbers from uniform (square) distribution of different width:

convolution

## Future

- With this addition, I think there's a strong need to be able to set tech level manually from custom scripts, so that tech level of say, Earth (London, etc.), is high. Or better: stations have a `size`, from which station model is selected, and this `size` also influences BBS adverts, tech_level, ship adverts, etc.

- Also, open question: is there some system wide tech level, that in some way guarantees the level of individual stations, like:
  1. minimum tech level?
  2. maximum tech level?
  3. highest techlevel found in system?

## FIN

- I'll clean up the branch, looks a bit weird atm, with commits from Andy (DONE).
- I'd like this to be merged with our BIG SAVE BUMP build together with #3485.

### CODE REVIEW

**Comment by clausimu** [comment]
Absolutely great! And I agree for the need to link station size to tech level in the future. In general, I would think that everything depends on population: population size -> station size -> station tech level, with a linear shift up/down depending on overall faction tech level.

**Comment by fluffyfreak** [comment]
What I really love about your PR's are the graphs, charts and other niceties! :)

...oh and the PR itself of course.

**Comment by laarmen** [comment]
You're going to hate me.

Because I don't like it. Well, I like the idea. A lot. (but then again, it's not yours it's Braben's, ain't it? ;-) )

However, the implementation irks me. Why, ô why would you think it is a good idea to add such a high level attribute in the C++ object? Granted, you don't have much of a choice, since it must be added at the construction of the SpaceStation object, right? Wrong. The techlevel attribute isn't used anywhere in the C++ code, nor should it be.

What we need here is some way for Lua to specify a constructor also for C++ objects, that would be run the first time the userdata is pushed to Lua.

Mmmmh, lemme think about that one...

**Comment by impaktor** [comment]
Where to place the assignment of the `tech_level` is something I did scratch my head over, but if you figure out something better that's good. 

> You're going to hate me.

Not at all. You objection is warranted, but I'm not at all what a fix would look like. Feel free to give me some commits to cherry-pick! :grinning:

**Comment by fluffyfreak** [comment]
I don't mind which of our two programming languages it goes in, although I do understand C/C++ better ;)

Also it is a case of where and how does it go in if not in the current way?

**Comment by laarmen** [comment]
The plan is to basically make the C++ call SpaceStation.New (and
Player.New, and whatever else you want) when it pushes an object of the
right kind onto the stack.

However, I'm having bootstrap problems : we have modules that instanciate
objects very soon in the whole process (typically, Game.pioneer) so I need
to make sure that

1/ data/libs/*.lua is processed before those instanciations
2/ Nothing uses directly the early objects in libs.

**Comment by laarmen** [comment]
If I do things right, it'll go in data/libs/SpaceStation.lua with something
like

```lua
SpaceStation.New = function (station)
    station.setprop("tech_level",
pick_randomly_according_to_a_nice_random_distribution() )
end
```

My rationale with it not being in the C++ side is that it makes things
harder for modders (and devs) to understand when features are split accross
the two languages. At least that way it'll be easy for forkers (although
probably not modders) such as @walterar to replace the function with
something different (even just hardcoding 11 to have all the cool stuff
everywhere)

**Comment by fluffyfreak** [comment]
@laarmen ok that's sounds like a plan, but a future one rather than something we can deal with right now. So does it make more sense to merge this and then when that change to Lua happens to convert everything in one big lump?

**Comment by impaktor** [comment]
@fluffyfreak laarmen said (IRC) that he'll have a stab at it tonight. When do you want to do The Big Merge? This weekend? Or when you get your computer back?

**Comment by fluffyfreak** [comment]
I think I'll poke Geraldine and see when she'll push out the ModDB update.
Once she's taken that copy then we should go merge-crazy and get everything. Gives us a month to deal with any issues the early adopters find.

**Comment by impaktor** [comment]
Sounds like a plan. I was also thinking about poking @robn to hold off on the builds until we done the Big Merge, then poke him for a build for the SSC people to test.

Geraldine is a she? Neat. I just assume everyone is an anti-social man living a life infront of the computer. I think on average I might not be too far off.

**Comment by laarmen** [comment]
Géraldine is a typical female first name in France. Well, typical...

**Comment by fluffyfreak** [comment]
Erm, that's a good point! I had assumed 'she' since in the UK 'Gerald' is male and 'Geraldine' would normally be a womans name. Hope I haven't insulted them.

**Comment by impaktor** [comment]
OK, I've updated the commits, to now make use of @laarmen's implementation.  But, as is usual for a weekend for me, this is 100% un-tested, so the following aught to be tested:

0. Does pioneer crash on start?
1. Does different stations have different tech level? (check Lobby screen) 
2. Is the equipment sold filtered? I.e. not showing 100% of purchasable eqip.(compare Lobby tech level, with some example equipment from the table in my first post)

Thanks laarmen for collaboration!

**Pull request merged**
