### PR TITLE
new hotkey for landing gear

### PR DESCRIPTION
**Pull request by joonicks**
default: g

### CODE REVIEW

**Comment by nozmajner** [comment]
G is already used for decreasing the set-speed setting (T increases).

**Comment by fluffyfreak** [comment]
`F6` is the current Toggle landing gear key

**Comment by nozmajner** [comment]
I like the notion of moving it from the F-keys to somewhere rebindable. Freeing them up for UI function and such is a good direction in my opinion.
But I think  T and G for Set Speed should stay there, so you can reach every important control on that side of the keyboard.
How about defaulting it to H or V? V is closer to WASD, so might be more comfortable. True, it doesn't rhymes that nicely as with G, but I doubt there's any other hotkey in Pioneer that lines up with its first letter anyway.

**Comment by joonicks** [comment]
z and x seems unused.... check y0 staging!

**Comment by nozmajner** [comment]
Z sounds good to me.

**Comment by joonicks** [comment]
I was suggesting z and x for setting thrust while keeping g for gear

**Comment by nozmajner** [comment]
Z and X isn't as comfortable to reach in my opinion, and Z and Y tend to switch places on some international keyboard layouts too.
And T and G have a bit of directionality to them, like WASDRF for the lateral directions.

**Comment by clausimu** [comment]
I agree with @nozmajner regarding the "z" - switches position with "y" on US vs. German keyboard. That sometimes messes up hotkey layout things.

**Comment by mooskagh** [comment]
I think key bindings should not (and currently do not, I guess) depend on keyboard layout. Otherwise it's complete mess for Dvorak users, and also for people with multiple layouts (e.g. Russian) finding out that keyboard doesn't work because you didn't change layout is pretty annoying.

**Comment by The-EG** [comment]
Why not leave the default at F6, but have this allow it to be changed for those users that want to?

As commented on in #3799, key bindings are going to have to be cleaned up/overhauled at some point with moving everything to ImGui, so we will likely be talking about it more in the future.

**Comment by fluffyfreak** [comment]
Closing

**Pull request closed without merging**
