### PR TITLE
Fix the UI strange rendering.

### LINKED ISSUE #2779: Invisible ink
someone has the same? vs2013 error?
screenshot-20140221-191754
screenshot-20140221-191758
screenshot-20140221-191802

mostly when minimize/maximize game window.

### LINKED ISSUE #3308: Strange rendering
After the latest merges yesterday/today: #3303 (and #3306) I'm seeing some pretty funky stuff.

When flying it seems like the ground, or parts of it, follows me up into the air, and it looks like the city buildings are sunk into the earth when starting a game. It's a bit difficult to take a screenshot of, since a video would be needed to show it properly, but this is also pretty strange:

screenshot-20150108-110454

screenshot-20150108-111201

Interestingly, Barnard's Star seems to work fine, but not starting from a planet side space port.

### PR DESCRIPTION
**Pull request by fluffyfreak**
Clear the depth buffer so that it draws the UI fresh.

Trying to fix #3308 and fix #2779

Slight problem is that I can't test it, Linux users (@impaktor) please give it a try!

### CODE REVIEW

**Comment by impaktor** [comment]
Will give it a try tomorrow. 
Thanks.

**Comment by impaktor** [comment]
OK, tested this just now.
BBS is fixed by this but not world view. The ground is too high up, and "follows me around" so to say, so that part is still as in #3308.

**Comment by fluffyfreak** [comment]
This is a bit brute force of an approach but should definitely work.

**Comment by radius75** [comment]
Wow, it also fixes  #2779 for me.

**Comment by impaktor** [comment]
> Wow, it also fixes #2779 for me.

Awesome.

I'll test this ASAP, which for me will be on Monday (if this isn't merged before then).

**Pull request merged**
