### PR TITLE
Control how many stars in the sky

### LINKED ISSUE #3343: Too many stars in sky background
Something changed with the sky background recently. There are many more stars and they seem much smaller. The disadvantage is that it is getting too noisy and distracting (especially in dogfights, when you are trying to follow the crosshairs, etc.). Can the number of stars be reduced - or even better, the brightness and "crispness" be reduced to make it more of a background feature?

### PR DESCRIPTION
**Pull request by fluffyfreak**
After many complaints to fix #3343 I've implemented a slider to adjust from 0% to 100% the number of stars in the star field.

Andy

### CODE REVIEW

**Comment by walterar** [comment]
error: [string "[T] @ui/Settings.lua"]:130: attempt to concatenate local 'caption' (a nil value)
stack traceback:
	[string "[T] @ui/Settings.lua"]:130: in function 'starDensity'
	[string "[T] @ui/Settings.lua"]:158: in function 'template'
	[string "[T] @ui/Settings.lua"]:355: in function 'template'
	[string "[T] @libs/ui/TabView.lua"]:130: in function 'SwitchToNum'
	[string "[T] @libs/ui/TabView.lua"]:96: in function 'AddTab'
	[string "[T] @ui/Settings.lua"]:362: in function 'Settings'
	[string "[T] @ui/MainMenu.lua"]:78: in function <[string "[T] @ui/MainMenu.lua"]:76>

**Comment by walterar** [comment]
This happens when another non-English language is used. No problem of this PR. But it is a problem.

**Comment by walterar** [comment]
run Pioneer
In config; set "Density of Star field" 20%
leave
run Pioneer
In config; "Density of Star field" 100%

Furthermore, I see no difference in density in any point between 0 and 100

Linux

**Comment by impaktor** [comment]
> This happens when another non-English language is used. No problem of this PR. But it is a problem.

You can't chose any other language than English in a PR, since this isn't merged, that new string hasn't been copied to any other language file by the bot yet, so a crash is expected for any un-merged code that tries to access a new language string.

**Comment by fluffyfreak** [comment]
@walterar 
> Furthermore, I see no difference in density in any point between 0 and 100

I said in the description:
> If you do this ingame you will need to jump to another system, or quit and start/load for it to take effect.

**Comment by fluffyfreak** [comment]
I had omitted a call to save the config file after changing the settings :(

Is there a way to call a function on closing the options screen? @impaktor / @laarmen

**Comment by impaktor** [comment]
> Is there a way to call a function on closing the options screen? 

Not sure. I'll pass that question on to @johnbartholomew. 
Hack: add a button next to the slider to save it?

So you have a slider now? Would having a text (number) input field make it simpler?

**Comment by walterar** [comment]
"You can't chose any other language than English in a PR"

If you do not admit there is a problem, you'll never see the solution

This is one of the solutions that come to mind at this time, can be improved.

--- /pioneergit2/data/ui/Settings.lua
+++ /pioneergit2/data/ui/Settings.lua~
@@ -123,14 +123,14 @@
   local fullScreenCheckBox = optionCheckBox(
    Engine.GetFullscreen, Engine.SetFullscreen,
    l.FULL_SCREEN)
-
+  local capt = l.STAR_FIELD_DENSITY or "Density of Star field"
   local starDensity = function (caption, getter, setter)
    local initial_value = getter()
    local slider = ui:HSlider()
    local label = ui:Label(caption .. " " .. math.floor(initial_value * 100) .. "%")
    slider:SetValue(initial_value)
    slider.onValueChanged:Connect(function (new_value)
-     label:SetText(caption .. " " .. math.floor(new_value * 100) .. "%")
+     label:SetText(capt .. " " .. math.floor(new_value * 100) .. "%")
      setter(new_value)
     end)
    return ui:VBox():PackEnd({label, slider})
@@ -155,7 +155,7 @@
     cockpitCheckBox,
     compactScannerCheckBox,
     confirmQuit,
-    starDensity(l.STAR_FIELD_DENSITY, Engine.GetAmountStars, Engine.SetAmountStars),
+    starDensity(capt, Engine.GetAmountStars, Engine.SetAmountStars),
    })))
  end

Andy

manual changing config.ini

AmountOfBackgroundStars = 0.05
or
AmountOfBackgroundStars = 0.80
or
AmountOfBackgroundStars = 1.0

no difference

**Comment by fluffyfreak** [comment]
@impaktor it's saving now, I fixed that up earlier. 
About @walterar problem I have no idea, it works fine for me - but you do have to quit the game, and start/load one before you see the difference.

If I could call something when the options screen closed then I could refresh the background so that would not be necessary.

**Comment by fluffyfreak** [comment]
I should also note that I'm just trying to do a build on my Linux box to test it.

**Comment by fluffyfreak** [comment]
Ok I've tested it on Linux and it built and works perfectly. I'm not sure why you're having a problem @walterar, please not it won't affect any stars baked into a skybox texture, only the point stars.

**Comment by walterar** [comment]
No 3431 With  "static const int BG_STAR_MAX = 5000;"  in Background.h
no_3431

With 3431. With AmountOfBackgroundStars = 0.05 in config.ini
with_3431

**Comment by fluffyfreak** [comment]
Ok, thanks @walterar but on Linux and Windows it works fine for me and we're going to need a 3rd party (@impaktor / @johnbartholomew / @laarmen) to help investigate it further.

Some questions to help:
 - Did you pull the latest change I added earlier today?
 - Did you do a clean build?

**Comment by walterar** [comment]
Did you pull the latest change I added earlier today? yes  eec4e6e

Did you do a clean build? yes

**Comment by fluffyfreak** [comment]
@johnbartholomew or @laarmen how would I go about calling a function when closing the options screen?
What I'd like to do is refresh the background when the options screen closed, rather than wait for the player to jump systems / reload.
Also how can I get the slider and title to appear on the same line instead of one after the other?

**Comment by shadmar** [comment]
Here is a nice wormhole effect (all glsl)
http://glslsandbox.com/e#27050.0

**Comment by impaktor** [comment]
@shadmar looks cool. What I like about our current one is that it has a natural transition from normal space to hyperspace.

**Comment by impaktor** [comment]
Setting the slider to lowest:

    pioneer: VertexBufferGL.cpp:61: Graphics::OGL::VertexBuffer::VertexBuffer(const Graphics::VertexBufferDesc&): Assertion `m_desc.numVertices > 0' failed.

**Comment by fluffyfreak** [comment]
I should probably run that range from 1 (or another sensible minimum) upwards instead of from 0, thanks :)

**Comment by johnbartholomew** [comment]
@fluffyfreak Something like this: https://github.com/fluffyfreak/pioneer/compare/howmanystars...johnbartholomew:howmanystars

Completely untested. Won't do quite the right thing for the Save button on the in-game settings menu (it'll trigger the refresh code when the user presses the "Save Game" button, even though the settings menu hasn't been closed), but probably good enough for a first version.

**Comment by fluffyfreak** [comment]
Ah-ha so that's how you do it, thanks @johnbartholomew :)

**Comment by walterar** [comment]
Now it works! Tested on Linux and Windows (MXE)

:+1:  FIRE IN THE HOLE !!! ;)

**Comment by walterar** [comment]
I do not understand why BG_STAR_MAX value is different from AmountOfBackgroundStars

And if you try K.I.S.S. method? :)

**Comment by fluffyfreak** [comment]
Because `BG_STAR_MAX` is the upper limit of the value, whereas `AmountOfBackgroundStars` is the value itself.

Which is why you see it being clamped between `BG_STAR_MIN` (the lowest value) and `BG_STAR_MAX` (the maximum value).

The sliders values have to be limited in a different way because they run from 0.0 to 1.0, therefore I limit them to `0.01` to mean 1% and `1.0` to mean 100%

**Comment by walterar** [comment]
K.I.S.S.

**Comment by fluffyfreak** [comment]
@walterar that couldn't be any simpler. It is simple. 
The one complication with it is because I didn't want to refresh the background each time the slider moved so it has to be done via a lua registered callback.

**Comment by fluffyfreak** [comment]
There, that should always work by effectively setting a dirty flag when the amount of stars is changed.
It's a bit ugly, but it's almost infallible.

**Comment by walterar** [comment]
With AmountOfBackgroundStars=0.05 always starts with 100,000 stars

**Comment by fluffyfreak** [comment]
@walterar clarify "starts with", do you mean in the start screen?

**Comment by walterar** [comment]
In the start screen and into the game

**Comment by fluffyfreak** [comment]
Ah ok, thanks @walterar

**Comment by walterar** [comment]
This is what I see https://dl.dropboxusercontent.com/u/15391580/Pioneer/4a4c1e8.avi

**Comment by Marcel-T** [comment]
This discussion gave me the idea of a dynamic slider. When the player is in the outer reaches of a solar system the slider would be set to maximum, and when close to a star the slider would be set to minimum, with a function based on distance or lumens to determine the slider setting dynamically. It could be toggled on the option screen.

**Comment by fluffyfreak** [comment]
That would be one hacky way to do it, really though we could do with HDR rendering and then everything just, sorts itself out.

That and a way of generating the background galaxy-scape.

**Pull request merged**
