### PR TITLE
WIP: Systems Editor

### PR DESCRIPTION
**Pull request by mooskagh**
That was initially PR #4173, but I had to revert that because I messed up git branches. Sorry for the noise.

So far it's not an editor but "viewer" that shows ugly tables.
Deps: python3 only, no other libs needed.
(may also work under python2 but I doubt).

Running:

1. Start main.py
2. Open http://localhost:9914/ in browser

In progress:

1. Make it editor rather than viewer

Next steps:

1. Tidy up tables.
2. Add better display of values (type-specific, e.g. mass angle etc)
3. Add simple graphical visualization of systems.

---
This change is [Reviewable](https://reviewable.io/reviews/pioneerspacesim/pioneer/4291)

### CODE REVIEW

**Comment by SpifforOmnivore** [comment]
Well, I'm very interested :+1: 
Currently, I'm creating my custom systems "by hand": I manually copy all system info with my keyboard, looking at one screen playing Pioneer, and writing the system.lua on the other screen.

Maybe also it would help other people who have ideas for custom systems, but don't want to delve in lua files

Is there any way to test this PR?

**Comment by fluffyfreak** [comment]
@SpifforOmnivore this PR would be great to have, however you're doing it all by hand?

Open the console window ingame and type `import("Game").system:ExportToLua()`, that'll export the system that you're in to a lua file with the same name as the system.

**Comment by SpifforOmnivore** [comment]
Thanks very much Fluffyfreak for the tip! :+1:

**Comment by impaktor** [comment]
@SpifforOmnivore I suspect the wiki is lacking/lagging behind on documentation for custom systems, so please feel free to add useful information there, on how to write [custom systems](https://pioneerwiki.com/wiki/Custom_Systems)

**Comment by Web-eWorks** [comment]
Rather than implementing this in an external tool (and having to write a Lua parser by hand, etc.), wouldn't it just be simpler to implement this as an in-game tool (or another game mode, similar to the modelviewer)?

You haven't provided any screenshots or information about what specifically you want this tool to do, so I can't really provide pros and cons of doing this in an external tool vs. in-game, but I can say that introducing 2.2k+ lines of Python and making this a web-based tool is going to introduce a *significant* amount of upkeep and support work.

It's understandable if you don't have much Lua/C++ experience, but especially for the visualization of the system, I'd prefer to leverage the already-existing renderer / code for this purpose rather than write an entirely new, unsupported (even if simple) visualization and editing tool. Additionally, if we use the game's existing visualization functions, live testing of the new system would be fairly easy to implement as well.

Admittedly, the downside to using the existing code for system visualization is that it may require a somewhat extensive rewrite to support changing a system's content on the fly (things may be keeping unchecked references where they shouldn't), but I haven't taken a thorough look at it yet.

I personally would be extremely hesitant to merge this PR given my limited understanding of these ramifications; but that's only my opinion, as I'm not part of the merge team.

**Comment by Web-eWorks** [comment]
Given this PR has set for at least a year and a half with no activity, and that it's introducing an entirely new Python codebase to visualize systems, I'm going to bite the bullet and close it.

If you'd like to bring this branch back up for merge, feel free to re-open it and address the concerns laid out above.

**Pull request closed without merging**
