### PR TITLE
Clang-format all the things!

### PR DESCRIPTION
**Pull request by Web-eWorks**
(Finally) Apply clang-format to the entire code base. Will likely need another pass to resolve hidden dependency errors (and as such the build will likely fail), but the first bit is done.

CC @impaktor: I'll get the clang-format stuff, you just handle updating the names and dates in your PR.

Now without Autotools files getting messed up!

Closes #4445.

### CODE REVIEW

**Comment by Web-eWorks** [comment]
@impaktor This PR has passed all tests. Modelcompiler is still broken, but everything compiles normally. Ready to merge when you are.

**Comment by impaktor** [comment]
All checks still fail...

So we're happy with this format, and the pointer alignment to be "right"?

ping C++-ers: @fluffyfreak, @ecraven, @johnbartholomew

**Comment by impaktor** [comment]
Also, since we're no longer touching all the files in the same PR as in the "happy new year" #4507, this needs rebasing.

**Comment by Web-eWorks** [comment]
Rebased, and with #4509, error free. Ready for merge at your discretion, @impaktor.

**Comment by impaktor** [comment]
Does anyone have any objections to this PR that will molest the entire C++ code base? If not, I suggest we merge soonish.

**Comment by impaktor** [comment]
There are a bunch of warnings, unused variables, and such, I guess that could be fixed in the future.

Now we all need to add the git commit hook thingy, so a wiki on that would be great.

**Comment by Web-eWorks** [comment]
Will get that up in a bit.

**Pull request merged**
