### PR TITLE
Add custom system Wolf 359

### PR DESCRIPTION
**Pull request by impaktor**
I'm only partially through season 2 of [wolf 359](https://www.wolf359.fm/season1) but I felt the need to add it propperly to the game. I suppose it's good that I don't know what will happen, as events further into the series would be too much of spoilers, but I hope the podcast doesn't end with the station dissapearing or anything.

I tried giving the description some similar feel as the show has in my mind, perhpas with too much of a tilt towards Lovecraft...

I took the star mass, radius, temperature, and station orbit distance from wikipedia.

I'll likely do small rephrasing of the description text every time I re-read what I've written, but please don't hesitate to come with suggestions of or re-phrasing / nitpicks.

I believe @jmf and @nozmajner have listened to the podcast. 

The system only has a single station in orbit around the star, description in more human readable form below, as of first iteration:

```
The system is best known for the old 'deep space' research and signal station
Hephaestus, that is still orbiting the red dwarf of Wolf 359. It harkens back
to when humanity took its first trying steps out from its birth system of Sol.

As more information of its operation emerges, Hephaestus is becoming an
epicentre of many legends and myths. It is whispered that the then comparative
seclusion of the system made it ideal for prying human minds with nefarious
intentions, wanting to probe the inner workings of the universe and ask of it
questions that no mortal mind aught to meddle with. Officially, many of the
rumours are attributed to the deteriorating mental state of the minimal
skeletal crew that manned the station, which are chronicled in the their audio
recordings, some of which have survived to this day. One of the controversies
is whether the supposedly alien signal intercepted from Gliese 163 was merely
the effect of listening to too much static.

The low mass and temperature of Wolf 359 puts it right on the lower limit of
being able to maintain hydrogen fusion. Coincidentally, it bears many features
in common with Gliese 163.
```

### CODE REVIEW

**Comment by nozmajner** [comment]
I also thought about putting this system in the game for a while, but then I trailed off on other stuff.
So \o/
The later seasons will clarify and deepen some stuff, so the description might not be spot-on in that regard, but still works for me anyhow. Maybe it could be a bit more obvious that it is referring to something the player should look up, but not sure how to do that.

**Comment by impaktor** [comment]
Yeah, I meant to make this WIP, as I should finish listening to it before merging. If it's possible to not be flat out wrong in the system description, then that would be better, so I'll revisit this. At the same time: no spoilers!

**Comment by vakhoir** [comment]
This is obviously not something for this PR, but... with what license is the podcast released?  can't find it for the life of me. But... why not have the logs be recoverable items that you can play in the game?

**Comment by Web-eWorks** [comment]
@vakhoir transcripts of episodes, you mean? Hmm... my copyright law is a little rusty but IIRC without an explicit license statement the text and audio falls under All Rights Reserved artist copyright, with license grants to e.g. iTunes for distribution. If you wanted to include logs in the game you'd need to keep it to a couple paragraphs so it falls under fair use, or contact the authors and get direct permission to include the transcript / audio of the podcast in Pioneer.

**Comment by vakhoir** [comment]
No, I meant the actual episodes. Elite: Dangerous has these newscasts you can play for example, thought it would be cool to have something to listen to ingame.

Yeah, I was afraid standard copyright might apply, but some podcasts are published on Creative Commons, I hoped it would be one of those cases.

**Comment by nozmajner** [comment]
[The show isn't Creative Commons, as far as I can tell.](https://www.wolf359.fm/credits)

**Comment by fluffyfreak** [comment]
@impaktor I'm happy to merge this if no other changes pending.

**Comment by impaktor** [comment]
@fluffyfreak please hold on this, as I need to finish season 3 and 4, so I know if the description I've written is incompatible with what happens in the show.

Feel free to comment my English. I think I managed to produce some sentences that felt odd. Or don't, as I might re-phrase some of them.

**Comment by impaktor** [comment]
OK, I finished the show now, did some very small change to the text, but I think I'm finished with this PR now

**Pull request merged**
