### PR TITLE
test irc notification

### PR DESCRIPTION
**Pull request by ecraven**
Check whether this correctly runs the irc bot from travis.

### CODE REVIEW

**Comment by ecraven** [comment]
also test github webhooks

**Comment by ecraven** [comment]
one more try

**Comment by impaktor** [comment]
What's the rationale between `travis-jameson` and `travis_jameson` (beside one being lispier)? The latter (old/original) version is what I registered at nickserv. I don't know about the status of the other one?

**Comment by ecraven** [comment]
> What's the rationale between `travis-jameson` and `travis_jameson`
> (beside one being lispier)? The latter (old/original) version is what
> I registered at nickserv. I don't know about the status of the other
> one?

None, I registered the former myself, but neither actually works.. I'll
keep trying to get it working.

**Pull request merged**
