### PR TITLE
Decouple terrain and related file

### PR DESCRIPTION
**Pull request by mike-f1**
Moved fractal definition in a separate file, moved ctor of `MinBodyData` in *.cpp,
thus forward declare `SystemBody` and include only `SystemPath`.

`TerrainFeature.h` has no needs to include `Terrain.h` and so `TerrainNoise.h`

...Some other includes I spotted here & there has been decoupled.

**EDIT:** ...added `GeoPatchContext.h|cpp` to the list

**EDIT2:** added some commits to make review easier, to be squashed

### CODE REVIEW

**Comment by mike-f1** [comment]
...I had to be really tired but last commit is fixing compiling AND enabling DEBUG_BOUNDING_SPHERES:
let me fix that thing.

**Comment by fluffyfreak** [comment]
I'll review this asap, just been busy with family visiting this weekend gone.

**Comment by mike-f1** [comment]
Bah, not a problem: I may use time to do something, like reordering public methods and naming of member variables in `GeoPatchContext`...

**Comment by fluffyfreak** [comment]
@mike-f1 did a little [sub-PR](https://github.com/mike-f1/pioneer/pull/13) for this PR

**Comment by fluffyfreak** [comment]
I'm not sure why appveyor is failing, it looks like the build succeeded but the `pushartifact` attempt is what actually failed.

**Pull request merged**
