### PR TITLE
Added travis build script for releases

### PR DESCRIPTION
**Pull request by Web-eWorks**
Per IRC, I have added a build process to allow Travis to generate our linux / MXE builds. This theoretically works correctly, though it is untested.

### CODE REVIEW

**Comment by Web-eWorks** [comment]
MXE builds are disabled as I don't have a good grasp on setting up that build system. Otherwise, Travis should build, package, and attach the distributable to a Github release when you tag a commit and push it to the repo.

**Comment by impaktor** [comment]
Squash last two commits, if possible, please?

**Comment by Web-eWorks** [comment]
@impaktor Commits are squashed.

**Comment by impaktor** [comment]
Let's merge and see what happens...

**Comment by impaktor** [comment]
> Let's merge and see what happens...

Travis did build fine, but as expected, failed to upload since we haven't specified encrypted key to give it that access.

Ref:
https://docs.travis-ci.com/user/deployment/releases/
https://docs.travis-ci.com/user/encryption-keys/

**Pull request merged**
