### PR TITLE
Fix 3310

### LINKED ISSUE #3310: Text Colouring is wrong.
@walterar has pointed out that some of the text colouring is black where it should be other colours.

This is after my recent #3304 merge

### PR DESCRIPTION
**Pull request by fluffyfreak**
Fix #3310 by refreshing the text when it changes colour, content or if the GameLog number of messages changes.

Andy

### CODE REVIEW

**Comment by walterar** [comment]
Tested ok. Thanks Andy, you're working a lot this year :)

**Comment by fluffyfreak** [comment]
@walterar thanks for testing :)

**Comment by walterar** [comment]
I have more, i have more :))

But I think, resolved 3240, 3311 and 3313, have a Pioneer engine "almost" stable.

**Comment by fluffyfreak** [comment]
Just keep opening issues, it keeps things simple if I can tackle them in pieces.

At work we have on nightmare issue that appears to have 12 separate problems in it! Things like that are a pain.

**Pull request merged**
