### PR TITLE
Add heavy atmospheric shielding, allows easier fuel scooping

### PR DESCRIPTION
**Pull request by richardpl**
"Stolen" from @impaktor old branch.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
This doesn't look like it help with pressure damage it just **increases** the drag factor which would make things worse for fuel scooping (_for example_) and for travelling in atmospheres.

It looks like it should instead affect the calculation around line [Ship.cpp LN 1092](https://github.com/pioneerspacesim/pioneer/blob/master/src/Ship.cpp#L1092) perhaps put the multiplier factor there instead?

**Comment by richardpl** [comment]
My math skills tell me this decreases the drag factor...

**Comment by fluffyfreak** [comment]
@richardpl dammit, sorry you are correct.

Is it still worth using the shield to increase the pressure resistance too?

**Comment by richardpl** [comment]
Yes, but by how much?

**Comment by fluffyfreak** [comment]
I'd guess that for now we try it with the same multiplier. If it needs to become a separate parameter later that's not too much work.

**Comment by fluffyfreak** [comment]
@richardpl are you going to make the change to the [relevent line](https://github.com/pioneerspacesim/pioneer/blob/master/src/Ship.cpp#L1092)?

**Comment by richardpl** [comment]
Not yet.

**Comment by fluffyfreak** [comment]
I added the changes so it increase the pressure resistance according to the `atmo_shield_cap`. Capped it with a minimum so it respects the default atmospheric pressure resistance otherwise you start taking damage immediately upon takeoff.

**Comment by fluffyfreak** [comment]
I think that ships without an atmo' shield will behave in exactly the same way as they used too.

The old pressure test never took into account having an atmospheric shield at all so multiplying pressure resistance by `1` is the same as the old test. It only improves if you have a heavy shield.

**Pull request merged**
