### PR TITLE
Small time acceleration limitation fix

### PR DESCRIPTION
**Pull request by laarmen**
This was at first only a thing about fixing missing braces, but it ended up a real fix \o/

See the commit log for the details. I wouldn't mind someone else's opinion, specifically @fluffyfreak since I don't know how to test because I don't even get what's the angular velocity length thingy. (I mean I get each word separately, but the three together...)

### CODE REVIEW

**Comment by fluffyfreak** [comment]
I think that it means the magnitude of the angular velocity, sometimes in vector maths Length & Magnitude are used interchangeably. Not sure what that value would actually represent in the real world though... because the angular velocity is how fast something is rotating around an axis yes? So it's magnitude/length should just be whatever that value is.

**Comment by fluffyfreak** [comment]
Ah I think it might be the magnitude of the speed of rotation around the xyz axes. So each axis has it's own velocity, and this is the magnitude of them all together. Best as I can tell from the code.

Will try to review this and some other stuff on my laptop tonight :)

**Comment by impaktor** [comment]
+1 for the name of the branch!

**Comment by fluffyfreak** [comment]
looking at that code around [L339](https://github.com/laarmen/pioneer/blob/im_alive/src/Game.cpp#L339) I'm ... well I'm not sure what it does, it's testing the ships angular velocity against a threshold divided by the time acceleration factor.

So, if the player is spinning really fast then don't allow time acceleration? It would have been really helpful for someone to have documented that code when they wrote it so we knew *why* it did it :/ oh well.

I don't see anything wrong with the code itself and it does clean things up a lot in there :)

**Comment by walterar** [comment]
I think this solves other important things too. But I need to test it several hours in real game to be sure.

I suspect that this area is responsible for many "rare" behaviors.

**Comment by impaktor** [comment]
> I think this solves other important things too

Are any of those "important things" / "rare behaviours" documented here on the issue tracker? 

> But I need to test it several hours in real game to be sure.

If you're going to spend hours testing, you could merge in many of our active PRs into the same temporary branch and see how they work together? Specifically all the save_bumping issues (pink/purple label).
(I'll update my law-and-order branch today to remove merge conflict and fix some cosmetic detail in it)

**Comment by walterar** [comment]
"¿Alguna de esas "cosas importantes" / "comportamientos raros" documentados aquí en el seguimiento de incidencias?"

Our old friend in #3048 and others.

**Comment by laarmen** [comment]
Thanks, but I don't think this is related. I didn't even know we had this
angular velocity thing before yesterday.

**Comment by walterar** [comment]
I think the problems of NPC ships stuck is related, somehow, with a check, or reset, than fail sometimes with accelerated time.

**Comment by fluffyfreak** [comment]
Good code works, merge now!

**Pull request merged**
