### PR TITLE
Add Sidebars to the Flight UI

### PR DESCRIPTION
**Pull request by Web-eWorks**
This PR is quite overdue to be opened, but I'm finally getting enough time to try to land it.

Finally implementing a [concept](https://i.imgur.com/bhlWOZl.png) from @nozmajner many years ago, I've added two sidebars to the "world view" and interfaced the existing UI elements (gauges, system overview window, comms log) with them for a consistent display paradigm. I've added a new cargo hold display widget to the sidebars, and the sidebar architecture is designed to make adding additional widgets very easy.

**NOTE: this PR is an open call to design/implement additional useful data display in the new sidebars - I'd like a few more sections of useful information before we ship this update.**

These sidebars also represent a bit of experimentation with theming and smooth animations for the UI, hopefully the first of many such improvements to come.

Here's a bit of a lengthy gameplay video showing how everything works (and also showing off a bug with the deliver cargo missions... I did not in fact jettison any cargo, but I apparently had to pay $2,660 anyways.)

https://user-images.githubusercontent.com/4218491/204464502-a86df6a0-6762-453e-a916-0f4318734449.mp4

This PR also includes a few other improvements to the codebase, the most notable of which I've listed here:
- I've significantly expanded the type information and completion data available to a Lua language server, and added support to our `scan_enums.py` script to auto-generate information about the various Constants tables.
- I've also made general improvements to the pigui ui code in some spots, though for details you'll have to reference the commit messages as I've honestly forgotten a lot of what I've done in this PR in the ~five months since I started working on it.
- @impaktor will rejoice, as I've exposed the most important parts of the ImGui Tables API to lua - now you can data-science to your heart's content! :smile: Operator's manual not (yet) included.

### CODE REVIEW

**Comment by impaktor** [comment]
Cool. 
1. Maybe there shold be the same "click" sound effect when clicking those buttons? Or some new sound? @WKFO 
2. I'll get back to you on more gauges. I just have to do some code archeology, as indicated on IRC.

**Comment by WKFO** [comment]
I don't really think those UI interactions need a click-clacking sound, especially with the smooth animation in place. Maybe something subtle.

**Comment by nozmajner** [comment]
I agree about it being subtle

**Comment by Web-eWorks** [comment]
If anyone is interested, Pioneer seriously needs a larger library of UI interaction sound effects - button clicks and mouseover sounds, confirm / deny sound cues, subtle menu open/close sounds, etc. It's much better to have them available in-tree for UI coders to pick from and use as needed then it is to make said UI coders hunt for appropriately-licensed suitably thematic assets (as usually they just don't use sounds at all, or worse use the existing "OK" sound we have for *everything*).

That rant's not really relevant to this PR though; I'm merging this given the generally positive feedback received so far!

**Comment by impaktor** [comment]
@Web-eWorks If interested, I have a branch (now rebased to master), where I'm pondering how to set parameters for a gauge:
https://github.com/impaktor/pioneer/tree/scout-mission

The gauge has hard coded criteria for when it's to progress towards 100%, and I'd like player to input that into some kind of input field, or that's my current thinking. Perhaps you'd like to have a look at the code.

If I remember correctly, it works like so: player takes mission to scan surface of planet, when entering frame, scanner will progress towards 100% if player is below/at altitude +/- some tolerance.

**Pull request merged**
