### PR TITLE
Fix scout bugs

### LINKED ISSUE #5500: Scanner installation issue.
### Observed behaviour

Skipjack only allows installation of one scanner, either a surface scanner or an orbital scanner.

All other ships tested (pumpkinseed, mola ramsayi, wave) allow multiple scanner installations, including multiple instances of the same scanner type, up to a maximum of 8.

### Expected behaviour

Expected behaviour would be to allow one surface scanner and one orbital scanner to be installed, or perhaps one of each model, 4 in total.

__My pioneer version (and OS):__

20230125
Linux Mint
Screenshot_2023-01-29_09-29-03
Screenshot_2023-01-29_09-34-22

### LINKED ISSUE #5501: Small issue on mission page after completing mapping mission.
### Observed behaviour

Got the mapping missions working by implementing the relevant pull request by Web-eWorks, and recompiling.

Accepted a mapping mission of Mercury in the Torvalds platform bulletin board.

Flew to Mercury and completed the mission.

On the return journey, the mission page has the following text:-

Hi!
I'm with the geographical society, and we need to update our maps of Torvalds Platform ,,,.. Should of course still be Mercury here.

__My pioneer version (and OS):__

Latest code.
Linux Mint.
Screenshot_2023-01-29_11-01-35

### LINKED ISSUE #5502: Minor mapping mission issue - set system target button does not set system target.
### Observed behaviour

Accept and set system target button (mapping mission) does not set system target.

### LINKED ISSUE #5503: Orbital scanning mission issue.
### Observed behaviour

While undertaking an orbital mapping mission, the mission details page describes the type of mission as a "Surface Scan"

### Expected behaviour

Would expect it to say "Orbital Scan"
Screenshot_2023-01-29_15-00-23

### LINKED ISSUE #5504: Discrepency between mssion details page and scan manager
### Observed behaviour

Currently running an orbital scanning mission, the mission details page lists the coverage as "607m", while the scan manager lists the required target coverage as 60.8%

BTW, scanning 60.8% of a planet is a huge undertaking, even running at x100 (>>>) I reckon it will take about an hour real time to complete the mission.

Screenshot_2023-01-29_15-00-23
Screenshot_2023-01-29_15-16-41

### PR DESCRIPTION
**Pull request by impaktor**
- Fixes #5502  scout not setting nav target when accepting mission
- Fixes #5501, mission target and mission return target mixed up
- Fixes #5503, after advert is converted to mission, the mission doesn't know if it's orbital or surface.
- Fixes #5504, for the same reason.
- Closes #5500

### CODE REVIEW

**Comment by impaktor** [comment]
Hold with merging this, there might be more to do on #5501, regarding coordinates and the mission list overview variables. Need to look into how those work

**Comment by impaktor** [comment]
There, last commit should fix #5501, I hope, but completely untested, as I only have the code on a VM, so can't run pioneer.

**Comment by RacerBG** [comment]
I had noticed 2 things while translating the Scout module:

1. The "Radar Mapper" is only mentioned once but the description mentions "_Radar Mapper is a ship equipment_" and I have no idea which equipment is this.
2. "You will need an orbital scanner fitted to your ship. Once you're at the body in question, activate the scanner, and orbit within the maximum altitude until the scan is comple**te**. Then deliver the data to me." - "te" is missing from "comple".

**Comment by impaktor** [comment]
@RacerBG Thaks for reporting. This string isn't used in the module anymore, so I've removed it from the translation resource now. (Until @Web-eWorks fine work with the sensor manager, the mission module would just require the ship to be fitted with a radar mapper, and we pretended it scanned the surface).

I also note there are two place-holder strings "xxx", that I'll fix now, then this should be good to go.

**Comment by RacerBG** [comment]
Also "_MAPPING_" and "_MAP UPDATE_" have duplicates but i don't know if this is intended.

**Comment by impaktor** [comment]
@RacerBG Those are just lack of imagination on my/our part. Sort of intended. You can see "Remove dead strings" in this pull request, what I'm removing.

**Comment by RacerBG** [comment]
@impaktor Sorry to bother you but in Transifex everything is stalled right now. The changes to the strings are not applied and the Transifex bot  is basically dead.

**Comment by zonkmachine** [comment]
@RacerBG This is a known issue and the developers are working hard to fix it.

**Pull request merged**
