### PR TITLE
Adjusted position of the overview window button

### LINKED ISSUE #4408: Overview window button moves slightly outside of the screen when overview window is open
### Observed behaviour

Overview window button moves to the right and partly out of the screen while the overview window is open after I click it, leaving only a few pixels of width that I can click on. Also when I hover my mouse over it when the window is closed, the mouseover text says "Show window" but when the window is open, I hover my mouse over the thin sliver of the button that is still visible and the mouseover text says "Toggle the overview window".

### Expected behaviour

I expect the button to stay in the same place, whether the window is open or closed, and to not be so thin that it's nearly impossible to click. I also want it to have the same mouseover text in either case.

### Steps to reproduce

1. Clone pioneer into your favorite cloning directory, make sure it is the version specified below, if not checkout commit 318867e18.

2. Compile Pioneer, make sure it's the correct version, run Pioneer.

3. Start a new game. Undock/takeoff from whatever base you start at.

4. In the HUD, hover your mouse over the button in the top right corner of the screen. Observe the mouseover text. It should say "Show Window"

5. Click on the button in the top right corner of the screen.

6. Hover your mouse over the thin sliver that's left of the button in the top right corner. Observe the mouseover text. It should say "Toggle the overview window"

__My pioneer version (and OS):__

Ubuntu 18.04 bionic (but a little messed up from installing lubuntu-desktop, then xubuntu-desktop, then doing my best to clean up lubuntu-desktop and ubuntu-desktop but i still see a lubuntu logo during reboot)

pioneer git (318867e18)

### PR DESCRIPTION
**Pull request by robothauler**
Fixes #4408

### CODE REVIEW

**Comment by robothauler** [comment]
Fixes also #4544 by not accessing Game.system

**Comment by impaktor** [comment]
Looks like a trivial code change. Too bad I'm shit at PiGui code. Anyone want to review? ping @Web-eWorks @vakhoir

**Comment by vakhoir** [comment]
Looks good, and is much easier to understand. Works too! I tested it on multiple resolutions.
The #4544 fix works as well.

You might want to squash the commits, but other then that it's good to merge IMO.

**Comment by Web-eWorks** [comment]
@impaktor Looks good to me. We don't have the more advanced ImGui sizing functions exposed to pigui right now (`GetAvailContentWidth` for example), but this looks perfectly fine and serviceable.

**Comment by impaktor** [comment]
> You might want to squash the commits,

First I thought the same, because my brain's beein all over the PRs asking for it, but they're actually consistent, i.e. no "this is random stuff I did first", "this is random stuff I did next coding session", nor is it "do A" and "fix error in A", so I'll merge as they stand.

**Pull request merged**
