### PR TITLE
Improve the clang-format hook and autoformat tool.

### PR DESCRIPTION
**Pull request by Web-eWorks**
This PR improves the clang-format hook (and the autoformat tool) to only consider staged files and to safely deal with files clang-format throws an error on, including misidentified files and deleted files.

### CODE REVIEW

**Comment by impaktor** [comment]
Neat, our first [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

**Comment by impaktor** [comment]
Btw, I see this commit was also in one of your other PRs, #4523

**Comment by Web-eWorks** [comment]
@impaktor I kinda _maybe_ forgot that the `tooling` branch still had a PR open against it. Was trying to recycle that branch for this PR.

I think I'm gonna setup the `bootstrap` tool to copy the git hook as well, now that I think of it.

**Comment by Web-eWorks** [comment]
...I keep forgetting clang-format PRs are not on the tooling branch.

**Comment by Web-eWorks** [comment]
@impaktor ready for merge now.

**Comment by impaktor** [comment]
Is there an error on line 44 or what does Travis complain about?

**Pull request merged**
