### PR TITLE
New UI System Info

### PR DESCRIPTION
**Pull request by johnbartholomew**
Very much work-in-progress.

To do:

- [x] Make text translatable
- [ ] Transfer existing translations from 'core' to 'ui-core'
- [ ] Trade info tab, visible only if you have a trade computer, showing imports and exports
- [x] Correctly handle 'unexplored' systems (hide all info)
- [x] Actually fill in the quick info 'Stable system with ...' text.
- [ ] Correctly handle systems containing multiple gravpoints.
- [x] Only use the 'hyperspace target' icon for stars (currently in e.g., Sirius, it gets applied to some planets as well)
- [ ] Auto-select the first body when you first switch to the Body Info tab.
- [ ] Hook up hyperspace target selection action to control the Player's current hyperspace target.
- [x] Make the body icons clickable -- when clicked, that body should be selected and the Body Info tab should show information about it.
- [x] Don't show the 'Notes' heading if the system doesn't have any long description.
- [x] Indicate the selected body somehow. Will probably need to create a new widget type to use to achieve this.
- [ ] Clean up commit history
- [ ] Run luacheck

### CODE REVIEW

**Comment by johnbartholomew** [comment]
Current status:
screenshot-20151212-203719

**Comment by fluffyfreak** [comment]
Wow you're really tackling a tangled one this time! Good work!

**Comment by impaktor** [comment]
Simply amazing. I just had to try it out, even in it's WIP state.

Currently both stars (A,B) are marked as hypertarget with the `[ ]` (bug/WIP), and another body for body info. I'm not sure it's very obvious at the moment that you can select stars as hyper target by clicking the text. A check-box (radiobutton?) shows that the're is a function here. Not sure how good it would look though.

screenshot-20151214-131833

Anyway. Fantastic progress to see.

**Comment by nozmajner** [comment]
Looks great!

**Comment by impaktor** [comment]
This issue should close #2985, and #1052, in the latter Andy says:

> We could really do with pulling all of these screens out of the "old-UI" and making a "new-UI" based version of them too. Lots of crappy old code could then go away quite rapidly!

Almost there. And annother [penny for me!](http://spacesimcentral.com/ssc/topic/5282-announcement-big-update-adventurous-test-pilots-needed/page-3#entry56285):

> Oh, if I had a penny every time during development discussions the phrase "yes, but this should be done in the new UI system" has been spoken... I would have many pennies.

Also, I wonder how this PR will handle the super-giants, like the one shown in #3455. With new random number generator, those reported are no longer there, but we have a lot of fixed `SUPER_GIANT`s in 03_bright_stars.lua.

No, wait, let's find out!
screenshot-20151216-100813

**Comment by impaktor** [comment]
First: sorry for spamming this WIP branch, but it's fun to see it, and I might as well share som thoughts, maybe some of them have relevance.

Question: I don't know if you plan on adding the econ/trade stuff in the PR or, if that is for another day and another PR. If the former, then question is how the trade computer will indicate good trades? Green and red text on blue background is pretty evil for colourblind. It could stay with colours, or use some little icons. A question perfect for our colourblind icon-maker, @nozmajner?

OK, I just had to play with this some more, hoping I'm testing / showing super and hyper giant systems. In these cases, they're so big you have to scroll to get past the star, which is pretty neat.

screenshot-20151216-141053

screenshot-20151216-141104


We have no __HYPER__ giants in bright_stars, so I edited it in. Looks a bit weird, as the edge is shown:

screenshot-20151216-141420

screenshot-20151216-141428

**Comment by nozmajner** [comment]
I think an icon or an icon + text color approach for the trade analyzer would be the best from usability perspective. I'll come up with some icons.

**Comment by corundscale** [comment]
Is there any point blocking selection of planets a hyperspace targets? The way jumping is supposed to work seems to be undecided as of now with proposed in-system jumps, so it may end up as do-undo kind of work.

I'd argue for allowing all bodies to be set as jump targets, at least provisionally.

**Comment by johnbartholomew** [comment]
I'm aware that there has been some discussion of in-system jumps, but I don't know what the current status of that is. As you say yourself, it seems to be undecided. I don't want this initial conversion to new-ui to get stuck by tying it to other work (either design work or coding) needed to implement in-system jumps.

Doing work that is changed or replaced later (even very soon afterwards) is entirely normal and doesn't worry me. The aim in this PR is just to convert the System Info View to new-ui, with the same level of functionality that the old-ui version had, which seems like a nice achievable goal. I had hoped to have this PR ready to test and merge by the end of my Christmas break, but I haven't quite succeeded. Still, I hope it won't take too much more effort to get there.

**Comment by corundscale** [comment]
Maybe allow some flexible solution where ability to select a body as jump target is determined on per body type basis?

**Comment by impaktor** [comment]
@corundscale / DraQ I was silent after your first post, but I feel the need to speak my mind clearly now: _We_ have decided on the basics of how jumps will work, we were all in agreement in the [thread](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=379) you started, only the details remain to be worked out, and they look nothing what you're trying to do here.

By __we__ I mean everyone taking part in that thread who _also_ regularly contribute to pioneer. This excludes you, as you are a mostly a player who pops by from time to time to make very long posts where you tell us what we should do for you, and drop general hindsight / besserwisser comments of the kind "why didn't you just implement it without the bugs?" (ref: #3005), which tend to make myself and others quite annoyed.

I do not appreciate your attempt to trick(?) @johnbartholomew, who didn't follow that discussion, into implementing this for you, thereby circumventing what the rest of the devs. decided, and the work @fluffyfreak has already started.

Jumping directly to planets will not happen, for all the reasons stated in the dev. forum discussion thread, so I ask to to kindly just drop it. This is not the place for this discussion.

**Comment by fluffyfreak** [comment]
Whatever happens to the in-system stuff it doesn't affect this PR.

**Comment by corundscale** [comment]
@impaktor 
Ok, at this point I'm seriously fed up.
Whenever I post anything, it gets interpreted in the worst manner possible, usually as malicious intent on my part. 
Whenever there is any sort of controversy that would call for some further discussion, it gets quickly and quietly resolved in favor of whomever has the most weight to throw around, seemingly without even cursory examination of the arguments against it,  and certainly without as much as honoring them with any sort of response, no matter how objective or well construed they might be (like L4/5 of a distant planet being just as distant from both the planet and its sun, so not really helpful for in-system travel - the discussion you mentioned ended with an unaddressed post of mine directed at, among others, you). 

Why do you expect anyone who isn't already a regular contributor to want to contribute code to the project if they are refused the opportunity to take even the most minor part in shaping its vision?
As in "having their feedback actually considered and responded to in a constructive manner".

Sure, people with most contributions should have the last word, but what's the point of having an open source project if anything coming from outside is automatically dismissed without as much as a word?

Also, no one wants to jump directly to planets - for obvious reasons - but I don't see any reasons against treating all the bodies like stars as far as hyperspace targeting and jumping is concerned and I'm pretty certain no such reasons were stated in the discussion thread. 
Feel free to provide any evidence to the contrary. 

As for #3005, could you please not misconstrue my position on it?

**Comment by impaktor** [comment]
I've answered in the [thread](http://pioneerspacesim.net/forum/viewtopic.php?p=4499#p4499), so we can stay on topic here.

**Comment by johnbartholomew** [comment]
I never found time to finish this.

**Pull request closed without merging**
