### PR TITLE
Cancel a missile order when the ship has jumped

### PR DESCRIPTION
**Pull request by laarmen**
Or crashed, for that matter. Anyway, AIKamikaze will not try and fail to go after invalid bodies anymore.

Ping @fluffyfreak , because i'm guessing the methods I've introduced might be useful elsewhere but I don't know much about this area of the code.

### CODE REVIEW

**Comment by laarmen** [comment]
Also, ping @walterar.

**Comment by walterar** [comment]
Testing.

**Comment by walterar** [comment]
This works. thanks @laarmen :+1:

**Comment by laarmen** [comment]
DO NOT MERGE!

While it fixes the problem, it shouldn't have to in the first place. For some reason onDelete doesn't do its job, investigating now.

**Comment by laarmen** [comment]
Oh wow, turns out it was broken ever since #1663 !

**Comment by laarmen** [comment]
OK, a better fix for that.

**Comment by walterar** [comment]
tested, OK :+1:  :)

**Comment by laarmen** [comment]
Cool, thanks!

**Pull request merged**
