### PR TITLE
WIP: move systemview UI to pigui

### PR DESCRIPTION
**Pull request by ecraven**
Not done yet, still working on it.

### CODE REVIEW

**Comment by impaktor** [comment]
I thought I'd try this, but I get merge conflict, and I'm too lazy to fix it.

**Comment by impaktor** [comment]
Looks nice. I reacted on that the zoom in / zoom out icons are the reverse of what I'm used to, but it's the same in the sector view, so I guess it's consistent.

**Comment by fluffyfreak** [comment]
It looks good, obviously it's WIP but I think it's better already.
Since you're in the area already could you add another state to the `enum ShipDrawing` to that it can be off entirely? The current `OFF` state just means not to draw a box or the orbit but an off-means-off would be good.

Other than that this is just a straight UI porting yes? Or do you want to do more with the screen too?

**Comment by impaktor** [comment]
@ecraven is this abandoned? If I understood you correctly, you currently don't have much time for pioneer. Possibly, someone else (not me) can play around with this, (it's been open for 1.5 years now, and we do want the end-product of this in master).

**Comment by Web-eWorks** [comment]
I've been trying to work with this; I'm probably going to go about it an entirely different way, so :+1: on closing.

**Comment by Gliese852** [comment]
If anyone needs any help on this topic, I'm interested.

**Comment by impaktor** [comment]
@Gliese852 I think it's safe to say this PR is abandoned, so if you want to work on this, then please do!

**Comment by Web-eWorks** [comment]
Closing this as inactive; @ecraven if you decide to come back to this, feel free to re-open!

**Comment by Web-eWorks** [comment]
@Gliese852 sorry I missed your message on IRC, it's been a busy day.

I've been discussing with @nozmajner about the goals we want from the system map. We've come up with some fancy plans, but at the most basic, I want to move all of the UI drawing to pigui, allow the system map to be "popped out" into its own window and drawn over the World View, redesign the "route planner" so that it's much easier to understand what the options do, and draw the background stars (very faintly) in the System Map view to give it a sense of scale.

I personally also want to improve the orbit lines display to add antialiasing and not cull them until you're zoomed in much farther on a body, add icons for ships, stations, etc. in the system map view, texture the bodies with a simplified version of their "actual" colors, add multi-step route planning, etc. but those are more grandiose plans.

I haven't had the time, but one part of my "different approach" is that I want to change the way we call into pigui code; at the moment we have hard-coded "handlers" that we statically call - I want to make that a bit more generic and let screens register their own binding points for pigui UI modules to hook into.

**Comment by Gliese852** [comment]
@Web-eWorks Maybe as a first step, I will try to bring what has already been done by @ecraven to a workable form? I have studied the code and find it a good starting point.

If interested, I rebased this branch to the current master https://github.com/Gliese852/pioneer/pull/3

And where is it better to ask questions? Here, or create a issue, or new PR, or maybe a forum or IRC?

**Comment by impaktor** [comment]
> Maybe as a first step, I will try to bring what has already been done by @ecraven to a workable form? 

Very big :+1: 

In pioneer-land, we all have huge plans and ambitions, but it takes years, the best way is indeed as you say, get started and see how far you get. If you have something half-working you can open a WIP/Draft pullrequest, and discuss code there. 

You'll best find me, ecraven, nozmajner and Web-eWorks (as sturnclaw) on IRC, but he just went to bed, being geographically imparied.

**Pull request closed without merging**
