### PR TITLE
Avoid CTD when trade ship try to decide hyperjump

### PR DESCRIPTION
**Pull request by mike-f1**
Solve #3913

...Seems LUA would know a distance to a "nil" object, but I don't
know: you need to ask @walterar , he did the work ;)

### CODE REVIEW

**Comment by impaktor** [comment]
Do we/you know why a trade ship ends up with no startport when trying to jump? And what happens with it if it doesn't have a starport set?  It will just linger in the system? Clog up stations? Just for curiosity, I wonder if we understand why this happens?

**Comment by mike-f1** [comment]
@impaktor: err... just see the screenshot on #3913, there are line number and a little explanation...

Regarding what TradeShips are doing all time... yes: this is a good question :)

**Comment by mike-f1** [comment]
@impaktor: err... just see the screenshot on #3913, there are line number and a little explanation...

Regarding what TradeShips are doing all time... yes: this is a good question :)

**Comment by fluffyfreak** [comment]
I'd prefer to merge this and then investigate the consequences afterwards as currently there's a crash bug ingame

**Pull request merged**
