### PR TITLE
Pigui Model Spinner, move ShipInfo to pigui.

### PR DESCRIPTION
**Pull request by Web-eWorks**
It's what it says on the tin. @fluffyfreak should probably review the rendering code and make sure I'm not doing something stupid, but otherwise this one's ready to go.

I've done something a little _special_ with the infoview - I've written it so that it's ready to be used in the new sidebar layout I've been hashing out with @nozmajner; all you've gotta do is turn `_OLD_LAYOUT` off and call it from a parent which handles the sizing. I'm going to further extend this with a few custom widgets to achieve the look of the prototypes, but that's for another PR.

@vakhoir on the first window opening, the tab-view wants to show the newUI tab underneath the pigui tab - I'm leaving you to figure out what's going wrong with that code.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
I'll have to check it out at home but it looks good so far!

**Comment by vakhoir** [comment]
> @vakhoir on the first window opening, the tab-view wants to show the newUI tab underneath the pigui tab - I'm leaving you to figure out what's going wrong with that code.

Yup, will do! I'm a but busier than usual,  recently and I might be even less available by the mid/end of the month, but I should be able to take care of this.

**Comment by vakhoir** [comment]
Found the issue: https://github.com/vakhoir/pioneer/commit/22723c8c15a17d6748c6d4b8f55f96bded9a91df

Is there a problem with calling hide/enable in every frame? Somehow it rubs me the wrong way. On the other hand, once we finish the tab views the legacy handling will be removed.

**Comment by Web-eWorks** [comment]
@vakhoir just open a new PR to fix it - being in `tab-view.lua`, it shouldn't conflict with this PR.

**Comment by impaktor** [comment]
@vakhoir's PR above should close this.

**Comment by fluffyfreak** [comment]
What? No this is for the Model Spinner, the #4620 just fixes a minor formatting issue

**Comment by impaktor** [comment]
@fluffyfreak thanks. sorry. Just read the description of @vakhoir. Seeing now this is a PR... 
Oopsie?

**Comment by vakhoir** [comment]
It should be fine. Worst case scenario I didn't fully fix it and we'll need another PR, but it worked well as far as I tested it.

Maybe someone can just doublecheck.

**Comment by fluffyfreak** [comment]
Unfortunately I can't run on Windows anymore due to #4618 so I'm holding off on merging PR's.

Someone else is free to test and merge if it all works.

**Comment by impaktor** [comment]
Only tested function, and glanced over the code. 

Very nice to have this in the game now!

**Pull request merged**
