### PR TITLE
Fixes, bowfin update, terrain rendering fixes

### LINKED ISSUE #5420: User made flight log does not save on closing the game
### Observed behaviour
Writing an entry into the logbook thing under personal info is not preserved when the game exits and does not show up when the game is reloaded

### Expected behaviour
Log is preserved on exit and viewable when reloading the save in a new session

### Steps to reproduce
Open game, start a save, write a diary/logbook entry, save game, close game, reload game

__My pioneer version (and OS):__
Version: February 2022-02-03
OS: Windows 10 64 bit

### LINKED ISSUE #5458: Wrong wheel up/down icon when in auto-pilot
### Observed behavior
Clicking wheel down when in auto-pilot plays the sound, but icon flickers, then back to what it was.

### Expected behavior
Either:
- clicking wheel button in auto-pilot does nothing, no sound, just "dead", since ship is under AI-control
- if wheels are down, then show correct icon

__version__ I expect this to be reproducible on master 2022-12.

### LINKED ISSUE #5470: Autosave clears bulletin board (for permanent?)
### Observed behaviour / Steps to reproduce

Land on a Star-/Spaceport when autosave is on
End the game
Load the game autosaved when you landed
Check the bulletin board - it's empty!

Even when you return to the port some time in the game later, there are no new entries.

__My pioneer version (and OS):__
actual master on SuSE Linux 15.4

### PR DESCRIPTION
**Pull request by Web-eWorks**
Unsure how much more bugfixing will be finished before Pioneer Day, so have an early batch. I'll try to get to the other reported issues with the Scout Mission etc.

- Fixes #5420: the global version attribute was being reset on game end, causing invalid data to be saved. The entire flight history log was discarded on load.
- Fixes #5458: added a separate button state for "autopilot control". Not using a separate language string due to time reasons.
- Fixes: #5479: this was caused by order of autosave handler relative to other `onShipDocked` handlers. I've deferred autosave by one frame to ensure all handlers run before saving.
- Fixes: #4123: autosave is now made before undocking, rather than after.
- Fixes #5470: this was caused by the autosave running before BBS / markets are generated for the station. Thus, reloading the autosave yields an empty market.
- Fixes: #5493: reloading the game or buying a new ship didn't update the equipment listener used to detect changes to the ship's loadout.

I've updated the Bowfin to have an additional 50% more equipment capacity as an interim measure before moving to volume-based equipment. This allows it to mount missiles in addition to a shield generator... :upside_down_face: The Bowfin's class has been updated to "Light Fighter" from "Medium Fighter" (as it in no way qualifies for a medium ship).

I've also fixed an unreported bug that caused extremely poor quality terrain in elevated areas. The centroid used to calculate LOD distance to a geopatch was remaining at the "sea level" height of the planet, rather than at the average height of the terrain, causing the game to think the camera was much further from the terrain than it actually is. This makes a *huge* difference in visual terrain quality, but leaves the performance cost about the same as before when the player is in low-lying terrain.

Before:
image

After:
image

### CODE REVIEW

**Comment by Bodasey** [comment]
Maybe you can also easily fix #4123 this way?

**Comment by Web-eWorks** [comment]
That in fact should already be fixed - autosave on takeoff is made before the ship is actually undocked (so if you forget something, you can quickload and buy/sell your commodities).

**Comment by Bodasey** [comment]
#4123 fix confirmed

#5470 fix confirmed

#5479 very probably fixed

**Comment by Bodasey** [comment]
While flying from Earth to Jupiter:

Warning: Caught error in Lua UI code:
        [T] pigui/modules/info-view/03-econ-trade.lua:71: Cannot call tableSetupColumn() outside of a beginTable() / endTable() pair

Hang with a long LUA error report, said it was written to output.txt, but there's nothing of this.

**Comment by Web-eWorks** [comment]
> Hang with a long LUA error report, said it was written to output.txt, but there's nothing of this.

Without the output.txt I cannot address this issue. If it occurs again, please get the error info from `output.txt` and make a new issue with it (as this is unrelated to this PR).

**Pull request merged**
