### PR TITLE
Crash bug fixes

### LINKED ISSUE #3387: Can't load saved games in Arch-based distros
When i try to load a game in pioneer the game crashes immediately, i asked people @ the IRC they told me to post this on the issue tracker (( Note: this issue is only for Arch-based distros ))

### PR DESCRIPTION
**Pull request by johnbartholomew**
For #3387 and #3399. I'm not sure if this fully fixes #3387, but it fixes a stack corruption (incorrect scanf format specifier) and memory access violation.

### CODE REVIEW

**Comment by johnbartholomew** [comment]
Apparently Travis didn't like this. I'm not sure why... inttypes.h isn't *that* new. When the next travis build fails I'll try to examine the output more carefully.

**Comment by johnbartholomew** [comment]
I suspect it's because __STDC_FORMAT_MACROS wasn't defined, and I was including <inttypes.h>. I'll try including <cinttypes> instead (which I think technically is not supposed to need __STDC_FORMAT_MACROS).

**Comment by johnbartholomew** [comment]
And now trying it with __STDC_FORMAT_MACROS defined... let's see how this goes.

**Comment by impaktor** [comment]
I'll keep my fingers crossed. (actually, I'll be holding my thumbs, since that's how we do it over here), either way, I suggest poking the build master (within 5 hours) once this is merged.

**Comment by fluffyfreak** [comment]
Awesome work @johnbartholomew :)
I was just glumly sitting down to try and figure all this out today.

**Pull request merged**
