### PR TITLE
Systeminfoview target box

### PR DESCRIPTION
**Pull request by joonicks**
Only show target box for
a) current system targets
b) remote hyperspace targets if more than one

Does not show anymore target around a remote systems single star.

### CODE REVIEW

**Comment by joonicks** [comment]
dont merge it yet, there might be a problem with it

**Comment by fluffyfreak** [comment]
Don't worry, it'll get a review first :)

**Comment by joonicks** [comment]
found the bug. now to figure out how to submit it without driving impaktor mad.

**Comment by impaktor** [comment]
Don't worry, I'm glad to help anyone, and believe me, git is not something you learn in a day, so it's perfectly natural to be in a confused state at first.

First to understand what went wrong: when you create a branch B from branch A (in your case master), the new branch B will be identical to A. When you created B (your feature branch), master had already been "contaminated" with three commits on it. Thus they followed into B.

So first we need to fix your master. Assuming you've defined an "upstream" repo, as described on the [wiki](http://pioneerwiki.com/wiki/Using_git_and_GitHub), if not do:

    git remote add upstream git://github.com/pioneerspacesim/pioneer.git

you can reset your master branch. First switch to your master:

    git checkout master

now reset it to upstream, this will reverse the master branch to the latest commit on pioneerspacesim's master:

    git reset --hard upstream/master

Now you can _create_ and _switch_ to the new branch from master with one command:

    git checkout -b money_format_fix

And git sitll knows about your removed commits (for another 30 days I think, by default), so you can cherry-pick them back. On this new branch you want to commit your "money format"-commit, which git still remembers so just reference it by its hash, by doing:

    git cherry-pick a1c5f30afd5da44e9ff39921d208184850580272 

and then push that branch to your github account. __Done__. 

Now I'd do the same on your feature branch to which this pull request is connected, but for some reason, that I do not understand, github (top of this page) now says it's an "unknown repository". But _if_ this branch was called B, I'd do:

    git checkout B
    git reset --hard upstream/master
    git cherry-pick  8b7bb65

And since you've changed the _history_ of your branch B (by removing the unwanted commits with a `reset`), github will be confused since the history of branch B on your harddrive will be different from the history of branch B on your github account, so you need to do a forced push to github, to really jam the changes down github's throat:

    git push -f

done.

**Comment by fluffyfreak** [comment]
@joonicks this PR needs updating so we can review and merge it.

**Comment by impaktor** [comment]
For those who don't know what is being discussed, it's about if we should show the green box for single star systems:
screenshot-20151007-130404

I'd like to point out that even though the green box on the selected star is ugly, not showing it at all for single star systems makes it less clear that one _can_ select stars from this screen as well, which is a common FAQ we get (how to not have to travel 100 AU to station).

For interface changes I'd like to ping @nozmajner for opinion.

**Comment by fluffyfreak** [comment]
Closing as it's been replaced by #3483.

**Pull request closed without merging**
