### PR TITLE
Close #2665: Orthographic view in modelviewer

### LINKED ISSUE #2665: Feature request: Model viewer orthographic view
It's difficult to check alignment of the collision mesh, AABB and shield with only a perspective view. Orthographic projections (top/side/front) would be useful.

### PR DESCRIPTION
**Pull request by mike-f1**
Pressing "o" key lead to orthographic view

### CODE REVIEW

**Comment by impaktor** [comment]
Is this new feature to be documented somewhere?

**Comment by mike-f1** [comment]
...err, don't know... At least in https://pioneerwiki.com/wiki/Model_viewer

**Comment by fluffyfreak** [comment]
It looks odd but it works fine for me.

**Comment by mike-f1** [comment]
@fluffyfreak : it looks odd but if you display collision then it is easy to check alignements...

There's also a problem with zoom (it start "quite" near) but it could be guessed.

**Comment by mike-f1** [comment]
..ehm: this need at least a link to this #2665

**Comment by mike-f1** [comment]
stupito
...an FTL merge...

**Comment by fluffyfreak** [comment]
@mike-f1 yep I checked, it works, it's merged :) first merge of the month!

**Pull request merged**
