### PR TITLE
Fix the floating point crash

### PR DESCRIPTION
**Pull request by Damjan94**
deals with the issue #5200

I say "deals" because I have no idea why the value was that large in the first place...

### CODE REVIEW

**Comment by Damjan94** [comment]
screenshots of the sips that were causing the crash
image

image

image


Doesn't seem to have any relevance though....

**Comment by Web-eWorks** [comment]
It's an issue with calculating terrain height, but I find it interesting that it causes an fpexcept crash on your computer; I personally have never had that happen. What hardware are you running, by chance?

Ideally the fix is to adjust terrain generation to avoid ridiculous values like that, but I suppose the long->int truncation is an acceptable patch for right now.

**Comment by Damjan94** [comment]
I use amd fx 8350
are you not getting a crash when fast forwarding the save file(before this "cast to long" patch)? I got it roughly 80% of the time...

**Comment by Web-eWorks** [comment]
> I use amd fx 8350
> are you not getting a crash when fast forwarding the save file(before this "cast to long" patch)? I got it roughly 80% of the time...

No! I've actually never gotten a crash from that, no matter how I build the repo, although I'm on an Intel i5 4690k. Nor have I seen this reported before, which makes me think it's something to do with your specific processor generation.

However, I'm happy to pull this in as it shouldn't cause any major differences in behavior on other unaffected platforms.

**Pull request merged**
