### PR TITLE
Search&Rescue module: stop searching for destroyed ships

### PR DESCRIPTION
**Pull request by clausimu**
This addresses #3801 partly. The segfault still happens and is still under investigation, but the added check for target ship presence, as @walterar correctly suggested, is necessary here. Otherwise the player ship would continuously search for a possibly already destroyed ship.

### CODE REVIEW

**Comment by clausimu** [comment]
Just tested again with #3796 correctly merged - this fixes #3801 now.

**Comment by walterar** [comment]
```
- if leaving_system == true or Game.player.frameBody ~= mission.target.frameBody or not mission.target then
+ if leaving_system == true or not mission.target or Game.player.frameBody  ~= mission.target.frameBody then
```

**Comment by clausimu** [comment]
@walterar - being picky about how concise my coding is? :)
Fine with me...

**Comment by walterar** [comment]
:+1:  ;)

**Comment by impaktor** [comment]
OK, I'll merge this shortly, but will cherry pick and rebase, so this PR will show up as "closed" rather than "merged".

**Pull request closed without merging**
