### PR TITLE
boot screen visuals

### PR DESCRIPTION
**Pull request by joonicks**
center-aligned the and shrank it to not cover the whole width of the
screen

### CODE REVIEW

**Comment by joonicks** [comment]
bootscreen

**Comment by fluffyfreak** [comment]
Ok this looks good, I haven't had a chance to check the code yet but does any else like our resident artist @nozmajner have any comment about the placement / size?

**Comment by impaktor** [comment]
Comments from noz and others in IRC have been positive. I think it serves as a good first commit, to get into the development process.

I thought you would like to look the code over. That `(xsize > 700)` threw me off a bit, I'd have expected it to, say, always have the bar be "2/3" of the width or something. Haven't looked at it in any more detail.

**Comment by impaktor** [comment]
Here's just a quick idea (mockup) of how to spice up the boot screen further, using our `data/galaxy_colour.bmp`

boot_suggestion

(Yes, I'm posting in this pull request, since this is where we had the main discussion, and both #3462 and this tracks your master-branch, so they're identical in all aspects).

**Pull request closed without merging**
