### PR TITLE
Add MSVC build to github-actions CI builds

### PR DESCRIPTION
**Pull request by The-EG**
I think I have the appveyor build working well now, but having all of the builds in one place would be nice, and probably simplify getting the releases automated again too.

This is a first shot at adding MSVC to the github actions builds for PRs.

### CODE REVIEW

**Comment by The-EG** [comment]
10 pushes later.....

This appears to be working. I had to remove some languages from the installer because they aren't officially supported by Inno Setup at version 6. For appveyor I was downloading the older files for those languages, but I think now that it may be better to drop them. We can always add them back if/when the language files are updated for 6.0.

**Comment by The-EG** [comment]
In addition to the build, the installer is published to the 'Windows-Artifacts' artifact on *all* successful builds with this change.

**Comment by Web-eWorks** [comment]
@The-EG you'll need to change a CPP file to trigger the Github action - once we confirm it's working, I'll be good to merge this!

**Comment by The-EG** [comment]
> @The-EG you'll need to change a CPP file to trigger the Github action - once we confirm it's working, I'll be good to merge this!

I did, that's what the example build I linked was. But I'll trigger it again so it shows up.

**Pull request merged**
