### PR TITLE
Implement a consistent (and purple!) UI theme

### PR DESCRIPTION
**Pull request by Web-eWorks**
After much frustration with the inconsistent colors of our existing theme (and the go-ahead from our resident UI designer @bszlrd), I've unified the theme colors used in the game's interface to a consistent UI style.

There are two major changes made by this PR:
1. We now have a single primary "action color" used for most interactable elements in the UI, split up into various luminance-based breakpoints to ensure that UI elements are accessible even to colorblind users. The "accent" color is now used very sparingly where needed to highlight important text elements, alongside other semantic colors like success/warning/danger.
2. Almost all window backgrounds are now a dark gray with subtle hints of purple. This provides a much more consistent feel to the UI than the prior bright purple/blue backgrounds did, allows us to use the blue accent color with less worry about colorblind users, and provides better text contrast - allowing us to reduce the sometimes absurdly large font sizes while still maintaining legibility.

Here's a quick clickthrough of the UI with the new theme:

https://github.com/user-attachments/assets/08138bd8-9adb-4d0a-bb58-0a8338c67e3b

(Music: Stellardrone - [To The Great Beyond](https://stellardrone.bandcamp.com/track/to-the-great-beyond))

There are still a few TODOs before this should be merged:
- [x] Better differentiate available and unavailable BBS ads (e.g. highlight/selection color)
- [x] Fix hardcoded colors in the C++ radial menu widget
- [x] Improve the color used in checkmarks to be less washed-out
- [x] Rewrite icon button widget to not render an overlay on top

### CODE REVIEW

**Comment by impaktor** [comment]
> Better differentiate available and unavailable BBS ads (e.g. highlight/selection color)

Out of scope / off topic, but this makes me think of how this was introduced in #2675. There was basically a disagreement in how it should work. 
- Should an advert be grayed out only after player had clicked it and been refused? 
- Or should all be grayed out right away, as if player had interacted with the advert all ready and knew the answer
- Or grayed out could just mean "clicked: yes/no", like URLs on this interweb I keep hearing about.

I'm more biased to the first option, but second option (current master) is no doubt easier for the player.

**Comment by impaktor** [comment]
@bszlrd video could go on youtube. (I wonder if we should distinguish between videos of unmerged stuff "IN DEVELOPMENT: <title> ", and actual merged stuff that can just have normal title?)

**Comment by bszlrd** [comment]
Looking good!

**Comment by Web-eWorks** [comment]
This branch is now ready for testing - I've done a pass on all icon buttons (and changed their size in some cases) as well as incorporated the latest icons.svg updates from @bszlrd. I'd appreciate a fairly close look at the entirety of the UI to catch edge cases / broken behaviors (i.e. buttons not working, broken text, scrollbars that weren't there before).

**Comment by Web-eWorks** [comment]
I have one final TODO item to address, and then I'd like to start looking at merging this PR. Anyone willing to click around the UI and look out for bugs would be much appreciated.

**Comment by impaktor** [comment]
I gave this a spin, below are just the thoughts that popped into my mind when I clicked through it. 

- I did get a crash when clicking on F3->equipment tab, (when starting a new game), but have not been able to reproduce now

- Font size of Language table (when accessed in game ESC -> Languages) is very large compared to other tabs
2024-08-17-082314_857x566_scrot_

- Blue box in upper left for name & rank intentional? Thought I could click it / interact with it.
2024-08-17-080609_981x664_scrot_

- Magnification in ship spinner changed for ship market? good/bad?
2024-08-17-081558_1264x624_scrot_

- This is probably a critique against myself, as I'm the one who did this screen for NewUI->Pigui, but it's a bit unclear what that 8t belongs to, if it's for the bar to the left, or if it's in a table on it's own, independent of the left hand side. Perhaps a vertical line separating the two panes?  Just a thought.
2024-08-17-081246_1273x620_scrot_

**Comment by impaktor** [comment]
> Font size of Language table (when accessed in game ESC -> Languages) is very large compared to other tabs

Come to think of it, the "Language (restart game to apply)" line has always looked like it's part of the table list. Perhaps this should be blue, if possible?

**Comment by Web-eWorks** [comment]
> Font size of Language table (when accessed in game ESC -> Languages) is very large compared to other tabs

Existing issue. That screen needs to be re-worked though and should be quick to do.

> Blue box in upper left for name & rank intentional? Thought I could click it / interact with it.

Yes, the box indicates this is the selected crew member - the menu supports multiple crew members in a starting preset. It's already interactable, just doesn't render a hover effect.

> Magnification in ship spinner changed for ship market? good/bad?

Default magnification is exactly the same. You've scrolled in on the ship spinner and zoomed in on the ship. Existing issue.

> This is probably a critique against myself, as I'm the one who did this screen for NewUI->Pigui, but it's a bit unclear what that 8t belongs to, if it's for the bar to the left, or if it's in a table on it's own, independent of the left hand side. Perhaps a vertical line separating the two panes?  Just a thought.

Also an existing issue! :smile:

I'll try to address problems 1 and 4 if I can. The other two are non-issues or out-of-scope as far as I see it.

> Come to think of it, the "Language (restart game to apply)" line has always looked like it's part of the table list. Perhaps this should be blue, if possible?

Will try to address this as well.

**Comment by Web-eWorks** [comment]
All TODOs and review feedback addressed. Going to merge this PR as I'm satisfied it's had an appropriate amount of testing and is quite large already. Ignoring the SVG changes, this PR is +840 insertions, -470 deletions.

**Comment by impaktor** [comment]
Post-merge thought: there's no difference in blue tone between selected tab and other/not-selected. I wonder if it might be of value to crank up the highlight of the selected tab? Or we only want it highlighted when mouse-over?
2024-08-23-100022_448x186_scrot

**Pull request merged**
