### PR TITLE
Correct minor formatting/indentation

### PR DESCRIPTION
**Pull request by starling13**
I'v found some unnecessary includes and formatting issues

### CODE REVIEW

**Comment by impaktor** [comment]
I don't know what the policy is regarding third party libraries (picoDDS, Json). We usually don't edit them. Or does your compiler throw warnings on those lines?

(Generally, there's no lack of strange / wrong indentation in the c++ source.)

**Comment by starling13** [comment]
At least semicolons after namespace declaration raise warnings.

**Comment by starling13** [comment]
If the development policy prevents editing contributed code parts, may be I should close this request?

**Comment by laarmen** [comment]
contrib is poorly named, and it's where embedded third-party libs live. We
try to touch them as rarely as possible to keep the diff at a minimum,
makes any potential update far easier.

However, anything in src can use a bit of cleanup ;-)

**Comment by starling13** [comment]
Understand, thank you for reply.

**Comment by fluffyfreak** [comment]
I accept PR's to PicoDDS 😁 
https://github.com/fluffyfreak/picodds

I think this can be merged tbh

**Comment by fluffyfreak** [comment]
Couple of minor changes required, merging.

**Pull request merged**
