### PR TITLE
Handle the case when size_t and unsigned int are the same type

### LINKED ISSUE #5527: 2023-02-03 does not build on FreeBSD/i386 due to incorrect overload
```
/work/usr/ports/games/pioneer/work/pioneer-20230203/src/lua/LuaPushPull.h:18:13: error: redefinition of 'pi_lua_generic_push'
inline void pi_lua_generic_push(lua_State *l, size_t value) { lua_pushinteger(l, value); }
            ^
/work/usr/ports/games/pioneer/work/pioneer-20230203/src/lua/LuaPushPull.h:17:13: note: previous definition is here
inline void pi_lua_generic_push(lua_State *l, unsigned int value) { lua_pushinteger(l, value); }
            ^
/work/usr/ports/games/pioneer/work/pioneer-20230203/src/lua/LuaPushPull.h:35:13: error: redefinition of 'pi_lua_generic_pull'
inline void pi_lua_generic_pull(lua_State *l, int index, size_t &out) { out = luaL_checkunsigned(l, index); }
            ^
/work/usr/ports/games/pioneer/work/pioneer-20230203/src/lua/LuaPushPull.h:34:13: note: previous definition is here
inline void pi_lua_generic_pull(lua_State *l, int index, unsigned int &out) { out = luaL_checkunsigned(l, index); }
            ^
2 errors generated.
```

Looks like on FreeBSD/i386 `size_t` and `unsigned int` are the same type, so the overload becomes bogus.

### PR DESCRIPTION
**Pull request by AMDmi3**
Fixes #5527

### CODE REVIEW

**Comment by AMDmi3** [comment]
Looks like vs solution needs path to `buildopts.h` added somewhere. Sorry, I cannot fix this bit myself.

**Comment by Web-eWorks** [comment]
Rather than defining this in `buildopts.h` (and thus including buildopts.h into almost every lua-related file), please simply add it as a target-level or global `#define` via CMake's `[target_]add_definitions()` utility.

**Comment by Web-eWorks** [comment]
In general however, we are phasing out support for 32-bit targets for Pioneer. I would not be surprised to find other areas of the code which have compilation or runtime issues on a 32-bit OS.

**Comment by AMDmi3** [comment]
That would be fine too, but if so it would be nice to have it documented somewhere.

**Comment by AMDmi3** [comment]
Done. Still need help with the solution though.

**Comment by Web-eWorks** [comment]
> Done. Still need help with the solution though.

Looking at the individual `.vcxproj` files, the VS solution only provides 64-bit targets. No changes required.

...now that I'm looking at the code with fresh eyes, the "cleanest" solution is to replace `size_t` with `uint64_t` and `unsigned int` with `uint32_t` (something we probably should have done a while ago), as that a) would not need a preprocessor define, and b) more correctly express the intent of the code regardless of processor word size.

I don't want to ask you to rework this PR for a third time though, so if you're satisfied with the current state, we can merge as-is.

**Comment by AMDmi3** [comment]
I have no problem with reworking this once more. I've opened a separate PR #5538,to leave this for reference purposes, if #5538 is OK this may be closed.

**Comment by Web-eWorks** [comment]
Closing in favor of #5538.

**Pull request closed without merging**
