### PR TITLE
.gitignore: add jetbrains, reorder and categorise

### PR DESCRIPTION
**Pull request by d3rp**
Few additions to the .gitignore for IDEs

### CODE REVIEW

**Comment by impaktor** [comment]
Difficult to see what the change is when there's a lot of lines that are removed and added back in again?

**Comment by d3rp** [comment]
Added jetbrains files and categorised others

**Comment by Web-eWorks** [comment]
Can you enumerate which entries specifically you added for jetbrains? I'm happy with the re-order, but I'd like to know what's intended to be kept for that IDE as I'll be doing a cleanup of some old and no-longer-required ignores if this PR is merged.

**Comment by d3rp** [comment]
clion (Jetbraims) uses these folders by default
`.idea`
`cmake-*`

If you want to be more explixit with the cmake folders, `cmake-build-*` would do.

**Comment by Web-eWorks** [comment]
Accepted. You'll most likely have to rebase your other PR on master once this is merged.

**Pull request merged**
