### PR TITLE
Make Autosave optional

### PR DESCRIPTION
**Pull request by impaktor**
Since there were complaints of long stalls when docking / undocking, and people not making use of it anyway.

Note: this is untested!

### CODE REVIEW

**Comment by impaktor** [comment]
... in #3511

**Comment by fluffyfreak** [comment]
Goes kablooey in `optionCheckBox` from `Settings.lua` line 19

I wish we could copy and paste from that damned error dialog!!!

**Comment by impaktor** [comment]
> I wish we could copy and paste from that damned error dialog!!!

When running pioneer from the command line (as I do) it is also echoed there. 

I'll probably just misstyped something. I'll have a look tomorrow. Thanks!

**Comment by laarmen** [comment]
We could simply put the text in the clipboard (SDL_SetClipboardText) when there's an error. I wish we could add a button to the error dialog but the widget is, by design, too primitive for that.

**Comment by impaktor** [comment]
Wow. Many bugs and typos in it. Fixed them all now.

I've tested both disabled and enabled autosave, and it seems to work now.

**Pull request merged**
