### PR TITLE
Add instructions on building pioneer with CMake and MSYS2

### PR DESCRIPTION
**Pull request by dlshcbmuipmam**
The documentation lacks the instruction of CMake build in Windows, but it is strict forward to do so in MSYS2. I have added a few lines to describe that.

### CODE REVIEW

**Comment by impaktor** [comment]
Nice, thanks!

**Comment by pcercuei** [comment]
What's about the CMAKE_SH trick? I never had to do that.

**Comment by dlshcbmuipmam** [comment]
> What's about the CMAKE_SH trick? I never had to do that.

This is a strange limitation of CMake and MSYS2. There is a sh.exe under MSYS2 path, and you will get an error because of that when you run CMake in MinGW shell. "CMAKE_SH="CMA KE_SH-NOTFOUND" tells CMake to ignore the sh.exe.

**Comment by fluffyfreak** [comment]
I don't know why this hadn't already been merged so I've done it now :)

Thanks for the instructions @dlshcbmuipmam

**Pull request merged**
