### PR TITLE
It is the nature of all things to die.

### PR DESCRIPTION
**Pull request by Web-eWorks**
It's the end of an era.

We've finally removed everything related to newUI from the codebase, and now newUI itself shall follow.

You may read the commit descriptions for the long soliloquy that the PR title is based on, but the short of it is that this removes 14k lines from the codebase, cuts the number of UI systems in use by 1/3rd, and is one step further to a resizable game window.

I've also re-implemented the LuaConsole in ImGui; it's not perfect by any means (I have a few bugs to work around later) but it mimics the functionality of the old console perfectly... by which I mean that completions don't do anything, history works just fine, and I've even added functionality to copy the game's log messages into the console's scrollback buffer!

image

### CODE REVIEW

**Comment by impaktor** [comment]
Yay!

Btw, @robn, @johnbartholomew should read the commit message :)

2020-11-29-095637_1600x900_scrot

**Comment by johnbartholomew** [comment]
Congratulations to all! You've done amazing work over the past many many months. I know I haven't dropped by in a while, but I do still have github notifications turned on so I see all the pull requests flying past! It's incredibly cool to see so much effort and so much progress, and to see Pioneer continuing to attract new people with new talents.

Updating my local repo, `tig` tells me Pioneer has 19275 commits (including the two in this branch :slightly_smiling_face:). The project was started by Tom Morton back in 2008 (with early contributions from John Jordan and others), and the set of active contributors has gone through many changes over time. I see AUTHORS.txt now lists 115 people!

**Comment by robn** [comment]
Pretty much what @johnbartholomew. Its quite humbling to have your work built on, and even more when it grows to a point that your work gets ripped out and replaced.

Right on, commanders! :rocket:

**Comment by impaktor** [comment]
Just for nostalgic reasons, I'll link in #2589 which was the first NewUI PR, which moved all the station screen. Also, fun personal note: I think that was the first time I compiled someone else's branch, as @robn asked me (back then, I was "only" a player) to test it.

**Pull request merged**
