### PR TITLE
[Workaround to avoid CTD] Initialize variables to be integers

### PR DESCRIPTION
**Pull request by mike-f1**
Get an error in master:
```
Could not find model: sinonatrix_cockpit
error: [string "[T] @modules/SearchRescue/SearchRescue.lua"]:544: attempt to perform arithmetic on local 'pickup_crew' (a nil value)
stack traceback:
	[string "[T] @modules/SearchRescue/SearchRescue.lua"]:544: in function 'calcReward'
	[string "[T] @modules/SearchRescue/SearchRescue.lua"]:1333: in function 'makeAdvert'
	[string "[T] @modules/SearchRescue/SearchRescue.lua"]:1984: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>

```

...Thus I pushed the simpler solution.
It is quick and dirty: ~~not tested~~ and it should be checked if works for every mission

### CODE REVIEW

**Comment by vakhoir** [comment]
I had a look, and tested it several times as well, seems ok to me. Didn't get any more crashes so I suppose no other missions are affected.

**Comment by mike-f1** [comment]
> I had a look, and tested it several times as well, seems ok to me. Didn't get any more crashes so I suppose no other missions are affected.

Yeah: it is working because it took "nil" which wasn't a number: My doubts are about 
the correctness of "0" as default value thus the "workaround" in PR title.

**Comment by fluffyfreak** [comment]
I'm going to merge this as it avoids a crash to desktop. Correctness can come later ;)

**Comment by mike-f1** [comment]
Link to #3795 (or more probably #4569) which seems to introduce the bug...

**Pull request merged**
