### PR TITLE
WIP - Cloud Shell

### PR DESCRIPTION
**Pull request by fluffyfreak**
# Clouds (2D)

Note that 2D clouds mean there is a single layer around the planet with a cloud texture applied too it.
This comes from a generation process that should become unique for each world based on it's atmophere and attributes (_gravity, size, rotation rate, atmosphere desntiy etc_).
# Work-in-progress

I'm putting this up to force myself to focus on it and fix the issues that remain.
- [x] Black clouds - I'm doing something wrong here, cloud are either fully white or black.
- [x] Not tested CPU path at all yet.
- [ ] No variation depending on world type, parameters are hardcoded in shader.
- [ ] Cloud Colouring - Clouds now have some colour but it needs rewriting...
- [ ] --- other stuff I'm too tired to remember, [fill-in-later](http://eab.abime.net/showpost.php?p=811091&postcount=1) ---
# Images

There's a [public album](https://goo.gl/photos/6EybyYdsA28Ww7Ez5) showing what it currently looks like.

Andy

### CODE REVIEW

**Comment by walterar** [comment]
Compiles fine on linux.
From the planet's surface it looks wonderful, but still from space, no.
I like this.

**Comment by impaktor** [comment]
WOw, looks very cool under time accel.

I'm experiencing significant CPU load upon start up. Like more than 10 seconds of unresponsiveness. Although that is with max graphics settings, I think, so I'll happily decrease my city size for clouds.

**Comment by fluffyfreak** [comment]
This probably needs a lot more work, some additional ideas here:
https://jwhigham.wordpress.com/2010/05/21/clouding-the-issue/
https://jwhigham.wordpress.com/2010/05/21/captain-coriolis/

**Comment by HybridDog** [comment]
How about that?
http://web.archive.org/web/20160418004149/http://freespace.virgin.net/hugo.elias/models/m_clouds.htm

**Comment by fluffyfreak** [comment]
Ugh, I've lost the will to work on this for now. Rendering stuff to do with the planets is hard fucking work at times.

Closing.

**Pull request closed without merging**
