### PR TITLE
Search&Rescue: bug fixes and more realistic ship simulation

### PR DESCRIPTION
**Pull request by clausimu**
This was supposed to be a simple PR that fixes the crew delivery mission in the Search & Rescue script - but one thing lead to another, depended on another - and here we are. The switch to more realistic ship simulation caused many of the downstream changes. There are more fixes/improvements coming, but I can make a cut here to limit PR size.

What this PR does:

- Simulate AI ships more realistically, with appropriate min/max crew, fuel to fly and hyperjump, engine selection, etc.
- Removed low-level hyperjump calls (ship:InitiateHyperjumpTo).
- Fuel requested for "out-of-fuel" missions is now variable (instead of fixed to 1 ton) and dependent on the target ship fuel tank size, engine, location and future nav-target.
- Crew requested for "missing crew" missions is variable based on crew present (variable too now) and dependent on min-Crew/max-Crew per target ship.
- Maximum of crew and passengers to be picked up or delivered increased from 4 & 2 to 8 & 20.
- For personnel pickup missions there is now a 50:50 chance that it will include passengers in addition to crew. If passenger transport is requested, the number of passengers is dependent on the target ship size (maximum = 20).
- Police ships are excluded as target ships.
- More effort is made to find a suitable target ship type during mission creation to limit the reduction of ad creation due to not finding a possible target ship that fit the mission criteria.
- If the target ship cannot hyp away after mission completion it is now discarded via explosion after flying in high orbit around planet or sun for 10 minutes.

I added "WIP" to the title because bug #3794 may or may not depend on this SAR script. Once the cause for that bug is found this can be merged (unless there are objections, of course).

### CODE REVIEW

**Comment by clausimu** [comment]
This can be merged now - as far as I am concerned.

**Comment by walterar** [comment]
@clausimu Look to the future:

"We request the delivery of {amount_of} of {cargo} to the ship."

In this way you will not have to change in the future this line of language.

{cargo}, now = hydrogen
{cargo}, future = liquor, hyperdrive, narcotics, military fuel, missiles, etc.

**Comment by clausimu** [comment]
@walterar - point taken. I like the subtle different flavors in language though for the different mission types in the SAR script. Because others have already done the work and translated the strings I have gone ahead and just replaced the specific "hydrogen fuel" with the more general "{cargo}" per string instead of using the same string altogether for each mission type. Under the hood the correct cargo type is now selected to make future extensions easier.

Since this is a significant update already, I'd like to merge it as is without further additions. There is more coming (for example adjusting reward based on cargo amount delivered, etc.) in following PRs once this one is in. I can do further additions in these smaller PRs.

**Comment by walterar** [comment]
@clausimu Yes, it is better to merge as is. No time for other things. Geraldine is waiting to publish Pioneer (August) in ModDB ;))

**Comment by laarmen** [comment]
Allright, let's merge this bugger.

**Pull request merged**
