### PR TITLE
Font Consistency and Other Bit-Twiddling

### PR DESCRIPTION
**Pull request by Web-eWorks**
This PR is technically still a bugfix!

This fixes several issues related to font sizing and consistency of font choices in the info and station screens, fixes an overlap between the ScanManager window and the cargo widget, as well as fixing an issue where the comms log did not scale with the rest of the UI, resulting in incredibly tiny comms messages on 4k screens.

I've made a few opinionated changes to UI element layout to fix minor issues and improve readability, like in the Ship Market screen.

I've generally brought the UI elements in line to use the semantic font size breakpoints I've been gradually introducing over the last year - now there are 'details', 'body', 'heading' and 'title' sizes for both Pionillium and Orbiteer, with the various screen code using those breakpoints as appropriate. Some screens use the heading size for content that really should be 'body', simply because the screen is so empty otherwise it looks incredibly out of place. (Those screens would be good candidates for future work or merging into e.g. the Station Lobby tab.)

I'll most likely push one more commit to this branch to adjust the top-level TabView widget and make a few opinionated changes there as well, but this is otherwise complete IMO.

Finally, this PR makes one balance change, which is to increase the trade-in value of ships in good repair to 65% from 50% - this should make our starts (especially the easy one) slightly less difficult to get to the point of upgrading to a better ship.

A picture or two for good measure:

image
image
image
image

And one at 1280x720 showing fonts aren't too small to read :smile:
image

### CODE REVIEW

**Comment by impaktor** [comment]
Based on the screen shots, it looks fine.

**Comment by RacerBG** [comment]
Looks very good so far though I would like to know if this PR fixes or improves the cyrillic characters inconsistencies which I reported earlier here #4977 and here #5133.

**Comment by Web-eWorks** [comment]
This does not address font-related issues (incorrect character sizing relative to the rest of the text string, strings clipping off of buttons), but may have a positive effect on some parts of the reported issues due to using a globally smaller font. You're welcome to test the new build and check for yourself though!

**Comment by Web-eWorks** [comment]
Merging as-is, my changes to the Tab View didn't wind up being an improvement sadly.

**Comment by Web-eWorks** [comment]
IIRC that's always been that way on small enough resolutions, and is a side-effect of not being able to specify additional padding next to a scrollbar in ImGui.

**Pull request merged**
