### PR TITLE
First commit of the Bluenose frieghter

### PR DESCRIPTION
**Pull request by BobTheTerrible**
Crosses fingers that this time it is actually right...

### CODE REVIEW

**Comment by fluffyfreak** [comment]
Thanks Bob, hopefully @nozmajner will be around sometime to review :)

**Comment by nozmajner** [comment]
It's good. :)

**Comment by impaktor** [comment]
SWEEET!

Is it intentional to not have atmospheric capabilities?

**Comment by BobTheTerrible** [comment]
Er...... well.... er... maybe?? I guess I need to give it some atmos shielding if I want to be able to land??

**Comment by nozmajner** [comment]
I always thought that this one won't have atmo capabilities.

**Comment by BobTheTerrible** [comment]
I remember that being discussed way-back-when. To be honest I will take ppls lead on this. No atmo works for me. Just happy to get it in.

**Comment by fluffyfreak** [comment]
So we're all happy with this?

**Comment by laarmen** [comment]
@nozmajner is the boss on that :)

**Comment by nozmajner** [comment]
Yupp, I think it's ok that it can't atmosphere. :) Heh, boss.... :P

**Pull request merged**
