### PR TITLE
Render far away

### PR DESCRIPTION
**Pull request by fluffyfreak**
Keep rendering stars and planets even though they are very very far away.

I was going through some old branches to clear them out and found this one. Thought it worth fixing up and submitting for review.

Andy

### CODE REVIEW

**Comment by impaktor** [comment]
> Keep rendering stars and planets even though they are very very far away.

Didn't @robn do some billboard light stuff, to not render things less than 4 pixels big or something?

**Comment by fluffyfreak** [comment]
Yes but as people have pointed out you can still see planets and stars at hilarious distances, since they're only being drawn as billboards it's very cheap. Might as well just show them.

**Comment by fluffyfreak** [comment]
Also this doesn't change @robn billboard rendering optimisations. It just keeps rendering planets & stars as billboards for longer. All other objects are culled once they get small enough.

**Comment by impaktor** [comment]
OK. I have no further input.

**Pull request merged**
