### PR TITLE
Law and order to lua

### LINKED ISSUE #62: Launch clearance
Requesting launch clearance, and actually launching, are currently behaving in exactly the same manner.  Should launching automatically request clearance, and should requesting clearance automatically launch?

Frontier's behaviour:
*In an enclosed dock, launch button didn't work without clearance.  Requesting clearance launched ship.
*In an open air port, launch button always worked (but was a crime to use without clearance) and requesting clearance didn't cause a launch.

The latter case doesn't exist in Pioneer yet.

### LINKED ISSUE #873: There's no penalty for dumping rubbish or radioactives
Buy garbage, jettison it, enjoy the free spacebucks.

This would be easily (?) scriptable as a lua module using onJettison and AddCrime (making it easier to tweak the rules/disable the feature as well).

### LINKED ISSUE #1055: Move police to Lua
Police function should be performed in Lua. Requires a few additional API calls:

1. Spawn and launch a ship
    - even if the landing bays are all full. For orbitals, just spit the spawned ship out of the door. For surface stations, launch from somewhere other than a landing pad.
    - #526 could be used in combination with a ship delete function to temporarily free up a bay for launches.
2. Land and delete a ship
    - Again, even if all the bays are full. This would be handy for removing other ships from time to time, too.
3. An event handler for paying a fine (so that the police can be called off).
    - Actually, fines and definition of crimes should all be under Lua control, and perhaps #770 could be used with the station as the target to pay fines. Then the station would call off the hounds.

### LINKED ISSUE #1237: Police ship should not be hardcoded
At the moment, the ladybird is hardcoded as the police ship (see [SpaceStation.cpp:473](https://github.com/pioneerspacesim/pioneer/blob/master/src/SpaceStation.cpp#L473)). Probably the tag system should be used instead.

Related: #1221

### LINKED ISSUE #1731: 3 Strikes Rule for Weapons fire in city limits - Same with Collison Warning
This is so bloody annoying (in fact I'm so used to it , I forget it's a problem.)

If it has to be asked, what some of the most annoying things a first time Pioneer player will encounter in game I'm certain this will rank highly.

  How many times I have accidentaly fired a weapon - causing me to have to reload - well grrrrr.. is all I have to say.

Anyways, just think this is too important to pan.

baobob

### PR DESCRIPTION
**Pull request by impaktor**
# Move Law to Lua

This moves the law enforcement from `Polit.cpp` (which is almost empty now) to lua. I worked on this about 6 months ago, but I got stuck due to a segfault when loading a game, but it seems to have fixed itself now (after updating branch to master).

__Update:__ as of 2015-08 I'm continuing this due to #887 being "fixed". 

## Changed/New features

Some of the changes in how police will behave now:

1. Police number, and how quickly they react to your crimes (police launch probability) depends on system lawlessness.
2. However, police will not launch until player has amassed high enough fines. I.e. threshold isn't `fine = 0` anymore, but `maxFineTolerated=1e3`
3. Lowered fine on piracy to `1e5`, and weapons discharge to `1e2`, allowing the latter to be below the `maxFineTolerated` level.
4. Dumping illegal goods or goods with negative price (close to station) is an offense.
5. Crime record now lists _how many_ of each crime type the player has.
6. Player has two crimerecords for each faction, one with "outstanding fines", and one "Crimerecord" with past history.
7. A police ship destroyed at a station remains so until player hyperjumps back (same as before I believe); i.e. limited number of police ships in station.
8. Police ships are different for different factions. Default: sinonatrix, CIW: pumpkinseed, SolFed: kanara.

## Design / Code

I'm not sure about what code to put in which file, i.e. how to structure it. Current structure reflects a lot of the development history during my work on this.

- I've introduced a `libs/Legal.Lua` that holds the crime constants, and a `notifyOfCrime()` which was previously in `Polit.cpp`.

- I've introduced a  `modules/CrimeTracking` to be symmetric with our `modules/StatsTracking`. It has the event triggers (`onShip<ActionX>`) for killing, firing, jettison, etc. and it holds the `doLawAndOrder()` (previously in `SpaceStation.cpp`).

- `libs/Player.lua` has a local CrimeRecord class, which the player has two copies of for each faction (current crimes, and past crimes). There are also Player:AddCrime() and such.

-  In the old (current master) code, each space station upholds the law (every frame) by calling the function DoLawAndOrder. I could implement it the same way in `libs/SpaceStation.lua`, but thought it needs only be called _once_ (about every 5 seconds), at which point a check is made to find the closest space station (calls a new method: `Ship:GetLawEnforcingStations()`, returns stations within "law range"), thus you will not be fined twice for one single illegal action done within range of both stations. (I still have to check the distance of the player to all stations every call.)

- "law range" is a new attribute: `Station.lawEnforcedRange` (100 km).

- Stations have a `SpaceStation:LaunchPolice(targetShip)` and `Station:LandPolice()`.

## Progress

- [x] 1. Remove all crime handling from c++
- [x] 2. Implement crime handling in Lua (kind of done), closes #1055
- [x] 3. Crime record shows number of violations of each type
- [x] 4. Police ship set by faction definition, fixes #1237
- [x] 5. Deny launch clearance if player has unpaid fines, fixes #62
- [x] 6. Dumping cargo with negative price (close to station) is a crime, fixes #873
- [x] 7. Police is launched first after some threshold of illegal actions is passed, closes #1731
- [x] 8. Crime record in Lua is a class
- [x] 9. Better methods for getting at the player's crimes in the `Player.record` table?
- [x] 10. Fix frequent crashes when a police ship is dead (#887)
- [x] 11. Implement a `Player:ClearCrimeFine`, and clean up comments in `lib/Player.lua`
- [x] 12. Test-test-test: Save/Load when chased by police and killed police and test again
- [x] 13. Moved Crime constants work in translation system
- [x] 14. Store settled crimes in an old crime record and still remember them
- [x] 15. Check natural doc rendering of API documenting strings

## For another separate pull request:

When this is merged, I'll be looking into:

1. Label police ships after the police name used by the faction, requires JSON to faction (It is really cool when the launched police is labeled as "Confederate Police" instead of just "Police".) see: #2867
2. Fix legal footer, #2863.
3. Find a better way of compounding fines in `NotifyOfCrime`. For now: works as it used to.
4. taking off when denied launch clearance is a crime
5. Number of available police ships should depend on station size?
6. Pay fines remotely by F4.
7. `IsCommodityLegal` should be in lua?

### CODE REVIEW

**Comment by nozmajner** [comment]
The two new police ship textures:
sinonatrix
pumpkin
This one doesn't have text, because the UVs are mirrored.

**Comment by impaktor** [comment]
For the record, I've been working on this PR this summer, and have it almost done, (I poked @nozmajner about the police textures, thanks). What remains is just to clean up and push the last code changes from my local computer. I currently have _very_ little time (or at least aught to have), so I'll see when this gets done.

**Comment by impaktor** [comment]
This has been fermenting for over a year now (first commit: 2014 April), and I'm almost approaching issue-1799 status, but now I think I'm ready for this to be reviewed. I don't know how many times I've rebased this, but it's _a_ _lot_, so the commits should make sense.

I don't expect anyone to read all code, but I would like:

- Please re-read the original top post (I've updated it)

- Please (if you have an opinion) look at the balance or "which-function-goes-where" in the files: `libs/Legal.lua`, `modules/CrimeTracking/CrimeTracking.lua` (and `libs/Player.lua`). My current thinking is that at least `Legal.lua` and `CrimeTracking.lua` could be combined or something? @laarmen, @johnbartholomew ?

- If anyone care, play around with it. Specifically, test save/load, jump between factions, and blow up police and save->load.

- Yes, I know the Police screen isn't updated real-time when you pay your fines, one has to go to some other tab then back again. I don't consider it a bug, more a lack-of-feature-I-didn't-care-to-fix. It's all in Lua, so anyone can play around with it.

So 90% of this work (c++ -> lua) is nothing anyone will notice, but at least below is some eye-candy. Hmmm. Or perhaps eye-oatmeal.

__I'VE BEEN BAD:__
screenshot-20150818-164622

__BUT I RIGHTED MY WRONGS:__
screenshot-20150818-164710

__BUT OLD HABITS DIE HARD:__
screenshot-20150818-164803

**Comment by fluffyfreak** [comment]
Excellent work!

I don't think I can bring myself to stare at any code tonight after doing it all day for work but will try to look into it & testing next week / Sunday.

Everyone else chip in where possible!

**Comment by impaktor** [comment]
Thanks @fluffyfreak! By the way, we're getting OpenGL errors on the new police ships, I'm guessing you can understand that more easily than me or @nozmajner.

I can add that since now the code is in Lua, it's easy for anyone to play around with how fines should work, how they're accumulated, and also how/when police should be dispatched. I wrote that part over a year ago, and I'm slightly foggy on it, and it can be tweaked later, but since I lowered fine for "unlawful firing" and put a threshold for when police will start shooting at you, you now have to shoot quite a bit to raise the police.

**Comment by laarmen** [comment]
Baaah, just merge it, get flamed for a week or two by random users while we
put out all the fires it started, and get done with it. That's how I did it
;-).

Another, slightly less fun idea would be to issue a call for tests on SSC,
Twitter, G+ and the dev forum. I dunno who has the setup to produce random
win32 builds, but this might prove useful. @robn, @walterar maybe ?

**Comment by fluffyfreak** [comment]
@impaktor & @nozmajner I think the OpenGL errors are coming from the `pumpkinseed_police_diff.dds` texture which is 1024x1025 <-- note the "5" instead of a "4" in there.

DDS textures using DXT1, DXT1a or DXT5 must be either power of two, or divisible by 4 in each dimension. So 1028 might be ok, or 1020, but 1025 isn't.

**Comment by fluffyfreak** [comment]
Also @laarmen might have a good point, we've got until the end of the month so getting more eyeballs on it and then fixing the obvious issues could be one approach.

Or wait until next month and merge right at the start to give maximum time.

So far I've not noticed any problems but I was only looking at the opengl issue thus far. I haven't been able to get the Police to attack me despite shooting at a ground station for a while though.

Will test some more :)

**Comment by fluffyfreak** [comment]
Ok, I have `278 Unlaful weapon discharge` and a `$178` fine but no police have come after me yet.

**Comment by impaktor** [comment]
Yes, so the threshold for launching police is currently 1000, and fine for shooting in Sol is 100, (on New Hope it's 89). I think I should lower the threshold to 300, i.e. a three strike policy for `lawlessness = 0` system.

I also agree with letting the players test it, and find the bugs. Ideally, I think it would be good with a "pioneer stable" version, and a "latest" version, my thinking is that the "stable" version is best for new players, since it's a bit of a bummer to try pioneer for the first time and end up with bugs and crashes.

Also, please note: this PR does not include any save-bump commit, so up to the merger to fix that.

Do we know of any other save-bumping code that might pop-up in the near future?

> Ok, I have 278 Unlaful weapon discharge and a $178 fine but no police have come after me yet.

I'll look into that, what system?

**Comment by fluffyfreak** [comment]
Got a crash now. 
To repeat do the following:
1. Start at `New Hope`
2. Take-off shoot up the `Itzalean` station a little.
3. Fly away to `Eridani Commercial Center` - shoot it up a little too.
4. Dock and save game.
5. Exit game.
6. Load saved game.
7. Press `F5` to undock.
8. As soon as you're given control start shooting...

Game crashes.

Apparently method `Add` is a `Nil` value in function `AddCrime`.

**Comment by fluffyfreak** [comment]
> > Ok, I have 278 Unlaful weapon discharge and a $178 fine but no police have come after me yet.
> I'll look into that, what system?

New Hope :)

**Comment by impaktor** [comment]
Interesting. I have to admitt I did most of my testing last year before I thought I'd be clever and implement a CrimeRecord-class in Player.lua. I'll look into it during the comming days, I hope.

Thanks for testing.

**Comment by fluffyfreak** [comment]
It'd be nice if we could do this merge along with the other two savegame bumps.

**Comment by impaktor** [comment]
Hint taken. :smile: 

I have it on my todo-list for this weekend, which doesn't guarantee much, since I cant do more than look at the code and think, since I can't run pioneer on my weekend-laptop.

All my pioneer-time this past week went into writing a single post on the [rebalancing](http://pioneerspacesim.net/forum/viewtopic.php?p=4191#p4191) thread on the forum.

**Comment by fluffyfreak** [comment]
It (_laptop_) won't run OpenGL 3 right? Or will it do 3.0 but not > 3.0?

**Comment by impaktor** [comment]
> won't run OpenGL 3 right?

Right. I think we established it was < 3.

I know @laarmen started looking into running pioneer from just a terminal, without graphics. I don't know how far that went. 


> Ok, I have 278 Unlaful weapon discharge and a $178 fine but no police have come after me

This is understandable, since I'm using the exact same formula for how fines are treated, but lowered the fine for unlawful discharge. I think I''ll undo that, and instead have some timer or something that keeps them from adding up so fast.

**Comment by impaktor** [comment]
Just an update on the bug-hunting: I see what is happening, (I save a table but load a table of table, it seems), but I'd also like to understand it before I fix it.

This is a result due to my foggy understanding of serialization of classes and tables.

I hope I have time by Friday to fix it.

Either way, all that is needed to trigger the bug is to load a game where the player has unpayed fines and add shoot.

**Comment by impaktor** [comment]
OK, pushed fix for each of the two issues raised above (crash-bug, and too low fine for weapons discharge). 

What I wrote in my last post was crazy talk, the problem was that I didn't serialize the `CrimeRecord` class properly (read: "not at all"), so the data was saved (and restored), but not the class methods, i.e. the `CrimeRecord` no longer had an `Add()` method after load (and no metatable to look it up in)

I also switched to use the infrastructure @laarmen wrote for classes in utils.lua, so I use the constructor written by him (thanks!).

If anyone is interested in testing this further, I'd put main focus on saving/loading/quitting (with active and/or old crime record for various factions) since bugs here will likely require save-bumping the game again upon fix, I suspect.

(I did test save/load with fines both payed and unpayed, in various combinations)

However, __I did notice a bug__, that I don't know if I'm to blame for in AutoSave (ping @johnbartholomew). How to reproduce:
1. Start new game, London -> try to buy something from "Bernard's holding" from the BBS and get a fine
2. Save
3. Exit and Load save (check that CrimeRecord is correctly loaded)
4. Exit
5. Load the "_exit" save. 

Strangely it seems to work if
1. Same as 1. above
2. Exit
3. Load from "_exit"

The bug is quite serious I think as continuing game might be done from loading the "_exit" autosave.

The few times (1-2 times) I tested "_autosave"-files they seemed to work.

**Comment by fluffyfreak** [comment]
I'll try to test this asap.

Whilst adding your repo' on another machine I noticed you've got loads of interesting branches! Pirates, Scouts, tech levels, deliveries and that old Lanner that could probably go up as a mod :)

Very interesting stuff! You should take some time off work and get them in :P

**Comment by fluffyfreak** [comment]
Hah, first thing that caught me out is you haven't merged latest in a while so there was no vs2015 project to load! :)

That conflict it mentions is just a couple of lines in `spacestation.h`, nothing serious it's just we've both deleted adjacent member variables which are no longer used.

Nearly lunchtime, hope to test then.

**Comment by impaktor** [comment]
> Whilst adding your repo' on another machine I noticed you've got loads of interesting branches! Pirates, Scouts, tech levels, deliveries and that old Lanner that could probably go up as a mod :)

- scout-mission is basically done, I just have to hook it into #3432 so that's my next priority after this, (well, I think I'll also keep tinkering with crime/fines some more, and add a few more offenses, but that's for another PR).
- [lanner](https://github.com/impaktor/pioneer/tree/lanner) is up for anyone who want to salvage it. Is it not in scout+ (ping @walterar)?
- For my deliver_message branch: that is almost done, but it doesn't really do anything much "new" (compared to deliver package), just a bunch (+60 flavours) "mysterious" messages to be delivered.

> Very interesting stuff! You should take some time off work and get them in :P

time? Ah, yes, you mean that precious thing that ran out for me last month (my contract ended, but since my task isn't complete I'm getting an extension, 3 months at a time). 

> That conflict it mentions is just a couple of lines in spacestation.h, nothing serious it's just we've both deleted adjacent member variables which are no longer used.

(I did notice the conflict as well last night, but didn't push any master-merge.)

> Nearly lunchtime, hope to test then.

Thanks for testing! (and _bon appetit_)

**Comment by fluffyfreak** [comment]
[Lanner as mod](http://spacesimcentral.com/ssc/topic/5277-lanner-for-current-pioneer-build/)

Rolling contract is kind of what I'm on now too, I expect that it will last until March/April next year but that's only based on what we've discussed there's nothing in writing. Such is life!

Now then **the bug**: yes I see it even with the latest merged in (_hoped for fixes_) which is pretty bad.
I don't understand the Lua save system at all unfortunately but I can at least confirm it for you :/

**Comment by fluffyfreak** [comment]
Is there a way to write to the output log from the Lua save methods so that you can see if they're being recorded/restored? Perhaps figure out where they are themselves called from and put some logging in there to figure out if they are being called, and if they are why they're not saving/restoring.

**Comment by impaktor** [comment]
I'm not sure my description for reproducing this bug is 100% deterministic. Seems like sometimes it works, sometimes not. I'm printing out debug statements, so I can see the bug happening "real time". I.e. when saving manually the save system always calls the serializer of the lua-class, as it should, and it prints out "...SERIALIZED!" (I've pushed a debug commit). When autosave does a save, it prints out "SAVED <savename>".

So just by doing:

1. save manually
2. exit game, 

I can get two different printouts:

### without bug triggered:
I get one print from CrimeRecord serializer for each save call (1 manual, 1 from autosave), and then AutoSave notifies me it's been called and saved to a file called `_exit`.
```
TradeShips: Removed 0 ships before serialization
...SERIALIZED!
TradeShips: Removed 0 ships before serialization
...SERIALIZED!
...SAVED!	_exit
```

### with bug triggered:
First printout if from my manual save. Second is from AutoSave, but somewhere down the line it failed to call the serializer of the class:
```
TradeShips: Removed 0 ships before serialization
...SERIALIZED!
TradeShips: Removed 0 ships before serialization
...SAVED!	_exit
```

So I'm guessing somewhere between LuaGame.cpp and LuaSerializer.cpp something strange is happening. I cant poke this more tonight.

**Comment by laarmen** [comment]
I'm mostly afk these days, but I'll try to take a look. I had my fair share
of battles against this subsystem ;-)

**Comment by impaktor** [comment]
That would be greatly appreciated @laarmen, because I'm at a loss here!

It might be interesting to also have debug printout for the Equipment serialization, since that might also have the bug, and if it doesn't then that's narrowed it down further. My CrimeRecord class is, as of my recent fix of the bug fluffy found, basically just an exact copy of your Equipment implementation.

**Comment by johnbartholomew** [comment]
Best guess about the bug is that it's because both the AutoSave module and the Player module have registered handlers for the "onGameEnd" event. The Player module onGameEnd handler clears out the player's data -- if that runs before AutoSave onGameEnd then the _exit save will have no crime record.

Should be fairly easy to fix -- don't try to clean up any state in onGameEnd; instead, reset the state in onGameStart (and then inject anything needed from loaded_data). It's not a very nice system, but should work ok.

**Comment by impaktor** [comment]
I believe you are as usual, spot on!


And as usual, I was way off. (How come I always look for bugs in the wrong place... until I find it? :stuck_out_tongue_winking_eye:  )

I've put a printout in `OnGameEnd` and indeed it is called before the autosave, which then has no CrimeRecord object to serialize. (with the printout I can't seem to get the bug not to happen, to really make sure they're called in the opposite order)

**Comment by impaktor** [comment]
Rebased (probably for the +40th time), and cleaned/squashed up previous fixes, (except for the last one, since that commit would have to be split in two and then each part merged into two different commits, and I don't feel much like doing that).

So, to the best of my knowledge, this PR is now done.

**Pull request merged**
