### PR TITLE
New behaviour of ESC button

### PR DESCRIPTION
**Pull request by salborrelli**
This request is the natural follow-up to a discussion we recently had in the Dev forum, namely:

http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=385

In short: so far the effect of pressing the ESC key has been to pause the game and open the Settings View, regardless of the context we are in at the moment. I have changed this so as pressing the ESC button is now someway closer to what normal users might expect, and probably more useful as well.

Please review the attached Excel file for a description of the new effect of pressing the ESC key depending on the current context. Let me know if you find any problem or bug in the implementation.
[esc_key.xlsx](https://github.com/pioneerspacesim/pioneer/files/112465/esc_key.xlsx)

### CODE REVIEW

**Comment by impaktor** [comment]
Interesting. I would have guessed more code would be touched. Goes to show what I (don't) know. I'll give this a test later in the week, unless someone else beats me to it.

I wonder if  ESC will also close the Lua console window?

**Comment by salborrelli** [comment]
>I wonder if ESC will also close the Lua console window?

Looks like it does, but I haven't changed anything related to LUA of course since I know nothing about the language. I can only guess that the LUA console is a new layer created on top of the current view, so pressing ESC simply hides it and switches back to the previous layer in the stack.

**Comment by walterar** [comment]
:+1:

**Comment by fluffyfreak** [comment]
This is nice, happy to merge since it has the coveted the @walterar seal of approval :+1: :grinning:

**Comment by walterar** [comment]
I love the English humor. :)

**Comment by salborrelli** [comment]
@fluffyfreak great ... and btw let me know when / if you need to update the downloadable version for Mac on the web site.

**Comment by fluffyfreak** [comment]
@salborrelli I don't think there's anything in the development pipeline for a little while so now might be a good point to do a new Mac version.

**Comment by salborrelli** [comment]
> @salborrelli I don't think there's anything in the development pipeline for a little while so now might be a good point to do a new Mac version.

@fluffyfreak Done! This is the link to the latest installer for Mac OS X:

https://drive.google.com/file/d/0B3YT4wkIA2jjMEZxWFRrckJza2c/view?usp=sharing

Let me know in case you have any issue downloading the file.

**Comment by impaktor** [comment]
@salborrelli Great! 

You have other projects / ideas to work on for pioneer, right? Let us know if you're looking to get busy :stuck_out_tongue:   

I trust @fluffyfreak can conjur that file to sourceforge

**Comment by salborrelli** [comment]
@impaktor Sadly I don't need Pioneer for getting busy, I'm already busy enough without :smile: And yes I already have another idea that I'll develop as soon as I've time. But I would like to hear your ideas too so let me know if you have some interesting proposal. Basically I can contribute to every aspect of the project that can be implemented in C++ (no Lua, that is).

**Comment by impaktor** [comment]
@salborrelli No worries. I think we're all swamped right now. But if you're curious: what I had in mind is an old one, and pure C++ restructure: separate ship object and player object: #38. 

(This would then pave the way for a future feature of player owning many ships (maybe in a garage somewhere).)

**Comment by fluffyfreak** [comment]
I'll get it uploaded asap, just been busy myself :)

**Comment by fluffyfreak** [comment]
Done.

**Comment by salborrelli** [comment]
> No worries. I think we're all swamped right now. But if you're curious: what I had in mind is an old one, and pure C++ restructure: separate ship object and player object: #38.

Seems interesting ... I'll take a look at #38 as soon as I have some time.

**Pull request merged**
