### PR TITLE
PiGui Station Lobby view

### LINKED ISSUE #4545: Incorrect hyperspace range shown in comm screen
### Observed behaviour
2019-02-23-095424_1366x768_scrot
2019-02-23-095513_1366x768_scrot

Hyperspace range is shown as way too much in this screen. The sector map, however, knows what the correct lightyear range is and will say INSUFFICIENT_FUEL if a star system is too far away.

The number displayed decreases when I buy more hyperdrive fuel.

### Expected behaviour
Comms screen shows actual lightyear range, which increases when I add more fuel.

### Steps to reproduce
1. Git clone pioneer, checkout the commit hash mentioned below, compile Pioneer using the cmake method.
2. Open pioneer, start a new game as easy or intermediate
3. Open comms, observe the hyperspace range shown that is way too high, is more than 0 when there's no fuel, and decreases when more fuel is added.

__My pioneer version (and OS):__
Pioneer commit [0072a09](https://github.com/pioneerspacesim/pioneer/commit/0072a0959c026bca3939a70014c84780eb4fc714) on Ubuntu 18.04.2 LTS x86_64

### PR DESCRIPTION
**Pull request by vakhoir**
Takes into account @mike-f1 hyperspace range fix from #4650
Was branched from #4624, so it also contains it's commits

EDIT: Will also close #4545

Screenshot from 2019-07-27 17-48-18

### CODE REVIEW

**Comment by robothauler** [comment]
After a quick check I noticed that the lobby window is empty when there is no hyperdrive. (Start at Barnard's Star)

**Comment by vakhoir** [comment]
Well, that was a stupid place to put a null check... that wasn't even necessary to begin with.

Thanks for testing! Fixed.

**Comment by vakhoir** [comment]
Hey @impaktor, I'm almost done with the Commodity Market as well. Should I keep opening PRs, or is it better to merge everything uder one?

**Comment by impaktor** [comment]
I dunno. Who's feeling up to reviewing this? @Web-eWorks, @ecraven ? what do you guys prefer?

At least, don't stop development, keep hacking away, on a new branch out of this PR's branch, I guess?, we can always cherry pick commits, or merge stuff, but if the Commodity market shares dependencies with thei PR, ideally we should test and merge this ASAP. 

I don't have any pioneer/internet time until next week, sorry.

**Comment by mike-f1** [comment]
@vakhoir , if you want/have time you could add the second line changed in #4650 and we save a one-line merge.

**Comment by vakhoir** [comment]
Done, I rebased your branch into mine

**Pull request closed without merging**
