### PR TITLE
Asteroid mining results controlled by lua

### PR DESCRIPTION
**Pull request by joonicks**
this code breaks out to lua the logic that detemines what you get when you blast away at an asteroid with a mining laser

original code spawned water, this code spawns coal ore instead

this is the bare code, my startup idea was to make a small chance of something rare spawning, like "strange crystal formation" which you could turn in somewhere for a reward, however if that should be integrated into the game or somehow split out as a module, I dont know.

also the name "SpawnMiningContainer" might be debated...though it does spawn a container with the returnvalue commodity.

### CODE REVIEW

**Comment by joonicks** [comment]
screenshot-20180110-184301

**Comment by fluffyfreak** [comment]
I'm a little confused by the statement 

> original code spawned water, this code spawns coal ore instead

Does that apply for all asteroids?
Looking at the code it looks like it should behave the same as the original but migrated to Lua.

**Comment by joonicks** [comment]
this code runs when any mining blast hits any asteroid. the lua returns the commodity to place in the container that is created.

**Comment by fluffyfreak** [comment]
Ok thanks, just wanted to check.

**Pull request merged**
