### PR TITLE
Disable Continue button if no saved game to load.

### LINKED ISSUE #3727: Cryptic error message when attempting to continue game when game has never been played
How to repdroduce:

* Start Pioneer the first time
* Click on “Continue game”
* You see a cryptic error message complaining about a missing save file called “_exit”

I suggest to just disable or remove the “Continue game” button if _exit is not there.

### PR DESCRIPTION
**Pull request by fluffyfreak**
Add method to test if a save game file exists for loading. Use it in the main menu.

Should fix #3727

### CODE REVIEW

**Comment by impaktor** [comment]
I just looked at the code for less than 2 seconds, so I assume I'm wrong, but since this whole "issue" is of nitpicking character, what happens if the player has auto-save, then disables auto-save before the _exit save is created?

Will not the continue button be disabled, even though there are autosaved states, jiust not the _exit one?

**Comment by fluffyfreak** [comment]
Yes it will but the continue doesn't load just any autosave, only the `_exit` autosave, so the point is moot.

**Comment by walterar** [comment]
Is this the inverse of K.I.S.S?

**Comment by fluffyfreak** [comment]
Keeping something simple for the player is sometimes not as clean as keeping it simple in the code but worth doing anyway.

**Pull request merged**
