### PR TITLE
Close default ctors and use a Ctor for load

### PR DESCRIPTION
**Pull request by mike-f1**
Most controversial point could be removing "UpdateLuaStats" from Ship loading function
to Body::FromJson, but Body is used as a factory so is (IMO) a minor design issue.

Minor changes:
* Projectile and Beam did not use "age" when load
* there where too many includes in ShipCockpit

I left default ctor in Body (and so ModelBody and DynamicBody)

### CODE REVIEW

**Comment by impaktor** [comment]
You are using the clang format script to check your code right?

**Comment by mike-f1** [comment]
I used git-clang-format after the whole thing and it told me it was all right,
now I know something went wrong...

Probably I should have also read docs before committing as told in your wiki but
may I ask where I can find `pre-commit-hook.sh`, could you put a link to it?

**Comment by impaktor** [comment]
> may I ask where I can find pre-commit-hook.sh, could you put a link to it?

I assume that's an error in the [wiki](https://pioneerwiki.com/wiki/Coding_Conventions), try using the clang-format.sh file?

If you get it working, you're welcome to edit the wiki. I haven't set it up myself yet.

**Comment by mike-f1** [comment]
Ok, no error on wiki: it seems I already have 'that' hook...

Side notes:

- I don't know if this is deliberate or not but, at least on my pc (Ubuntu), the compilation process overwrite `pioneer` in main folder, which is a script file.
- I found this [link](https://stackoverflow.com/questions/43974371/run-git-clang-format-on-series-of-git-commits) but I'm not able to get it going... It may worth a try

**Comment by impaktor** [comment]
Ideally, that reformating commit should be squashed into the rest of the commits.

As for code itself, I can't review that, its best done by some more c++ savy person. But this is just code clean up, as I understand it?

**Comment by mike-f1** [comment]
> Ideally, that reformating commit should be squashed into the rest of the commits.

Well, I don't think it's the best: if I do like that, you will end having code changes mixed with
style changes... Anyway, if you want, I could squash as you suggest.

> But this is just code clean up, as I understand it?

Yes: topics are in initial post. But, obviously, some bug may slip in...

**Comment by fluffyfreak** [comment]
This is really good. Tested it out and am merging now.

**Comment by mike-f1** [comment]
**A little explanation on some topics, so it is write and should last** 

>  removing "UpdateLuaStats" from Ship loading

It seems you cannot change the type of an object pushed on LVM,
which happens when you call `LuaObject<Type>::CallMethod` in that
method.

So you could think then to use a `dynamic_cast` but it could trigger UB
because it is used in a ctor (and it is time expensive).
A viable solution could be to use a RTTI system, but the one already
in place ( `Object()`: with their `GetType()` & `IsType()` ) don't works because
when you call these functions in a virtual method, they return the object
type of executed code. And it could be its **parent type** or **grand parent type**...

This is, in my limited experience, an unusual way to perform RTTI... it could
be changed to a common paradigma so it will take less to familiarize with
this code.

Howeve, comment on code is already presents, although "generic": the issue could
be better explained...

> Ideally, that reformating commit should be squashed into the rest of the commits.

The reason I did it that way is because I can't get [this](https://stackoverflow.com/questions/43974371/run-git-clang-format-on-series-of-git-commits) work.
So there's three solutions: or I squash last commit, and reviewer will complain about unreadability
of last commit; or reviewer will squash it _after_ review; or let merge "style" commits.

Definitely, if someone can get the linked solution to work, it should be mentioned in wiki.

**Comment by impaktor** [comment]
> So there's three solutions: or I squash last commit, and reviewer will complain about unreadability
of last commit; or reviewer will squash it after review; or let merge "style" commits.

Yes, after review the whole thing could be squashed before merged.

> Definitely, if someone can get the linked solution to work, it should be mentioned in wiki

The "propper way" is to have the commits right from the start, which one can get by having git run the clang-format as a hook for each commit, as described here: https://pioneerwiki.com/wiki/Coding_Conventions#Code_Formatting

(Note, I haven't tried it myself yet, so feel free to add example to wiki of how you do/did it, once you do it).

Thanks for the PR and code. I've been told pioneer compiles a lot faster now (I haven't benchmarked it myself).

**Comment by mike-f1** [comment]
> The "proper way" is to have the commits right from the start

Well, I didn't realize the 'hook' can do the job for each commit (although I
have some reserve on running it each commit), sorry.
But then there's something wrong.
Indeed, on my laptop:
```
$ ls
aclocal.m4           CMakeLists.txt  install-sh       pioneer
application-icon     compile         libpioneerLib.a  pioneer.iss.cmakein
appveyor.yml         COMPILING.txt   licenses         pioneer.rc.cmakein
AUTHORS.txt          config.guess    Makefile         Quickstart.txt
autoformat           config.log      Makefile.am      README.md
autom4te.cache       config.status   Makefile.common  SAVEBUMP.txt
bootstrap            config.sub      Makefile.in      savegamedump
buildopts.h          configure       metadata         scripts
buildopts.h.cmakein  configure.ac    missing          src
Changelog.txt        contrib         modelcompiler    test-driver
CI                   data            Modelviewer.txt  win32
CMakeCache.txt       debian          nd
CMakeFiles           depcomp         nix
cmake_install.cmake  doxygen         osx
```
But
```
$ cp scripts/pre-commit-hook.sh .git/hooks/pre-commit-hook
cp: cannot stat 'scripts/pre-commit-hook.sh': No such file or directory
```
Because in that folder I have
```
$ ls scripts/
build-osx.sh                  move_translation.py  scan_enums.py
build-travis.sh               nightly-build.pl     ShipPlanner015.py
canonicalise_translations.py  parse_gliese3.py     sketchfab.json
clang-format.sh               parse_hygxyz.py      update-translations.sh
clean_lang_data.py            Pioneer.cppcheck     wiki_ship_stat_parser.py
galgen_verify.sh              prep-changelog.pl

```
And note that:
```
$ git log --oneline | head -5
9fb03a6be Merge branch 'better-intro-info' close #4534
2ab104d1e Intro: Font size of ship name -> 24, show only if fully zoomed.
47892a524 auto-commit: translation updates
605ae1c97 auto-commit: translation updates
6dced3abb Update Changelog.txt
```

**Comment by impaktor** [comment]
scripts/pre-commit-hook.sh was merged in #4429 but I don't see it now, and I don't see (easily) why it's not there now?
ping @Web-eWorks

**Comment by Web-eWorks** [comment]
Ah, I forgot to update the wiki when that PR got merged. The hook is now `scripts/clang-format.sh`, and `autoformat` in the main dir runs clang-format on your changes and presents you the list of changes as well as a option to automatically apply them.

**WARNING**: clang-format 7.0.0 misidentifies certain header files as Objective-C, giving an error and resulting in null output. This will cause the affected files to be destroyed if you automatically apply the clang-format changes. I'm working on a fix now and should have a PR up in the next few days.

**Comment by Web-eWorks** [comment]
@impaktor the hooks got changed around in #4516.

**Comment by Web-eWorks** [comment]
Wiki is now updated, and the clang-format fix will be coming in #4539.

**Comment by mike-f1** [comment]
> Wiki is now updated, and the clang-format fix will be coming in #4539.

Great work!

**Pull request merged**
