### PR TITLE
Optimise route rendering

### PR DESCRIPTION
**Pull request by fluffyfreak**
Build all of the lines into a single buffer once, render as necessary and offset using the transform.

Resolves part of #5030 rendering

- https://github.com/pioneerspacesim/pioneer/blob/b5e21686269c7efcadcc2301169147e6f7ca04e7/src/SectorView.cpp#L751 this needs some kind of spacial bucketting!
- Added a sector selection optimisation to avoid generating sectors we then discard `Info: SectorView::AutoRoute, nodes to search = 5253, earlied out sector distance from line: 109870 times.`
- Avoided a bunch of sqrt operations by using the square distance.
- Tried to reserve some of the vectors and other stl structures.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
I'm thinking that the unvisited possible systems is a column/capsule/hot-dog shape thorugh space, so a simple spatial partitioning scheme would just be distance from the origin along central axis of that. 

Starting at zero at the origin bucket and incrementing by whatever the distance metric used. Each node would have the index of the bucket they're in, and they'd only need to consider their own bucket and bucket+1 for systems.

So for each iteration it could add to the unvisited list it's own bucket & bucket+1's sectors, runs the algorithm, and repeats 🤔
I don't think it's that simple because it's always going by system rather than sector, but something along those lines.
Maybe it adds to the unvisited list everytime it passes into a new bucket? 🤷‍♂️ anyway, something like that should reduce it by a few billion iterations to consider at each step.

**Comment by impaktor** [comment]
```
<sturnclaw> fluffyfreak: here's a simpler idea: instead of using a
minimum-cube of sectors in the broadphase, use the Bresenham line algorithm
to generate the sectors in-order along the start->target line (probably an
antialiased variant of Bresenham to get the fuzzy cylinder). Don't do any
line testing, just push the systems onto the vector. Then when you're doing
the narrowphase, keep track of the current < i < i+n}, where n is some number
(e.g. 24) that's the "reasonable upper bound" of the number of systems in the
number of sectors selected in the "width" of the broadphase [03:29:31] that
also advances to the target (e.g. with a dot product) but you can "jump"
through the list of systems that way and process logN on average the same
time complexity and also fit in O(N) space complexity
```

**Comment by fluffyfreak** [comment]
A quick look at Bresenham or Wu lines didn't make it much simpler when you have to have a variable thickness to the volume of the "line" that you want to calculate. Also it wasn't where the cost was, evaluating all of the sectors takes no time, but generating them does so I eliminated most of that.

It can still be improved with a simple incremental step perhaps 🤔but that's not where the cost is now, the narrow phase is bewilderingly expensive.

**Comment by fluffyfreak** [comment]
@Web-eWorks & @The-EG I'm making this into a 2 part piece, this part that does route rendering, and some other minor broadphase optimisations. However it does not touch the narrow phase at all.

Then either someone else can tackle the narrow phase, since there are some good ideas going around, or I will eventually get too it, but my time is limited so I don't want to delay getting in what I've done so far.

**Review by Web-eWorks — APPROVED** [review]
Only nitpick I have is that `m_setupRouteLines` is not quite as descriptive as I'd hope (e.g. `m_rebuildRouteLines`), but that's miniscule compared to the rest of the PR. Thanks!

**Pull request merged**
