### PR TITLE
Remove the rings from Venus and Ariel

### LINKED ISSUE #4652: Venus (ringless) has rings in pioneer
Venus is a ringless planet. It has rings in the game though.
Pioneer version: git master d72e4e9dc9dbd1f48109419d36ca322ebc7ec2d2

venus

### PR DESCRIPTION
**Pull request by fluffyfreak**
Fixes #4652 by marking the them as not having rings.
I checked all of the other bodies for rings, these were the only ones

### CODE REVIEW

**Comment by impaktor** [comment]
> I checked all of the other bodies for rings,

Probably stupid question, but you mean in the code, right? So with this PR, all bodies have explicit true/false on rings? If so, merge when ready.

**Comment by fluffyfreak** [comment]
Nope this just changes the custom system definintion for Sol to prevent Venus & Ariel from having rings explicitly. No code changes.

**Comment by impaktor** [comment]
So next time the seed or random number generator changes, any planet in Sol that doesn't have explicitly defined ring state, might get rings?

**Comment by mike-f1** [comment]
>might get rings?

[...probably? :smile:](https://en.wikipedia.org/wiki/Murphy%27s_law)

**Comment by impaktor** [comment]
Just to be clear, when I said "code" above, I meant "Sol custom system script", and I think a good fix would be to explicity set rings = false for all planets except Saturn, I guess. No change in C++ for this.

**Pull request merged**
