### PR TITLE
Add button to Settings menus so user can open their Pioneer folder.

### PR DESCRIPTION
**Pull request by fluffyfreak**
After numerous situations where the user cannot find their `Pioneer` folder with `config.ini`, `output.txt` and `opengl.txt` files in it I realised that of course we already have that information.

This adds a button to the settings screen that will ask the system to open the folder directly so they do not have to search for it.

I've only implemented the Windows call necessary as that's all I have access too right now.

### CODE REVIEW

**Comment by laarmen** [comment]
That's a really good idea!

**Comment by impaktor** [comment]
I assume you're thinking of #3779, where in the first answer the full description how to find the config file, and solve the problem is given, assuming they can find our wiki without us providing the link.

Turned out 11 more posts were needed to reach there.

So, yes, this is probably needed.

Apparently, I'm in a bad mood today.

**Comment by fluffyfreak** [comment]
Not just of #3779 but yes it's what inspired me finally :)

Also now that's it there I'm finding it quite useful!

**Comment by fluffyfreak** [comment]
@laarmen / @impaktor either of you guys want to try implementing a generic Linux version?

**Comment by laarmen** [comment]
Note to future self: xdg-open with inode as mime type should do the trick.

**Comment by laarmen** [comment]
To be honest, I'm not entirely sure it would be useful on Linux. The platform fragmentation will probably make the code not very robust/clean, and our users tend to compile from source, which means they probably have the reflex to look for a $HOME/.pioneer dir.

**Comment by fluffyfreak** [comment]
More for completeness then, Windows will have it and OSX should be pretty easy too.
Is there no simple way of doing it for all Linux distros/WMs?

**Comment by johnbartholomew** [comment]
Drive-by comment:
There's much more variation in how Linux users examine and navigate the file system than on Windows. There might also be more variation in the text editors that would be used to edit config.ini.

But if you just want something for the button to do on Linux, perhaps it could just show a dialog/message box that gives the path to the config directory. (For a message box you could show one in-game, or use SDL_ShowMessageBox or SDL_ShowSimpleMessageBox)

**Comment by laarmen** [comment]
Eh. On my netbook (which actually runs Pioneer, albeit painstakingly slow), I don't have any way to open a directory: I don't have any file explorer installed.

**Comment by fluffyfreak** [comment]
@johnbartholomew thanks :) that's a good idea actually.

**Comment by fluffyfreak** [comment]
Added @johnbartholomew suggestion using a simple message box.
Will merge this once it's passed the check unless there's objections?

**Pull request merged**
