### PR TITLE
Fix installed directory structure on Windows

### PR DESCRIPTION
**Pull request by Web-eWorks**
During the last major change to CMake I accidentally broke the install structure on Windows. This PR resolves that and should make the installation behavior on Windows systems more robust and easier to understand.

I've also included a potential fix for MSVC doing strange things with unicode character escape sequences in C string literals by explicitly specifying that we want the UTF-8 encoding of the unicode character.

CC @nozmajner @pcercuei to give this a test on Windows if able.

### CODE REVIEW

**Comment by pcercuei** [comment]
What I see if that you have a install() in the top CMake script, why isn't it in the cmake/InstallPioneer.cmake, below the spot where CMAKE_INSTALL_BINDIR is overriden?

**Comment by nozmajner** [comment]
@Web-eWorks 
The binaries are now put in their proper place, but the data is in a pioneer directory:
image
I've tried this artifact: https://github.com/pioneerspacesim/pioneer/actions/runs/7293314137

**Comment by Web-eWorks** [comment]
That should also be fixed now.

**Comment by nozmajner** [comment]
Confirmed, it works properly now.

**Pull request merged**
