### PR TITLE
Translation for #3549

### PR DESCRIPTION
**Pull request by radius75**

### CODE REVIEW

**Comment by impaktor** [comment]
Looks fine to me.

Ideally, we need the transifex magic of @robn (or @johnbartholomew?) to move translated string when this is merged, to not need re-transltion.

**Comment by fluffyfreak** [comment]
@impaktor Does this mean we're waiting on @robn to do something or do you mean in future we need to do it another way?

**Comment by impaktor** [comment]
> @impaktor Does this mean we're waiting on @robn to do something 

I believe so, yes. Since this moves already translated strings from core to ui-core.

**Comment by johnbartholomew** [comment]
I'm merging this manually now.

**Comment by johnbartholomew** [comment]
Merged, and moved translations pushed to Transifex.

**Pull request closed without merging**
