### PR TITLE
no radar in hyperspace

### PR DESCRIPTION
**Pull request by joonicks**
very simple patch

### CODE REVIEW

**Comment by impaktor** [comment]
@nozmajner thoughts?

**Comment by nozmajner** [comment]
Can't check it right now. Is it hiding the radars during hyperjump? Since we already hide the HUD, it would make sense to hide it as well.

**Comment by impaktor** [comment]
@nozmajner yeah, check the code, I suspect you can render its effect in the brain.

**Comment by nozmajner** [comment]
:D

**Pull request merged**
