### PR TITLE
Fix for #4095

### PR DESCRIPTION
**Pull request by radcapricorn**
This needs review and testing, I'm not 100% sure this wouldn't break something else.

### CODE REVIEW

**Comment by radcapricorn** [comment]
On a second look, this does contradict #4002.

**Comment by jaj22** [comment]
#4002 was a bad fix. If GetAccelUp returns negative then there's an error elsewhere. Up thrusters are supposed to thrust upwards.

If you need to protect the autopilot code against thrust-direction errors then you should do it at a higher level. Preferably with an assert, as it's a nonsense result.

**Comment by radcapricorn** [comment]
The issue isn't that `GetAccelUp()` returns negative, it's that `body->GetMass()` returns 0, making `alt` on line 1112 become 0, causing division by zero on line `1096`, which makes m_vel a NaN, which eventually leads to `sqrt(-NaN)` call on line 664, triggering a domain error.

**Comment by jaj22** [comment]
GetAccelUp() returning negative was the original reason for #4002, I think. As you've identified, the original version of the code worked fine for mass 0.

On the other hand, I'm not sure why there are mass 0 objects. That seems like another higher-level bug.

**Comment by fluffyfreak** [comment]
by fixing it this way we get back the other bug #3996. #4002 was always just a patch-it-and-hope fix, so does anyone know how to actually fix it?

**Comment by jaj22** [comment]
Ok, this is weirder than expected. Turns out that Deimos has a massively negative mass. I traced this to `l_fixed_new` in `LuaFixed.cpp` using luaL_checkinteger for >32bit integer values. In context, this has a straightforward workaround:

Old code:
`int num = luaL_checkinteger(L, 1);`
`int denom = luaL_checkinteger(L, 2);`

Fixed code:
`Sint64 num = (Sint64)luaL_checknumber(L, 1);`
`Sint64 denom = (Sint64)luaL_checknumber(L, 2);`

I've stepped through and this works correctly for every call. However, a side effect is that the terrain generator now throws a height assertion on the Earth start. I'm guessing that this is because an asteroid terrain generator function doesn't work correctly for the now-correct mass values. I'm having trouble getting a valid breakpoint due to terrain threading, so I'm going to bounce this back for the moment.

**Comment by impaktor** [comment]
That's great finding. I wonder if @fluffyfreak, with that fix applied, can detect the weirdness in the terrain generator (when you have time).

**Comment by jaj22** [comment]
Ok, some followup. The Terrain assert is likely to be partially caused by this calculation in Terrain.cpp:

`m_maxHeightInMeters = std::max(100.0, (9000.0*rad*rad*(m_volcanic+0.5)) / (body->GetMass() * 6.64e-12));`
`if (!is_finite(m_maxHeightInMeters)) m_maxHeightInMeters = rad * 0.5;`

I believe this is a physical calculation intended to determine how spherical planets should be. For planets with small but non-zero mass, it blows up so that m_maxHeightInMetres is thousands of times greater than the planet radius. The terrain generators generally assume that m_maxHeightInMetres is somewhat related to the planet radius, and they're not exactly solid at the best of times. Capping m_maxHeightInMetres to the planet radius works around this problem. I didn't check whether it ended up with reasonable-looking asteroid terrains.

A related glitch I ran into is that asteroid masses are mis-specified or mis-adjusted. The SystemBody constructor for custom bodies (StarSystemGenerator.cpp, line 497) transfers the mass with the following code:

`kid->m_mass = csbody->mass;             // straight 32.32 fixed-to-fixed copy`
`if (kid->GetType() == SystemBody::TYPE_PLANET_ASTEROID) kid->m_mass /= 100000;`

Whoever wrote the masses for Sol apparently did not know about this line, as all the ASTEROID bodies are specified in earth masses. However, this adjustment is currently pointless, as the lua specification is just as (in)accurate as the SystemBody mass, given the Sint64 fix above.

Note that mass 0 is still a valid case due to the lack of accuracy in 32.32 fixed point values, but I think it's handled correctly everywhere except #4002.

**Comment by jaj22** [comment]
More glitches. Ignoring the asteroid mass miscorrection, the masses of Phobos and Deimos appear to be incorrectly specified in the lua by a factor of ~100:

Real Phobos: 1.775e-9
00_Sol Phobos: 1.875e-11
Real Deimos: 2.47e-10
00_Sol Deimos: 2.5e-12

This seems to also be true of Jupiter's asteroids. Not sure why. Too consistent to be accidental. Who usually deals with this stuff?

**Comment by nozmajner** [comment]
I did some of the Jupiter moons, and I had a hard time figuring out exponent. Not the Mars moons though.

**Comment by jaj22** [comment]
OK, fixed a bunch of moon masses. Pasted for reference:

// Mars moons. Deimos has the smallest representable non-zero mass
	CustomSystemBody:new('Phobos', 'PLANET_ASTEROID')
		:radius(f(21,10000))
		:mass(f(1775,1000000000000)) -- 10.6e15 kg = 1.775e-9 EM
	CustomSystemBody:new('Deimos', 'PLANET_ASTEROID')
		:radius(f(12,10000))
		:mass(f(247,1000000000000)) -- 1.48e15 kg = 2.47e-10 EM - comes out as 1

// Jupiter inner moons, mostly tiny.
	CustomSystemBody:new('Metis', 'PLANET_ASTEROID')
		:radius(f(337,100000))
		:mass(f(633,100000000000)) -- 3.6e16 kg = 6.33e-9 EM
	CustomSystemBody:new('Adrastea', 'PLANET_ASTEROID')
		:radius(f(338,100000))
		:mass(f(352,1000000000000)) -- 0.2e16 kg = 3.52e-10 EM
	CustomSystemBody:new('Amalthea', 'PLANET_ASTEROID')
		:radius(f(13,1000))
		:mass(f(348,1000000000)) -- 208e16 kg = 3.48e-7 EM
	CustomSystemBody:new('Thebe', 'PLANET_ASTEROID')
		:radius(f(773,100000))
		:mass(f(72,1000000000)) -- 43e16 kg = 7.2e-8 EM

// Jupiter outer moons.
	CustomSystemBody:new('Themisto', 'PLANET_ASTEROID')
		:radius(f(627,1000000))
		:mass(f(115,1000000000000)) -- 6.9e14 kg, 1.15e-10 EM - comes out as zero
	CustomSystemBody:new('Leda', 'PLANET_ASTEROID')
		:radius(f(156,100000))
		:mass(f(837,1000000000000)) -- 5e15 kg, 8.37e-10 EM
	CustomSystemBody:new('Himalia', 'PLANET_ASTEROID')
		:radius(f(1334,100000))
		:mass(f(1122,1000000000)) -- 670e16 kg, 1.122e-6 EM
	CustomSystemBody:new('Lysithea', 'PLANET_ASTEROID')
		:radius(f(282,100000))
		:mass(f(1055,100000000000)) -- 6.3e16 kg, 1.055e-8 EM
	CustomSystemBody:new('Elara', 'PLANET_ASTEROID')
		:radius(f(675,100000))
		:mass(f(1457,10000000000)) -- 87e16 kg, 1.457e-7 EM

// wat
	CustomSystemBody:new('Aega', 'PLANET_ASTEROID')
		:radius(f(313,1000000))
		:mass(f(1055,100000000000))

// Couple of Neptune moons. These correctly used the old asteroid adjustment
	CustomSystemBody:new('Proteus', 'PLANET_ASTEROID')
		:radius(f(310,10000)) 
		:mass(f(843,100000000)) -- 5035e16 kg, 8.43e-6 EM
	CustomSystemBody:new('Nereid', 'PLANET_ASTEROID')
		:radius(f(2668,100000))
		:mass(f(452,100000000)) -- 2700e16 kg, 4.52e-6 EM

**Comment by impaktor** [comment]
Merged fix discussed above. @radcapricorn no hard feelings I hope if we "stole" your PR, your debugging effors and insights were very valuable, and got the ball rolling really good. Thanks!

**Pull request closed without merging**
