### PR TITLE
Start moving station-view to PiGui

### PR DESCRIPTION
**Pull request by vakhoir**
Same deal as with the Info View (#4573). Set up the Station View so each tab can be worked on separately.
Also moved the info-view logic to a tab-view object that can be also used by the station-view.

### CODE REVIEW

**Comment by impaktor** [comment]
Nice!

What's the status on the ship-spinner? As I understood it, this was the main obsticle to moving the station screens to pigui?

Also, I imagine CrewRoster and Mission screens in info-view would be low hanging fruit to be ported to pigui?

**Comment by vakhoir** [comment]
I thought @Web-eWorks  was doing it?
If not I'm happy to take it on.

**Comment by fluffyfreak** [comment]
I was supposed to be doing it, there were diverging opinions on the best way to handle it so it got forgotten about.

If you're happy to do it @vakhoir then I'm happy for you to do it :D

**Comment by Web-eWorks** [comment]
@vakhoir I'm going to work on that today - between rescuing my rebase-borked branch, implementing #4590 and some personal stuff I haven't had time to properly tackle the ship info view. If all goes well I should be able to get that knocked out and ready for merge by Monday - Tuesday.

As a worst case I might have to badger you a bit @fluffyfreak for best practices with the rendering system's internals, but hopefully the code is reasonably self-documenting.

**Comment by Web-eWorks** [comment]
I think I've got it nailed down - there's a bit of a bug with trying to call `ModelSpinner()` related to the way LuaObject works, but otherwise it's working...

Screenshot from 2019-05-26 23-44-57

Or not? @fluffyfreak halp! I've suddenly contracted a case of the stupids and forgot to clear my texture and enable `GL_DEPTH_TEST` before drawing...

_(some furious scribbling later)_

Screenshot from 2019-05-26 23-54-57

Okay, I think I've actually got it this time. I'll clean it up and actually replace the old UI page while I'm waiting on #4576 to be merged.

**Comment by vakhoir** [comment]
Nice!

**Comment by fluffyfreak** [comment]
Nice work @Web-eWorks, are you going to see about merging it into this PR with @vakhoir ?

**Comment by Web-eWorks** [comment]
@fluffyfreak I think I'm going to run it as a separate PR to get merged before this one is - I'll likely use it as an excuse to convert the Ship Info screen to pigui _en-passant_.

I do want to poke your brain a bit about rendering architecture over on the forums when you get some free time - found some interesting resources regarding design.

**Comment by fluffyfreak** [comment]
Sure I'll check the forums and try to reply asap

**Comment by fluffyfreak** [comment]
@vakhoir is this ready for review as-is? Or do you have more to do in _this_ pull request?

**Comment by vakhoir** [comment]
This one is good to go. I think each specific view should be it's own PR.

**Pull request merged**
