### PR TITLE
Refactor Body inheritance tree to remove Object and CityOnPlanet

### LINKED ISSUE #22: Refactor Body inheritance tree to remove Object and CityOnPlanet
CityOnPlanet should not inherit from class Object. It makes it necessary to have special-case checks for rendering and collision detection. Instead it should be a seperate discrete class, with multiple instances attached to a planet/starport. The render and collision detection can be done as part of the planet draw.

Once thats gone, everything in the Object tree is also a Body, so Object and Body can be merged. Then there is no ambiguity - anything that inherits from Body is something that can exist in the world space.

### PR DESCRIPTION
**Pull request by Web-eWorks**
So yeah, #22 is what I consider low-hanging fruit to knock out in an hour now. I'm a bit in shock to be honest, this was significantly less painful than I thought it would be.

Fixes #22.

This basically turns Object into a simple non-inherited enum-namespace struct, removes CityOnPlanet from the inheritance tree and cleans up some spots that tested for it when they were never going to be passed a CityOnPlanet instance.

The usual bugtesting steps apply; fly around, crash into things, get into a shootout with the police, try a mission or twelve, and if it doesn't crash and you do die horribly then it's working as intended.

### CODE REVIEW

**Comment by impaktor** [comment]
Nice!

Ha, this must be the longest open issue that then gets fixed, as @robn opened it +9 years ago.

**Comment by robn** [comment]
Hah! Nice one :laughing:

**Comment by fluffyfreak** [comment]
Nice I'll try to get a look at it today/tonight 👍 

Also, Hi @robn 😀

**Review by fluffyfreak — APPROVED** [review]
Had a quick fly around, might be best to wait for more in depth testing from others with time to spare.
However code looks good (_as always_) and initial testing seems to work just fine 👍

**Comment by impaktor** [comment]
With that, I'd say: merge this sucker, and let players test it on master.

**Comment by Web-eWorks** [comment]
Will hold this open until json-commodities and input-frame-2.0 is merged so I can get some more testing. Shouldn't be more than a week, I think.

**Comment by Gliese852** [comment]
Do I understand correctly that the `Object` structure is used only by children of the `Body`?  does not its separate existence now seem strange? (for a person who does not know the background)

**Comment by Web-eWorks** [comment]
@Gliese852 now Object is just a struct that wraps an enum; there is no inheritance anymore. I've only left it alive because I didn't want to re-write every little thing that used `Object::STAR` or `Object::SHIP`.

**Comment by Gliese852** [comment]
I would completely remove the word `Object`, as it is essentially the same as Body, but confusing.  (I don't know how difficult it is)

**Comment by Web-eWorks** [comment]
@Gliese852 good point, I can probably rename it to BodyType or something like that. The entire Object system is going away eventually in favor of an ECS-based system, so I wanted to avoid as much code-churn as possible.

**Pull request merged**
