### PR TITLE
Mac compilation fix

### PR DESCRIPTION
**Pull request by jfacoustic**
Updated to compile latest version on Mac.  Also noted changes to compilation steps in the compiling.text

### CODE REVIEW

**Comment by impaktor** [comment]
This is great, thanks! :+1: 

A few small things though: it appears you've also changed the mode of some files. Specifically, many text files (e.g. "COMPILING.txt") has been set to be executable. This can easily be fixed by changing the mode back (e.g. `chmod a-x ...`), followed by `git add` on those files, and `git commit --amend` which will add those changes to your latest/previous commit (see wiki for more on this), and thus no longer be seen as changed/modified by your pull request. (I'd also investigate how/why your editor(?) changed the mode of the files).

@salborrelli could you please review this? Also, I see that `osx/install_ports.sh` is _not_ executable on our current master, so maybe that file actually should have executable mode as set by this pull request? 

@fluffyfreak just to introduce @jfacoustic, he wants to join pioneer (from a couple of time zones west of us), has a Mac, knows C++, and is studying computer science. (hope you don't mind me sharing that info here)

@jfacoustic Also, a minor point, I see that you made your changes directly on your master branch. Usually, one creates a separate branch for each feature, and then the pull request is made from that branch. This would then isolate the changes/features, which would allow you to easily switch to another branch if you want to implement/play around with something new wile this is in review.

(Technically, if you want to play around with something different (e.g. #3348), now while this is in review  you can still create a branch from your master, to keep these changes separate, but when time comes to create a pull request you might want to exclude your "Mac compilation fix"-commit from that branch, since it's a separate feature that belongs to this pull request)

**Comment by salborrelli** [comment]
@impaktor @fluffyfreak @jfacoustic Hi all, I have tested the PR and yes I confirm that the Xcode project builds without errors now, thank you Josh for resolving this (and saving me the hard task of finding some time for checking into it 😄 And I also agree about making the install_ports.sh file executable, an issue that this PR would resolve as well.

Regarding the permissions problem, yes it is quite strange: of course I can fix it easily but I think that this could be a good chance for Josh to experiment with branches and amends, so I will wait for him to fix the problem and update the PR. Let me know when the PR is ready for review (or if you need help of course), afterwards we can do a quick additional test and eventually merge it.

**Comment by jfacoustic** [comment]
@fluffyfreak Thanks for sharing.

**Comment by jfacoustic** [comment]
@salborrelli I am working on making the .sh executable.  It seems like all I have to do is delete the extension and chmod it.  Then I select terminal as the default program.  I'm unsure if this transfers to other computers; would you check it for me?

**Comment by jfacoustic** [comment]
@impaktor My editor doesn't show that those text files changed to executables.  I'm unsure what happened.  I'll play around with stuff though and try to figure out what happened.

**Comment by jfacoustic** [comment]
@impaktor Thanks for sharing with @fluffyfreak

**Comment by salborrelli** [comment]
@jfacoustic no need to remove the extension and neither to select a "default program" (which would only affect your local system anyway), simply issuing a chmod will do. Anyway I have pulled the latest version and can confirm that the "install_ports" file (formerly install_ports.sh) is now executable.

**Comment by jfacoustic** [comment]
@salborrelli Thanks.  If I didn't do that, Xcode kept opening it rather than terminal which was rather annoying.

**Comment by jfacoustic** [comment]
Sorry, I meant to pull from another branch.  Still trying to figure this out.

**Comment by impaktor** [comment]
Oh, there's a lot of confusion here at the moment.

For starters, the last commit "fixed fullscreen for mac" @808d7a8 should not be in this PR, as this deals with getting compilation running on mac, and the last commit should be in its own pull request.

The commit before that @e06419f shows the remnants of an unresolved merge conflict, and should be removed.

And wasn't `install_ports.sh` made executable by your first commit? I.e. you did not have to do anything with it (since this was one of the files that had mysteriously been set as executable)? I didn't follow why you removed the `.sh` part of the file name.

I think basically removing all commits except the first one would be the way to go, you probably want to be on IRC for that, as it's "advanced" git usage. 

@jfacoustic don't worry though, we've all walked the path of learning git/github, so I'll be happy to help you sort things out.

**Comment by impaktor** [comment]
@jfacoustic it's getting late here now, but if you have time tomorrow we'll sort this out then?

**Comment by walterar** [comment]
@jfacoustic  Linux no problem with the changes to src/graphics/WindowSDL.cpp

**Comment by impaktor** [comment]
@walterar great, thanks. I can test it later as well, if need be. 

I'm closing this, since the comits were a bit bundled up in the wrong way, (and also done from his master).  We're now tracking the mac-compile commits in #3759 and the Mac-fullscreen problem in #3762.

**Pull request closed without merging**
