### PR TITLE
Attack outlaws immediately

### PR DESCRIPTION
**Pull request by robothauler**
Attack outlaws immediately and show no mercy.

### CODE REVIEW

**Comment by impaktor** [comment]
So this makes the police patrol attack the player's ship not only if carrying contraband, but also if an outlaw?

I've always imagined that once a player is an outlaw, there will be a contract on your head, thus bounty hunters will be going after you.

**Comment by fluffyfreak** [comment]
How do you now land to pay off a fine if you've got on? Everywhere you go will just attack you before you can pay it.

**Comment by robothauler** [comment]
I think you are talking about the Station Police. The Police Patrol is only sparsely spawned and shouldn't be a problem here.

**Comment by fluffyfreak** [comment]
Ah ok then. Will merge in a few days so it doesn't mess up the August changelog :)

**Pull request merged**
