### PR TITLE
Improved UI resolution rescaling

### LINKED ISSUE #4545: Incorrect hyperspace range shown in comm screen
### Observed behaviour
2019-02-23-095424_1366x768_scrot
2019-02-23-095513_1366x768_scrot

Hyperspace range is shown as way too much in this screen. The sector map, however, knows what the correct lightyear range is and will say INSUFFICIENT_FUEL if a star system is too far away.

The number displayed decreases when I buy more hyperdrive fuel.

### Expected behaviour
Comms screen shows actual lightyear range, which increases when I add more fuel.

### Steps to reproduce
1. Git clone pioneer, checkout the commit hash mentioned below, compile Pioneer using the cmake method.
2. Open pioneer, start a new game as easy or intermediate
3. Open comms, observe the hyperspace range shown that is way too high, is more than 0 when there's no fuel, and decreases when more fuel is added.

__My pioneer version (and OS):__
Pioneer commit [0072a09](https://github.com/pioneerspacesim/pioneer/commit/0072a0959c026bca3939a70014c84780eb4fc714) on Ubuntu 18.04.2 LTS x86_64

### PR DESCRIPTION
**Pull request by vakhoir**
_EDIT by @impaktor_ [this](https://help.github.com/en/articles/closing-issues-using-keywords#closing-multiple-issues) closes #4624 closes #4651 closes #4654, fixes #4545

Like I mentioned in the previous pull request, I noticed the ui doesn't seem to rescale very well. We typically use code like this to scale to current resolutin:

`local mainButtonSize = Vector2(32,32) * (ui.screenHeight / 1200)`

It usually works well enough. but only within the same aspect ratio. Calculating these sizes has also been annoying, because the formula assumes 1920x1200 as the base resolution, and I usually work on 1600x900. So I wrote the `ui.rescaleUI = function(val, baseResolution, rescaleToScreenAspect)` function, which will automatically rescale any value, or all values in a table, using the relatively smaller dimension (so if the width changed more relative to the base resolution, it will use that). The `rescaleToScreenAspect` parameter works only for vectors, and if it's set it will use both dimensions (so a shape that is a square in 4:3 will become more rectangular in 16:9, and vice versa).

Other than rescaling I added some resolution-dependant rearrangements in the lobby.

So, without further ado, some comparisons:

**Station lobby - 1600x900 (my base resolution):**

1600x900_lobby

**Station lobby - 1152x864, old rescaling:**

1152x864_lobby

**Station lobby - 1280x960, new rescaling**

1280x960_rescale_lobby

**Station lobby - 800x600, old rescaling:**

800x600_lobby

**Station lobby - 800x600, new rescaling:**

800x600_rescale_lobby

**EquipmentMarket - 1600x900, old rescaling:**

1600x900_eq_market

(note I originally did not notice that with the sizes provided I cut off the "In Stock" column)
**EquipmentMarket - 1600x900, new rescaling:**

1600x900_rescale_eq_market

**EquipmentMarket - 800x600, old rescaling:**

800x600_eq_market

**EquipmentMarket - 800x600, new rescaling:**

800x600_rescale_eq_market

### CODE REVIEW

**Comment by mike-f1** [comment]
First of all: nice work, not only for this PR but also for the other one's (...so many I can't count :) ).
This thing of rescaling is a big improvement as first issues are already opened: the old UI has not this hard limit (IIRC), and iy can change scaling far better.
So centralizing all the calls to the same function is a good step in the right direction but I think that _The_ final solution is to change all functions in LuaPiGui.cpp to request a different kind of Vector specifically designed to be used for screen coordinates.

...As I said the above are a future topic, for now this will suffice.

Well done!

**Comment by impaktor** [comment]
Nice! And thanks for the many screenshots. Helps a lot to show the effect of the PR.

**Comment by impaktor** [comment]
I've been a bit absent (still am), but does anyone want to voice opinion on this, or any hinderence to merging?

**Comment by pcercuei** [comment]
I think it'd look better to have each fuel gauge below its set of buttons. There is quite a lot of vertical space available.

**Comment by fluffyfreak** [comment]
It looks good.
That doesn't look like font downsizing, it's a higher resolution so that font is proportionally scaled by the looked of it.

**Comment by pcercuei** [comment]
It is downsizing, if you look at the last two screenshots, they are both 800x600.

**Comment by fluffyfreak** [comment]
It looks good to me, although I admit that I do not play in 800x600... does anyone?

**Comment by Web-eWorks** [comment]
I'll review the Lua in a couple hours, otherwise I'm very happy with better rescaling!

**Comment by Web-eWorks** [comment]
Lua looks good to me! Only thing I'd comment on is that we might want to make `screenSize` an optional parameter defaulting to 1600x900 for `rescaleUI`, to establish a common base screen size.

**Comment by pcercuei** [comment]
If you do that, I won't contribute anymore, because I won't be able to run the game anymore :)

**Comment by Web-eWorks** [comment]
@pcercuei the idea is to specify a common 'base' resolution to develop for, and allow the game to handle resizing / scaling the UI at higher or lower resolutions (or different aspect ratios). I intend (and I'm sure @vakhoir intends as well) to make the game playable at any resolution you can think of.

**Comment by pcercuei** [comment]
Ah, ok.

**Comment by impaktor** [comment]
Sweet!

I've edited the first message, to auto-close all other PRs this is branchin off from, as I've understood it.

Will merge shortly.

**Comment by impaktor** [comment]
> Lua looks good to me! Only thing I'd comment on is that we might want to make screenSize an optional parameter (defaulting to e.g. 1600x900) for rescaleUI, to establish a common base screen size.

@Web-eWorks / @vakhoir shounds like a PR that would be merged fast ;), if it's something you'd like to have.

Sorry for the long delay on this barrage of PRs, but it's very nice to have these features in the game now! Let's see how many bugs we introduced now... (given the amount of code)

**Pull request merged**
