### PR TITLE
Skipjack Courier from OKB Kaluri

### PR DESCRIPTION
**Pull request by nozmajner**
A new ship coming up, courtesy of @BobTheTerrible.
A Medium Courier named Skipjack from OKB Kaluri. 
Has an ample capacity and a rather nice deltaV, but not as nimble as the Light Couriers. It can still sit on the small pads though!
But I let the man do the describing:

> "The Skipjack is a medium courier manufactured by OKB Kaluri.
> 
> The Kaluri design team's primary focus was that of operational reliability and
> survivability with every contingency considered to ensure the Skipjack's
> consignment arrives at its destination safely and on time.
> 
> This philosophy is observed throughout the Skipjack's design from triply
> redundant avionics and life support systems to paired thrusters minimising the
> impact of critical failures and the subsequent need for mid-flight EVA repairs.
> While all but the most determined pirates are kept at bay by strong shielding
> and respectable offensive capabilities.
> 
> The Skipjack's redundancy, however, comes at the price of maintenance with
> servicing and overhaul costs way above other ships in its class.
> Although most larger corporations and operators of Skipjacks keep their fleets
> in good condition, smaller operators and sole traders often neglect their
> Skipjack's redundant systems allowing them to fall into disrepair - something a
> would-be buyer aught to be wary of."

modelviewer-20200428-224652
modelviewer-20200428-224704
modelviewer-20200428-224708
modelviewer-20200428-224712
modelviewer-20200428-224712

### CODE REVIEW

**Comment by impaktor** [comment]
Since we seem to be leaning to adding [git-lfs](https://github.com/github/git-lfs#getting-started) with #4554, we might as well make the switch now, and move models and music into it now, and make proper adjustments for this PR to put it in LFS. Thus, I'd like to probe what others think of making this move now, with this ship/PR?

It is a bit of work (I'm reading up on it now), I assume various packages would need upgrading (flatpack, arch/aur, debian, fedora) and travis/appveyor, and COMPILING.txt.

**Comment by Web-eWorks** [comment]
The downside to Git LFS is that we either need to host it ourselves somewhere or pay Github for it - Github provides 1GB of free storage (and 1GB of bandwidth per month) while we have almost 900MB of file history in the repo:

```
*.dds 	352 MB	  257/257 files(s)	100%
*.ogg 	276 MB	  158/158 files(s)	100%
*.png 	204 MB	2651/2651 files(s)	100%
*.dae 	162 MB	  211/211 files(s)	100%
```

Added to that, each version of a file in Git LFS history counts for storage size - so if we make changes to a DDS file and re-push, we're now using twice as much storage for that file.

**Comment by impaktor** [comment]
> I was just playing with it in the modelviewer and notice that the maneuvering thrusters aren't animating. Someone who knows how those work might want to take a look at that.

https://pioneerspacesim.net/forum/viewtopic.php?p=6383#p6383

**Comment by nozmajner** [comment]
Wait with merging this please, @BobTheTerrible and @Keeper were doing some texture work.

**Comment by nozmajner** [comment]
@BobTheTerrible, @Keeper I've added your patterns. 
@impaktor This should be good to merge.

**Comment by impaktor** [comment]
Cool! Then I suggest some grace period where I [explore LFS](https://pioneerspacesim.net/forum/viewtopic.php?f=4&t=639), and if that works out, this will be moved into LFS instead into this git repo, so I suggest to hold on merging this a while, while I investigate our options.

**Comment by BobTheTerrible** [comment]
Woo! Great news, many thanks!! :-D

**Comment by Web-eWorks** [comment]
Slightly tweaked stats to reduce that new ship feel, slightly improved it's handling overall and improved in-atmosphere performance a bit as well. It's roughly stable at mach 2 (definitely have problems with our atmospheric flight model but that's for another day...) and I didn't touch the drag coefficients, so it still flies like a sphere.

In sum, I'm good to merge this in. We're not going to go the LFS route unless we're totally migrating to Gitlab or a Gitea instance, so there's no need to delay further.

**Pull request merged**
