### PR TITLE
Scanner / Equipment Toggle

### PR DESCRIPTION
**Pull request by salborrelli**
1) the Scanner / Equipment two-buttons group in ship panel has been replaced with a single button which switches between the Scanner and Equipment views.
2) the Mac OS X build project for xCode has been updated to work with the latest Git version

### CODE REVIEW

**Comment by impaktor** [comment]
Sweet.

@nozmajner probably want to see the end result (is placement OK?):
screenshot-20151210-125253

I think you should also remove the two, now unused,  old highlighted versions of these pngs.

**Comment by nozmajner** [comment]
Looks good, but I'll make a replacement icon which shows more clearly that it's a toggle between stuff.
https://www.dropbox.com/s/5n5svndxu2wmys6/scannertoggle.zip?dl=0
multifunc_scanner_on
multifunc_scanner

Hmm. Would it be a lot of hassle to switch the position of this toggle and the Set speed/Control mode text? So the text doesn't hang over those two little icons, and more readable.
Just in case it's possible, I've a couple of smaller icons, so it's similar with the other two little icons.

**Comment by impaktor** [comment]
I'm always confused by these two-state icons: so the first one is when the scanner is active? And
the second one if for equipment active?

I guess the "highlighted" version should be the special case, i.e. the equipment version? Hmm, but you can sell your scanner. Oh dear. I feel like Winnie-the-Pooh.

**Comment by nozmajner** [comment]
I see what you mean. Here, get some honey. ;P
I went with the other icons in this case: the lighter little radar dish+highlight is for the scanner, and the dark button-light wrench-rocket is for the equipment. What if the icon/button isn't even shown when you don't have a scanner? Since you don't have anything to switch to anyway.

**Comment by impaktor** [comment]
Honey? Like: :honey_pot: 

@salborrelli when you add the icons, have them in their own commit as:

    git add <path to icons>
    git commit --author=nozmajner -m "my commit message"

alas, I forgot it today, when mergin another commit.

**Comment by salborrelli** [comment]
@impaktor I have updated the language strings as you suggested.

@nozmajner I don't see any big issue in switching the position of the scanner / equipment toggle with the labels underneath. Please send me the smaller icons when ready.

**Comment by nozmajner** [comment]
@salborrelli  Neat. I've already included them in the zip, you just need to rename them, removing the small suffix.

**Comment by fluffyfreak** [comment]
@salborrelli when you'd added/changed the icons I'm happy to see this merged.

**Comment by salborrelli** [comment]
Guys I'll be traveling around Europe for business next week, I don't think I'll have time to address the icons request 'till Thursday.

If you are in a hurry to merge this pull request then feel free to close it now. I will add the latest things about switching the icons / labels and integrating the smaller icons to a new PR.

**Comment by fluffyfreak** [comment]
@salborrelli there's no rush, there's no pressure on Pioneer (it's in Space!) to get things done by a arbitrary deadline. Either one of us can add the icons if we get time to merge this PR, or it can wait until you have time :)

**Comment by salborrelli** [comment]
Hi guys,
 I have updated the Scanner / Equipment icons and also switched the button position with that of the navigation status label.

Can  you please review and let me know if any further adjustment is necessary before merging?

**Comment by walterar** [comment]
:+1:  :+1:

**Comment by impaktor** [comment]
For @nozmajner 
screenshot-20151218-103008
screenshot-20151218-103014

**Comment by nozmajner** [comment]
I think it looks good.

**Comment by impaktor** [comment]
Thanks for the fix. Now I don't have any more small fixes for you to play around with that I can think of right now (#3103 perhaps?), but there's plenty of medium to big things to do if you want to contribute more (both c++ and/or lua code), or perhaps you have ideas of your own for pioneer?

If you want, you can look around here on the issue tracker for various things to play with, and the [wiki](http://pioneerwiki.com/wiki/How_you_can_contribute), or come by IRC or the dev-forum if you have ideas, questions, or just want to talk.

When #3564 is merged, I suspect we'll need your help to update the xcode stuff again.

**Comment by salborrelli** [comment]
@impaktor I have no big plans for Pioneer yet so I think I'll browse through the issues tracker and the forums in search of ideas :-) Seriously, I'm basically still in the "learning" phase, meaning I'm using small issues as an excuse for digging into the code and analyse the basic structure. But the project is very interesting, I enjoy both playing with the code and the game itself when I have some time.

Is there any technical documentation around (e.g. a functional / technical spec, technical notes etc.) that you could share for speeding up the analysis of the system architecture?

And I will definitely take a look at #3103 before switching to the issues tracker.

**Comment by impaktor** [comment]
@salborrelli Actually, that's a very issue, hardly noticable, so I don't know how worth your time it is. #3565 is even smaller, and should be very simple to fix. Low hanging fruit, as we call it. Do what ever you feel up to doing.

**Comment by salborrelli** [comment]
@impaktor @nozmajner @fluffyfreak One thing that I've found quite annoying during game play is that sometimes the effect of pressing some "standard" keys is not what you would expect, or at least does not match the normal user experience provided by almost all common environments.

For example, while looking at the BBS I frequently find myself clicking the ESC key, expecting to escape to the previous screen (the Station View), but alas I find myself in the Settings Views instead, with no immediate way to go back to the BBS. Similarly, I have tried to use the Up / Down arrow key to scroll up / down the list of missions, with no luck: looks like the only way to scroll the list is to use the rightside slider.

An interesting idea (for me at least :-) would be to do a general review of the application in order to make the user experience someway closer to what normal users expect from their interaction with common operating systems, for example:

1) the ESC key should bring users to the previous "main" view, at least while in contexts where we expect that
2) the Down / Up keys should allow users to scroll down / up a page in all cases where a scrollbar is available
3) etc ...

What do you think? Should I open a discussion in the developers forum?

**Comment by nozmajner** [comment]
Yeah, a thread on the dev forum could be good.

**Comment by salborrelli** [comment]
>Yeah, a thread on the dev forum could be good.

Ok done, you can now follow the discussion (if you wish) at:

http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=385

**Pull request merged**
