### PR TITLE
Fixing the covering of data by icons in reticule.lua

### PR DESCRIPTION
**Pull request by jimishol**
At resolution 600x800 last row icons of current system and target cover the data above them.
Lowering the local size to 20 makes the data readable and it does not seem to make any difference in higher resolutions.

### CODE REVIEW

**Comment by impaktor** [comment]
I've tested, I notice no difference on my resolution, so I'm fine with it, if it fixes an error on some other resolution. Ideally a screenshot showing the problem before/after this fix would be nice, could help e.g. @nozmajner weigh in on the issue.

**Comment by impaktor** [comment]
You do not need to push merge commits, the PR was done as it was.

**Comment by jimishol** [comment]
https://susepaste.org/74525928
https://susepaste.org/26527210
These are 800x600 resolution screenshots
As you can see 372m/s is covered by the current navigation target icon when size is 24 (the digit 3 is not visible)

**Comment by impaktor** [comment]
Please stop pushing merge commits, this PR is done, so no need to keep pushing merges. This PR should ideally be one single commit, not 3 as it is now.

**Comment by Web-eWorks** [comment]
Going to squash and merge. In the future, please avoid merging into a pull-request branch; if absolutely needed to advance the branch onto `master`, please:

```
git checkout master
git pull upstream master
git checkout <topic-branch>
git rebase -i master
git push -f origin <topic-branch>
```

Note: you'll want to confirm that the output of `git remote -v` shows your `upstream` remote as https://github.com/pioneerspacesim/pioneer and `origin` is https://github.com/jimishol/pioneer.

**Pull request merged**
