### PR TITLE
Handle JSON errors in Ship Type, Station Type definitions

### PR DESCRIPTION
**Pull request by johnbartholomew**
For #4226. Makes the game abort on startup when it tries to load a ship-def or station-def that fails parsing. There should be a not-totally-useless error message written to stdout, or (on Windows) to output.txt.

Code structure is pretty bad (sorry).

### CODE REVIEW

**Comment by impaktor** [comment]
> For #4226. 

Does it [fix](https://help.github.com/articles/closing-issues-using-keywords/) the issue as well?

**Comment by johnbartholomew** [comment]
> Does it fix the issue as well?

Yes. The commit has the tag to close the issue.

**Comment by impaktor** [comment]
Doh, sorry. I should have checked.

**Comment by fluffyfreak** [comment]
Yes this looks good to me.

**Pull request merged**
