### PR TITLE
Player Character title translateable

### PR DESCRIPTION
**Pull request by radius75**
see https://github.com/pioneerspacesim/pioneer/commit/cfb5d6c2848debadaf79404370d8ce8f3d991069#diff-4

positive for https://github.com/pioneerspacesim/pioneer/issues/2749

### CODE REVIEW

**Comment by impaktor** [comment]
> see cfb5d6c#diff-4

I don't think I follow, where did (the removal of) `libs/Translate.lua` come from? That's not in current master, and not in the (sum) of your commits either?

I'd poke @laarmen to review this, if it weren't for the fact that he recently announced that he currently doesn't have much time for pioneer

**Comment by radius75** [comment]
commit cfb5d6c is a part of https://github.com/pioneerspacesim/pioneer/pull/2521/commits
there player title no longer be translated

**Comment by laarmen** [comment]
"all in one" -> Please don't.

Reviewing a patchset is painful enough with correct commit logs, but reading a diff without any idea what it is all about is just a special brand of masochism. b3c85768 is an ideal commit message :-)

**Comment by fluffyfreak** [comment]
Ok @radius75 sorry for only just getting around to this one :(

The code itself looks ok, maybe the Git commit history could be cleaned up but that's not my personal priority so long as the feature does what it's supposed to :)

What else needs doing to get this merged? I see changes to `ui-core/en.json` so does this need something doing on (@robn) Transifex too?

**Comment by impaktor** [comment]
> What else needs doing to get this merged? I see changes to ui-core/en.json so does this need something doing on (@robn) Transifex too?

Nope. But if it had added new files then yes.

Generally it is a bad idea to move strings from modules to (ui-)core, right? Since it "de-modulerizes" pioneer.

**Comment by fluffyfreak** [comment]
Maybe but is there another way to make those strings available for translation?

**Comment by impaktor** [comment]
Could we hold on this, I'd like to give it a test first. Give me a day or two.

**Comment by fluffyfreak** [comment]
Yeah of course :) I just realised that I hadn't really looked at it before and it had been here for a while.

**Comment by radius75** [comment]
Currently "crew member title"/"station crew" strings are scattered:

in ui-core: GENERAL_CREW, COMMANDER, STATION_MANAGER, CONSTABLE,CHIEF_MECHANIC

in module-crewcontract: NAVIGATOR, PILOT, SENSORS_AND_DEFENCE, SHIPS_ENGINEER

To be able to easily translate "title" in the text and in the images (InfoFace.lua
), I moved them in the same place ```ui-core```.

**Comment by impaktor** [comment]
>What else needs doing to get this merged? I see changes to ui-core/en.json so does this need something doing on (@robn) Transifex too? 

I change my mind, to __yes__, since this is _moving_ already translated strings, there is some @robn magic needed I think. I didn't think that far in my first iteration of reading the question.

**Comment by impaktor** [comment]
OK, I've looked at this some now. So the actual _bug_ being fixed by this is that "Commander" wasn't being translated. All other strings worked but were inconsistent in which language module they were stored.

I don't have any strong objections to this.. I'll harass @robn this weekend to fix the auto-copy of all the translated files, so this can be merged.

**Comment by radius75** [comment]
It is worth mentioning:
If you use the older save than this FIX, then we will have "empty title" ```''``` instead of the previously translated string (crew and player title stored in old Save).
In New Game work as it should.

**Comment by fluffyfreak** [comment]
What's happening with this PR? Is it active or can it be closed?

**Comment by impaktor** [comment]
I think it's active, and waiting for @robn magic on transifex side, since it moves already translated strings.

But now tthere's also merge-conflicts I see. Would be good if those were solved.

**Comment by radius75** [comment]
I resolve conflicts this weekend

**Comment by radius75** [comment]
Done

**Comment by robn** [comment]
I've move the language keys from `module-crewcontracts` to `ui-core`. I haven't touched the rest of this PR; I'll leave that for someone else.

**Comment by radius75** [comment]
I cleaned up this PR. Updated and now one commit in branch.

**Comment by radius75** [comment]
I think the translation on transifex has been prepared by @robn in https://github.com/pioneerspacesim/pioneer/commit/61d75a60460af21d9694a4ba5e61e9fd377f2695 and  PR is ready to merge:)

**Comment by impaktor** [comment]
> I think the translation on transifex has been prepared

Yes. Now the question is if the code is "sane" enough to go in. I understand what the aim is (not have translated strings "hardcoded" in the save), but rob expressed some reluctance to merging it, as it might not be the optimal way to do it. I don't know myself. Maybe @johnbartholomew @laarmen or @fluffyfreak have opinions?

**Comment by fluffyfreak** [comment]
This just translates the job title yes? So `Commander` becomes `Kommondant` in German for example? Then I'm ok with it.

**Comment by impaktor** [comment]
> This just translates the job title yes? 

Not quite, it splits the `.title` into `.title` and `.titletranslate`, apparently to aviod including translated strings in the save file, making it language dependent. I'm not entierly sure why/if `.titletranslate` is needed for this? Why not simply use `.title` in the translation system when we want the title? `l[character.title]`? I'll admitt I have not gone in-depth here, but it does bother me slightly to have both a `title` variable _and_ a `titletranslate`, the latter "feeling" slightly like a sub-optimal solution. If they're really needed then a `character.get_title()` might feel more natural?

**Comment by radius75** [comment]
Translation in the ```data/libs/ui/InfoFace.lua``` is possible?

via: https://github.com/pioneerspacesim/pioneer/commit/cfb5d6c2848debadaf79404370d8ce8f3d991069

I applied the ```titletranslate``` that does not translate into libs. I had no better idea.

**Pull request closed without merging**
