### PR TITLE
Update the .gitignore file for more vs2015 files outputs

### PR DESCRIPTION
**Pull request by fluffyfreak**
Update the .gitignore file for more vs2015 files outputs

### CODE REVIEW

**Comment by impaktor** [comment]
You're both adding the explicit file names and also the pattern for them? Feels like the `*.exp` should take care of much of the files you are also listing. 

If you feel like fixing it, remove those lines, `git add` the file, then `git commit --amend`, and `git push -f`.

**Comment by fluffyfreak** [comment]
Cheers @impaktor I've remove the explicit 'exp' files and left just the filter. I wanted the 'lib' files to be explicit.

**Comment by impaktor** [comment]
Nice git-work!

Care to do it once more, to also make the file end on a new line?

**Comment by fluffyfreak** [comment]
Done! If you're next request is `dance monkey, dance!` I will be ignoring it though :P

**Comment by fluffyfreak** [comment]
Merging!

**Pull request merged**
