### PR TITLE
tradeships.lua unexplored crashfix

### PR DESCRIPTION
**Pull request by joonicks**
game crashes in tradeships.lua when entering an unexplored solar system

this = fix

### CODE REVIEW

**Comment by impaktor** [comment]
Good find!

Out of curiosity, do we know why exactly a crash is triggered? What function/line is it that causes the crash?

**Comment by joonicks** [comment]
in getSystemAndJump, line 310.

but afaik, unexplored system = no tradeships, so mite as well skip the whole thing.

**Comment by laarmen** [comment]
I don't remember if this is actually possible, but couldn't a tradeship use an unexplored solar system as a waypoint towards a distant, explored system?

**Comment by joonicks** [comment]
if any ship entered an unexplored system for any reason, it wouldnt be unexplored anymore.

sure some classes of ships like pirates or military wouldnt want to report their movements, but tradeships would. especially if a system was safe to travel, theyd report it = no more unexplored.

**Comment by fluffyfreak** [comment]
I'm happy with it, going to merge

**Pull request merged**
