### PR TITLE
Add dashed circles and lines to imgui, use for 2d radar

### PR DESCRIPTION
**Pull request by ecraven**

### CODE REVIEW

**Comment by nozmajner** [comment]
A preview of it:
radar_dashes
I think it looks good.

**Comment by fluffyfreak** [comment]
It's nice, merge it!

**Comment by ecraven** [comment]
hm.. ocornut of imgui mentioned that there might be performance issues, I'll need to investigate a bit more, not quite ready for a merge yet...

**Comment by fluffyfreak** [comment]
@ecraven, care to elaborate on the issues?

**Comment by ecraven** [comment]
See https://github.com/ocornut/imgui/pull/1118 for details.
The gist is (afaiu), this creates too many draw calls, it should be done with texturing

**Comment by nozmajner** [comment]
If it's too expensive, then ditch it, it's not that important.
(could be nice for the orbit display too, but not a requirement)

**Comment by impaktor** [comment]
Ah, I've been meaning to make this suggestion to the radar. Great!

**Comment by laarmen** [comment]
So, any news ? (None on the imgui PR itself)

**Comment by fluffyfreak** [comment]
I think we should close this one if it's not going anywhere.

We could do the dashed radar with just a regular square texture for this purpose.

**Comment by ecraven** [comment]
not going anywhere at the moment ;)

**Pull request closed without merging**
