### PR TITLE
GPU jobs for generating gas giant textures.

### PR DESCRIPTION
**Pull request by fluffyfreak**
# What is it?
This is some tech' I wrote a while ago that generates the texture map used by the gas giants on the GPU. It's a little rough right now but I hope to improve it as time goes by and to use the GPU jobs for other things.

- [x] Update linux makefiles
- [x] Make work on AMD MESA R600 GPU's

# Testing:
The new GPU jobs are enabled by default, they can be deactivated by replacing the line `EnableGPUJobs=1` with `EnableGPUJobs=0` in the `config.ini` file.

Then ingame pick the Earth based starting location and once it's loaded you use the `F2`->`F7`->`Click a Gas Giant`->`Ctrl+F10` to view one of the giants in the object viewer.

# Linux:
As usual the problem is the open source GPU drivers similar to #2176, this is why you can't have nice things :P on AMD Radeon chipsets using the R600 gallium drivers the shader fails to compile.

There is now a workaround in place that uses less noise octaves. This produces less detailed texture maps for the gas/ice giants but they still look good and at least the program runs.

Andy

### CODE REVIEW

**Comment by impaktor** [comment]
I was going to try this, but ended up in libpng 1.2 v.s. libpng 1.6 hell (also on my master), and threw in my towel. Sorry, but I feel I don't have much energy left in me nowadays.

**Comment by laarmen** [comment]
Oh, I was gonna try and reboot on my Linux partition tonight to update my resume, I'll try this while I'm at it. And for good measure, i'll even try to understand the code (and will probably fail)

**Comment by laarmen** [comment]
GasGiant.o: In function `GasGiant::OnAddGPUGenResult(SystemPath const&, GasGiantJobs::SGPUGenResult*)':
/home/laarmen/dev/pioneer/src/GasGiant.cpp:325: undefined reference to `GasGiantJobs::SGPUGenResult::OnCancel()'
GasGiant.o: In function `GasGiant::GenerateTexture()':
/home/laarmen/dev/pioneer/src/GasGiant.cpp:527: undefined reference to `GasGiantJobs::STextureFaceRequest::STextureFaceRequest(vector3<double> const*, SystemPath const&, int, int, Terrain*)'
/home/laarmen/dev/pioneer/src/GasGiant.cpp:562: undefined reference to `GasGiantJobs::GenFaceQuad::GenFaceQuad(Graphics::Renderer*, vector2<float> const&, Graphics::RenderState*, unsigned int)'
/home/laarmen/dev/pioneer/src/GasGiant.cpp:564: undefined reference to `GasGiantJobs::SGPUGenRequest::SGPUGenRequest(SystemPath const&, int, Terrain*, float, GasGiantJobs::GenFaceQuad*, Graphics::Texture*)'
/home/laarmen/dev/pioneer/src/GasGiant.cpp:565: undefined reference to `GasGiantJobs::SingleGPUGenJob::SingleGPUGenJob(GasGiantJobs::SGPUGenRequest*)'
GasGiant.o: In function `GasGiantJobs::SingleTextureFaceJob::SingleTextureFaceJob(GasGiantJobs::STextureFaceRequest*)':
/home/laarmen/dev/pioneer/src/GasGiantJobs.h:140: undefined reference to `vtable for GasGiantJobs::SingleTextureFaceJob'
graphics/opengl/libgraphicsopengl.a(RendererGL.o): In function `Graphics::OGL::GenGasGiantColourMaterial::GenGasGiantColourMaterial()':
/home/laarmen/dev/pioneer/src/graphics/opengl/GenGasGiantColourMaterial.h:54: undefined reference to `vtable for Graphics::OGL::GenGasGiantColourMaterial'
collect2: error: ld returned 1 exit status

Ooooops ;-)

**Comment by fluffyfreak** [comment]
@laarmen have you got everything? I updated the makefiles and it works on two Linux installations here. Not sure what's different that would stop yours from working.

**Comment by walterar** [comment]
> What is the point of a new feature that is turned off?

1) It looks very ugly on linux 64 - nvidia 650

**Comment by impaktor** [comment]
> 1) It looks very ugly on linux 64 - nvidia 650

Maybe a screenshot to demonstrate what isn't working properly?

**Comment by walterar** [comment]
EnableGPUJobs=0
jupiter1

EnableGPUJobs=1
jupiter2

**Comment by nozmajner** [comment]
Which one is the problematic? The second one seemt to resemble Jupiter a lot more. And I'm not seeing any glitches either.
jupiter

**Comment by fluffyfreak** [comment]
Oh ffs, linux open source drivers are going to make me insane.

You can't test to see if the shader fails because even when it won't RUN it will still COMPILE.
THen the next problem is that you cannot `#define FBM_OCTAVES 5` because that won't work, you actually have to replace the instances of `FBM_OCTAVES` in the shader with `5` itself. Only then will it RUN.

Staggeringly shit.

**Comment by fluffyfreak** [comment]
Ok the nightmare is that this works when generating the texture, but won't render if you have the eclipse code enabled...

**Comment by fluffyfreak** [comment]
@laarmen are you still having those builds problems?

**Comment by fluffyfreak** [comment]
@walterar which one do you mean is ugly? I was trying to make them look more like the real planets.

**Comment by impaktor** [comment]
Compiles fine.

Asking for a seed twice, with `EnableGpujobs=0`, (like pressing random seed twice), crashes the game:
```
pioneer: GasGiant.cpp:531: void GasGiant::GenerateTexture(): Assertion `!m_job[i].HasJob()' failed.
[1]    25657 abort      ./src/pioneer
```
I assume this is due to the debug just being temporary hack? But seems to work when enabled, although sluggish during first 3-4 seconds.

Merge whenever you're happy.

**Comment by fluffyfreak** [comment]
I haven't been able to get that assert, how did you do it?

**Comment by impaktor** [comment]
Well, I had the GPU-jobs disabled (from before) in my config, started pioneer, and did exactly what you suggested in your top post, then looked at the gas giant (I might have rotated it a bit with my mouse? If that is possible?), pressed new seed -> then random seed -> crash.

Second time I tried it, I though asking for random seed caused crash, so did same as above, but instead asked for random seed, which worked first time, but then second time it crashed.

Or that's how I remember it.

**Comment by Tichy** [comment]
I saw that this doesn't work on R600 (blank untextured plantes) unless I set AMD_MESA_HACKS=1 in config.ini

Should I add an entry to the FAQ about this?

**Comment by impaktor** [comment]
@Tichy Please do.

**Comment by Tichy** [comment]
http://pioneerwiki.com/wiki/FAQ#I_see_blank_untextured_Gas_Giants_and_I.27m_using_an_ATI_graphic_card_under_GNU.2FLinux_with_open_source_drivers_.28Mesa_R600.29

With a bit of explaination from fluffyfreak initial post.

**Comment by fluffyfreak** [comment]
Thanks @Tichy :)

**Comment by impaktor** [comment]
This adds new source files that cause XCode to stop working.
Ping @salborrelli if still with us.

**Comment by salborrelli** [comment]
@impaktor yup I'm still with you guys, and following the discussions, even though my job workload is getting out of control :-) I will pull the latest version and check the Xcode as soon as I can.

**Comment by jfacoustic** [comment]
Hey I got it working!  I submitted a pull request.

**Pull request merged**
