### PR TITLE
Galaxy (and other things) rework/simplifications

### PR DESCRIPTION
**Pull request by mike-f1**
Lot of simplification on code.

The main target is to let programmers do changes on galaxy stuffs without having to age during recompilation of (almost) everything.

In order to achieve this target, some function is no more inlined; some dependecy is changed; some file is splitted and some other is created to encapsulate things. Thus there aren't (big) new features...

There's still work to do but having `Pi.h`, `Game.h` and `Space.h` with less than 3 "effective" dependancies should ease life.
There's also more "forwarding" inside `galaxy` folder:
1) a new class (`SystemBodyWrapper`) which encapsulate dear `SystemBody` 
2) some files used to contains data (...stuff like `Enum`s),
3) some split (`Faction` and `CustomSystem`)
4) ...etc...

In addition I found some files which seem to have been emptied without removing includes: done :)

Finally I moved `GalaxyCache` management and part of hyperspace calculations from `Space` to `Game` and moved (partially) some code for that cache directly in `Galaxy`

I can provide a full "change log", but I fear the best solution should be that who review pick some useful title (...if possible ;) )

As (by now) usual my [experimental branch](https://github.com/mike-f1/pioneer/tree/experiments/src) is updated with changes from this PR, #4669 and #4612 with some more little additions.
This so people can try and report bugs.

This is intended to be merged **after** #4669 and #4612 got merged, thus I leave it as a draft PR.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
`Files Changed 94` 😭

**Comment by mike-f1** [comment]
> Files Changed 94 😭

Yeah: A new world record :D

But do not be discouraged: a lot of changes are due by a6b4a386b and ff47b32 which are "no brainer" (*).
They rework includes (the first) and move enums in a separate file (second), thus the only check I can think of is to check if it compile, as it is...

So, excluding the above, the number of involved files dramatically decrease.

Please consider the work from my perspective: if a open a pull request for every commit I did here and in #4669, I have had to rebase every single branch for every single conflict got by every single PR which got merged before mine :( This way instead I had only to rebase a single branch, which is easier.

(*) And 08d55900: another "no brainer".

**Comment by impaktor** [comment]
I can imagine reviewing 100 files, is not very motivating if they don't come with some very new shiny feature, like #1719

**Comment by laarmen** [comment]
You rang? :P

**Comment by mike-f1** [comment]
Ahahah, @impaktor , I don't know if it can be called "a feature", but you can try yourself: 
1) compile everything
2) open `Systembody.h` or `StarSystem.h` or `Galaxy.h`
3) hit cr in an empty line
4) save
5) re-compile

...Check how it works before and after this and other PR I did and... well, I hope you enjoy with the time saved.

This said, it's not only a matter of compiling time: having a change not propagating to every existing file in repo implies you can track (real) coupling between things, and get where your changes make differences without having to skim around the entire codebase.

Thus (I'm exaggerating here) I think I could state that that series of changes is more important than every feature even got merged: I'm trying to let the real structure of code emerge, I'm trying to let contributor see and better evaluate what they are changing, and I'm trying to save 5 seconds (more? less? ...frankly I don't care) x compilation x contributor x ever .

Don't know, let you judge if the above is worth the effort.

**Comment by Web-eWorks** [comment]
@mike-f1 in the interest of keeping things sane and easy to review, we're gonna have to ask that you separate parts of your code into separate PRs. General include-decoupling like the first few commits are a natural fit, and although it might seem like a lot of work to rebase a bunch of branches, it's much much easier than merging 2-3 segfaults with each PR.

Sadly, the alternative is having to wait 2-4 months for people to find the time and energy to review a massive PR with many unrelated changes lumped together. Please, by all means cherry-pick the commits you named and open them as a new PR - I'll sign-off on the changes as soon as you do so!

**Comment by impaktor** [comment]
> Don't know, let you judge if the above is worth the effort.

Well, my C++ skills have atrophied the past years, so it's really up to others, depending how motivated they are to review and merge.

It's very nice to see you work on the code base, don't get me wrong.

**Comment by mike-f1** [comment]
Ahahah (again: what a day!) @Web-eWorks , thank's for mentioning

> 2-3 segfaults with each PR

...I hope to do better when me (as everyone) can spot what changes implies, but I should say that it is far better than having someone left stuck during recompilation... But don't get me wrong: I really appreciate your tips, you're encouraging ;)

Apart from the above, I think you're asking for things in a "__Draft _PR__"_ (...I already talk about this before, or I'm wrong?), and this will be kept as "Draft" until the previous PRs got merged... So no hurry plz :)

Regarding the "massive PRs", frankly I don't think I would update 22 PRs (and branches) and follow your hints as I spent most of __my__ time rebasing; I got no reviews even for simpler PRs and even if I would, I really can't trust your words as, but please don't hesitate to bark to me if I'm wrong, last comment I got from you was: "I'll handle review tomorrow", dated 9 September 2019 :/

...An alternative I'm evaluating is to care about my "experiments" branch and merge only there my changes, then I can open little PR where I can reference some interesting commit which **you** can cherry-pick... But I really don't know... Time will pass before I decide.

**Comment by Web-eWorks** [comment]
@mike-f1 

> Apart from the above, I think you're asking for things in a "__Draft _PR__"_ (...I already talk about this before, or I'm wrong?), and this will be kept as "Draft" until the previous PRs got merged... So no hurry plz :)

On the contrary, please do grab the commits you mentioned and open them as a full PR before moving this one away from Draft status! I'd like to get those merged ASAP; they're standalone, easy to follow, general QoL changes, and they'll drop the complexity of this PR significantly.

**Comment by laarmen** [comment]
Thank you for your contributions!

There are very good reasons for asking you to split up this PR, that mainly originate from the basic fact that a 22-commit PR with no specific end in mind is just not reviewable. For a maintainer, the responses to such can vary, but are broadly into several buckets :

* Try and work through the branch to make it so that it's reviewable.
* Ask for the contributor to do so.
* Ignore the PR and pray that somebody else will deal with it.
* Simply close the PR.

The thing is, when I submit a PR to an open source project, it might seem like I'm gifting them something, but in reality it's the other way around. By default, my opening a PR only means I'm taking time and attention from the maintainer, that they could spend on other things, especially if it's a volunteer project. From their point of view, merging my code means having to maintain it afterwards, and being the ones being yelled at if my patches broke something. And *yes*, people can be really unpleasant when `master` doesn't work, even for games.

So the best way to have my contributions merged is to make it obvious to the maintainers that it's something *they* want, and to make it easy for them to check that they're not breaking `master`. Thus, making it easy to review.

It might seem like a lot of work, but keep in mind that it's also a lot of work to review, merge, and maintain afterwards, and that asking you to split a PR is far much more work than simply closing your PR.

To be blunt, @Web-eWorks is actually being rather nice here, please respect their work.

**Comment by mike-f1** [comment]
> Thank you for your contributions!

Glad to serve :D 

...And?

**Comment by fluffyfreak** [comment]
@mike-f1 Ok, I am not going to review this PR, I am going to close it and explain what you need to do for us to review it.

The reason is that you have done too many unlreated things in one single PR, and it is almost impossible to separate them out for review.
That stops me from understanding _why_ you did something, or even what has changed.

The way to fix this, is to cherry-pick related/similar commits out into new branches, and keep each PR that you create from them as simple as possible.

Those two massive commits that hit most of the 94 files affected, could *both* be PR's of their own.

When you do this it keeps the PR manageable for the reviewers.

There's so much extra stuff in here that it's the Galaxy refactoring is almost an afterthought, a minor detail.

I would like to get this work into Pioneer, but it needs to be broken up into smaller PRs that can be reviewed.

That's the point that @Web-eWorks and @laarmen have been trying to communicate to you. That you have made the PR too difficult to review by throwing everything into one massive lump.

**Pull request closed without merging**
