### PR TITLE
Different tech levels for the thruster upgrades

### PR DESCRIPTION
**Pull request by robothauler**
Feels more realistic when the upgrades are not visible at all tech levels.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
🤔 not sure about this, the reason I did it was because it's a bit like modding your car. Something open to all levels.
But I'm willing to hear what others thinks.

**Comment by impaktor** [comment]
I'm positive, I'm all for differentiating space stations. Could even have minimum tech level x > 1.

By @fluffyfreak's description, it sounds more like it shold be something offered by the shipyard/ship repair shop, rather than the equipment shop?

**Comment by nozmajner** [comment]
@impaktor Moving them to the ship repair shop sounds apt to me.

**Comment by impaktor** [comment]
I don't want to merge this against @fluffyfreak's wishes, so it's up to him, I guess, to give thumbs up on this.

**Comment by Web-eWorks** [comment]
To be honest, this is kind of a no-brainer change; if you want top-of-the-line high-performance parts it's not like you can just walk into your local AutoZone and pick them up off the shelf - you usually have to order them from the manufacturer, which gets more difficult in an interstellar society.

Given that ship equipment will be getting reworked sooner or later I wouldn't worry about moving them to a different station screen, and I'm personally all for giving them a (low) minimum tech level.

**Comment by fluffyfreak** [comment]
@impaktor I'm not precious about it, people seem in favour of using the tech levels. Go for it 👍

**Pull request merged**
