### PR TITLE
Fix segfault when exiting Pioneer

### PR DESCRIPTION
**Pull request by pcercuei**
Signed-off-by: Paul Cercueil <paul@crapouillou.net>

### CODE REVIEW

**Comment by laarmen** [comment]
Thanks for the patch. Glancing at the diff, I however don't see the
relationship between the patch itself and its title? Granted, it's a
cursory look.

Le lun. 24 juil. 2017 à 12:24, Paul Cercueil <notifications@github.com> a
écrit :

**Comment by pcercuei** [comment]
The segfault happens when `SDL_GL_DeleteContext(m_glContext);` is called, because m_glContext is never initialized.

**Comment by ecraven** [comment]
looks good to me, however, wouldn't it be simpler to just remove `m_glContext`, which seems to be never used anyway?

**Comment by pcercuei** [comment]
Well, we have to keep it around so that the GL context of SDL is properly destroyed.

**Comment by ecraven** [comment]
fixes #4057 for me.

**Pull request merged**
