### PR TITLE
Pigui equipment market for station view

### PR DESCRIPTION
**Pull request by vakhoir**
So I've been working on this for a while, and it's almost ready, but like I said in another PR, I won't be available for the next couple weeks. I thought I'll open a PR and maybe someone can take a look, I'll finish it when I'm back.

### CODE REVIEW

**Comment by mike-f1** [comment]
Nice work!

I didn't review it, but a glance bring to my attention this new function:
`ui.popupModal`, which problably should have "popped up" earlier :smile: 

As a hint they would be used it in save/load and preference windows, so people
can't close the underlying window while loading (IIRC, I'm AFK right now).

May I ask if you have time to detach that change from the rest? ...thus
(hopefully) it can be merged sooner and I or someone may use it for those issues.

**Comment by Web-eWorks** [comment]
I'll give this a more indepth review later when I have time, but for now I'd just like to ask that you prefer the use of `function MarketWidget:refresh()` over `function MarketWidget.refresh(self)` - it's cleaner, more in-line with existing code, and clearly communicates the intent. Also, it's three less characters to type and standardizes the `self` variable name.

**Comment by vakhoir** [comment]
> May I ask if you have time to detach that change from the rest? ...thus
(hopefully) it can be merged sooner and I or someone may use it for those issues.

No, sorry. Feel free to copy-paste and submit it yourself. I'll rebase when I'm back.

> but for now I'd just like to ask that you prefer the use of function MarketWidget:refresh() over function MarketWidget.refresh(self) 

Huh... that was some sort of a brain fart. I'm pretty sure I tried that, and it threw some kind of error. Must have screwed something else up at the time, because it's obviously working now.

**Comment by vakhoir** [comment]
Alright, I'm back, and I applied my tweaks.
If there's no more feedback, it's good to from my side.

**Comment by impaktor** [comment]
Nice!

For some fast testing, the numbers in the footer looks a bit weird on my end:
screenshot-20190710-214223

(also, for some reason, taking screenshots in-game are now transparent?)

**Comment by vakhoir** [comment]
> For some fast testing, the numbers in the footer looks a bit weird on my end:

Not sure what you mean? They seem normal in the screenshot

> (also, for some reason, taking screenshots in-game are now transparent?)

I'm guessing this is caused by whatever made the buttons black. My changes are only on the LUA side.

**Comment by Web-eWorks** [comment]
Pinging @pcercuei; I think the screenshot transparency is related to the libPNG removal...

**Comment by pcercuei** [comment]
> Pinging @pcercuei; I think the screenshot transparency is related to the libPNG removal...

What's the shortcut to take screenshots? It's not in the controls option tab.

**Comment by nozmajner** [comment]
Should be Ctrl+Printscreen

**Comment by pcercuei** [comment]
> Pinging @pcercuei; I think the screenshot transparency is related to the libPNG removal...

It's not related. I reverted the commit, rebuilt Pioneer and the screenshots are still broken.

**Comment by vakhoir** [comment]
Ok, I almost figured it out.
The button coloring was broken by the change in Color.h in c19aab4e482d4574b7b6af2e738a1574db1dbc99, and I'm still trying to get to the bottom of it, but the transparent screenshots started when #4626 was merged

**Pull request closed without merging**
