### PR TITLE
fix ARFLAGS to remove warning

### PR DESCRIPTION
**Pull request by ecraven**
set ARFLAGS to rcD (instead of rcu)

### CODE REVIEW

**Comment by impaktor** [comment]
I can't review this due to lack of knowledge. If the author is sure it is right, I can merge it. Doesn't look like it will start a game of global thermonuclear war, so should be safe.

**Comment by tomyun** [comment]
`D` (deterministic mode) is specific to GNU `ar` and causes build failure on macOS:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar: illegal option -- D
```

Users can circumvent this issue by explicitly setting `ARFLAGS` when running `configure`, but this may not be ideal.

**Comment by ecraven** [comment]
@tomyun does macOS ar have U (Do not operate in deterministic mode)? There's no actual reason for needing deterministic mode (so far), we just need something that works on all platforms and gives no warnings.
Can you try ARFLAGS=crU, if that works, I'll start a PR, should be fixed soon then.

**Comment by tomyun** [comment]
It doesn't accept `U` option either, but non-deterministic behavior seems to be by default according to this [question](http://stackoverflow.com/questions/6741737/ar-library-override-timestamp) posted in SO.

You may want to have a look at the [man page](http://www.manpages.info/macosx/ar.1.html) for the macOS version of `ar`.

**Pull request merged**
