### PR TITLE
Stop tradeships crashing into landing pads while trying to hyperspace

### PR DESCRIPTION
**Pull request by WKFO**
Makes things better, for now (their jumps may still be illegal, idk). Maybe we can add a delay so ships can travel even further away from the starport before jumping.

Gotta admit it is enjoyable watching the AI screw up :D

### CODE REVIEW

**Comment by macksting** [comment]
I know it wouldn't actually help anything, but can somebody record a video of this? It sounds hilarious.

**Comment by WKFO** [comment]
https://youtu.be/dxQpHUjW-lQ

**Comment by impaktor** [comment]
Why do they crash into the pad to begin with? I thought #4098 was solved, as they should no longer be refused to hyperspace due to landing gear being down, right? That code checks if ship is player.

I suspect @laarmen would argue that hyperspace rules should be implemented in Lua (and then i Equipment.lua)?

I suspect @jaj22 would argue this is behaviour the AI should be able to "know" about, and impelemnted in c++?

**Comment by WKFO** [comment]
As soon as ships lift off they attempt to hyperspace the way you (impaktor) do (begin countdown and hope you have enough time before hitting the ground) Most ships acheive this but some ships with low accel on high-ish G worlds unfortunately hit the ground as far as I've observed

**Comment by jaj22** [comment]
The old issue is that there's no function exposed at Ship level for either flying to an arbitrary point or flying away from a body. Not an ideological thing. If you have scripting then people will want fine control, even if full-journey functionality also existed at the C++ level.

However, as far as I can tell, the Lua side has no understanding of frames or relative positions, so some abstraction is required. Maybe something like AIEscape(body, dist), that attempts to fly the specified distance away from the target body. Could implement that with the FlyTo code, although the calculation is a little fiddly. There's also a question of how much fuel to use if the function is used for long distances.

I thought people used to fudge this either by using FlyTo on another planet in the system, or one of the orbits. I don't know what the hyperspace rule is at the moment.

**Comment by fluffyfreak** [comment]
This just patches the problem and I'm ok with that for this PR.

To make the departing ships fit our "legal" rules on hyperspacing they would need to reach a certain distance from the port. So fly to low orbit, then jump. Perhaps just having a delayed hyperspace jump whilst they fly-to-orbit would be enough?

**Comment by fluffyfreak** [comment]
@impaktor if we had tail-sitter style launching this would be a non-issue since the main engines are much more powerful and the ships would still be going upwards when they jumped :)

**Pull request merged**
