### PR TITLE
Fixed XCode Project file

### PR DESCRIPTION
**Pull request by salborrelli**
Hi guys,
 this is my first commit to Pioneer so feel free to hit me with your comments and requests if I did something the wrong way. 

The main goal of this commit is to update the project file for XCode on Mac OS X. The old version was clearly outdated as several files that were listed in the project were missing from the file system, and vice-versa. I've spent some time fixing the project by synchronising it with the file system, upgrading references to the latest version of the relevant libraries, etc.

The project now builds without errors on Mac OSX 10.10 (Yosemite) and XCode 6. The resulting App runs smoothly and seems even better than the official Mac OS X build that I have downloaded from the web site, since the compiled version does not crash if I try to start from a station different from the "Barnard's Star" (as the binary version did).

Note that in order to avoid weird compilation problems, I have also had to do the following minor changes to files out of the "OS X" directory:

1. contrib/miniz/miniz.h - added static cast to mz_uint8 to real header structure, in order to avoid the following compiler error: "Non-constant-expression cannot be narrowed from type 'char' to 'mz_uint8' (aka 'unsigned char') in initializer list"
2. graphics/opengl/LineMaterial.cpp - commented line "assert(desc.effect == EFFECT_LINE);" as there is no EFFECT_LINE constant defined anywhere in the project (or at least, I haven't been able to find it). For a similar reason I removed the third parameter from the constructor: there is no three parameters constructor defined in Graphics:OGL:Program class.

Let me know if you need me to change anything in order to accept the commit. If this commit is accepted I'll try to dig into the code further to see if I can someway help with the development of this wonderful project.

King Regards,
Sal.

### CODE REVIEW

**Comment by impaktor** [comment]
Welcome, and thanks.

We have a pull request (PR) for this in #3397. That is older, and I don't know which is the best, since we're all Mac Illiterate here. 

If you compare your changes with #3397, are there new/better solutions in your PR?

I think you pretty much have to advice us.

**Comment by fluffyfreak** [comment]
`graphics/opengl/LineMaterial.cpp` is not currently used and should be excluded from the project if possible.

Does this mean that we can use XCode to package the project for distribution as well? Or is that something separate that I will still have to do from the command line?

**Comment by fluffyfreak** [comment]
Also welcome and thanks for doing this! :)

**Comment by salborrelli** [comment]
Hello,
  sorry for the late answer but I write from Italy so there is quite 
some difference in timezone to take into account.

I've looked at #3397 and I've noted that you have been discussing about 
it for several months now, while I've been working on my XCode project 
for a few hours at most. Furthermore, the author of #3397 took care of 
editing some files which I also noted are in need of some update (e.g. 
COMPILING.txt and osx/install_ports.sh) but I haven't had time to look 
at yet because of my "real life" constraints.

All summed up I would say let's go on with #3397 if you find it's 
correct, I will try to pull it to my env and do some testing as soon as 
I have time. And I'm sure I'll have other chances to help you with this 
amazing project in the future.

**Comment by impaktor** [comment]
> some difference in timezone to take into account.

Actually, we're all in the same time zone +/- 1 hour (excluding rob down under). We're in no rush.

I've lost track on where we are with #3397, and we pretty much rely on you Mac-people to tell us what needs doing, or what is wrong/good.

You can post in 3397 your findings/opinions, and if it's ready to be merged.

We can keep this PR open until we know where we're going with this.

> And I'm sure I'll have other chances to help you with this amazing project in the future.

Hope to see more contributions from you. You know basic C++? Here's a small suggestion to get started if you're interested: _change time acceleration with PageUp/PageDown-keys._

**Comment by salborrelli** [comment]
Hi Andrew,
  thanks for the advice about LineMaterial.cpp, I have now removed it 
from the project.

Regarding XCode, you can use it to create the Mac OS "App", which just 
to clarify is the equivalent of a Windows ".exe". In order to distribute 
the application you need to create either a "bundle" or an "installer". 
The bundle solution is easier and can be seen as (roughly) the 
equivalent of creating a zip or tgz archive. Creating the bundle is very 
easy but you cannot do it from within XCode directly: there are several 
Apps that you can use such as DiskUtility, or you can use the "hdiutil" 
command line tool.

If you think it could be of use, I can create a bundle for distribution 
to OS X 10.10, publish it to one of my servers (or even better to Google 
Drive) and send you the link so you can test the application yourself, 
just let me know.

**Comment by salborrelli** [comment]
>Hope to see more contributions from you. You know basic C++? Here's a small suggestion to get started if you're interested: change time acceleration with PageUp/PageDown-keys.

C/C++ have been my languages of choice for several years. In this time of web and mobile apps I have had to switch to PHP5 and Java for my business, but I like the idea of doing some "real" programming again, at least for fun (and according to my job and  family commitments of course :)

I haven't been able to find "change time acceleration with PageUp/PageDown-keys" in the issue tracker, but I'll definitely look into it if you send me the reference.

**Comment by impaktor** [comment]
There is no issue on it (it's such a small change). I guess `src/ShipCpanel.cpp` line 78 is a good start, if you're interested. If you have other ideas/projects on your own for pioneer then go ahead with that.

**Comment by fluffyfreak** [comment]
I'd prefer to go with this solution so long as it doesn't break the command line build, because that's always a good fallback.

We've heard nothing on #3397 in quite a while :(

**Comment by fluffyfreak** [comment]
To give some context, I have a Mac Mini and did the last OSX build but I am in no way comfortable doing work on OSX or with XCode.

I did it from the command line and packaged the bundle manually / using scripts.

**Comment by salborrelli** [comment]
>I'd prefer to go with this solution so long as it doesn't break the command line build, because that's always a good fallback.

So is there any way I can help you with the build process? Just to clarify I can hardly take frequent periodic tasks on (e.g. doing a daily build or kind of) but "infrequent periodc tasks" are within my range. 

To star with, I will try to create an install package for OSX today COD or tomorrow morning, will send you the link asap so you can install it on you Mac Mini and send me your feedback.

**Comment by fluffyfreak** [comment]
@salborrelli that would be fantastic :)

**Comment by salborrelli** [comment]
Hi all,
 I've just committed a new version of the Xcode project, where I have removed some unnecessary libraries. In addition, I have updated the Xcode section in the COMPILING.txt file to match the new project.

Finally, I have created an install package for Pioneer for you to test and uploaded it to Google Drive:

https://drive.google.com/file/d/0B3YT4wkIA2jjZjh6N3lhcUVrajg/view?usp=sharing

You can use this package to automatically install the Pioneer APP to the system's Applications directory on Mac OS X 10.10 and later. Please test the installer and let me know if everything works as expected. If it does, then I've already scheduled the creation of an additional build phase for creating the install package directly from Xcode 6.

**Comment by salborrelli** [comment]
>There is no issue on it (it's such a small change). I guess src/ShipCpanel.cpp line 78 is a good start, if you're interested. If you have other ideas/projects of your own for pioneer then go ahead with that.

I'll definitely look into this change, the only doubt I have is about the use of the PageUp and PageDown keys, which are already used for changing the camera view. Should we also change the default settings for "Top Camera" and "Bottom Camera"?

**Comment by impaktor** [comment]
> I'll definitely look into this change, the only doubt I have is about the use of the PageUp and PageDown keys, which are already used for changing the camera view. Should we also change the default settings for "Top Camera" and "Bottom Camera"?

Ping @nozmajner

**Comment by nozmajner** [comment]
I think that should be fine if the views are only on the numpad keys.
On laptops without numpat, it can be problematic, but that's true for the views anyway, and as far as it's rebindable, it shouldn't be much a of a problem in my opinion.

**Comment by fluffyfreak** [comment]
@salborrelli so close but I get a problem report when i try to run it.

> Library not loaded: /opt/local/lib/libcurl.4.dylib
> Reason: Incompatible library version: pioneer requires version 9.0.0 or later, but libcurl.4.dylib provides version 8.0.0

It might just be because I haven't update this Mac in a while, it's not on `El Capitan` yet.

**Comment by salborrelli** [comment]
Don’t think this is related to the OS version, I too haven’t upgraded to El Capitan yet.


Probably the cURL library that ships with your OS is an older version, I will try to statically link the library to the APP so there is no need to use the OS version. Will send  you the new link once ready.

**Comment by salborrelli** [comment]
@fluffyfreak actually this is a very strange error, because the latest version of cURL is 7.45 so I don't understand what that "version 9.0.0" refers to. Which version of Mac OS X are you currently running?
Another test that we can do is try to upgrade your version of cURL via MacPorts, this is the command that you have to issue from terminal:

sudo port install curl

Once done, please retry running pioneer and let me know if the problem persists.

**Comment by laarmen** [comment]
My guess is that it refers to an ABI version number, and not to the actual
software version. On Linux we have currently libcurl4 (well, libcurl3 is
still around on many systems as well).
Not that it helps that much, though.

**Comment by fluffyfreak** [comment]
@salborrelli ok that's fixed it :)
My Mac was just very out of date.

**Comment by salborrelli** [comment]
@fluffyfreak good to know that the problem is resolved, but in the meantime I realized that I've been probably a little bit too demanding on the OS compatibility requirement. I will decrease the installer's target OS version to 10.9 (Mavericks) from now on.

**Comment by fluffyfreak** [comment]
Ok I am going to merge this asap and then close #3397 I think.
We can pick any additional bits from there if it's helpful.

Having an independent packaging script might be useful for anyone doing command line build in the future but that doesn't need to be part of this PR.

@salborrelli is there anything more you want to do to this PR before it gets merged?

**Comment by salborrelli** [comment]
>@salborrelli is there anything more you want to do to this PR before it gets merged?

Nothing that is strictly related to this pull request. To clarify, I think the Xcode project has been fixed, and this is the main goal of this PR, but there are still a few things to take care of before we can say the Xcode project is complete, for example:

1. updating the Version and Build numbers automatically
2. generating the Pioneer Installer directly from Xcode

etc. ... but I'll add them to future request(s).

@fluffyfreak the bottom line is, feel free to merge this request as soon as you are ready.

**Comment by impaktor** [comment]
@salborrelli if you see useful commits from #3397 then it's good practice to cherry-pick them into what ever future PR you plan to submit next. (Or point them out to us so we can merge them)

**Comment by fluffyfreak** [comment]
@salborrelli thanks for the patch I've just merged it, how would you like to be known in the `AUTHORS.txt` file?

**Comment by salborrelli** [comment]
@impaktor well to be honest I have already done an analysis of #3397 by cloning the corresponding branch to my local system and comparing the Xcode project files. I have also taken inspiration from parts of his commits to update some files, for example the instructions in COMPILE.txt and list of ports in install_ports.sh.

**Comment by impaktor** [comment]
Then I suppose we might as well close #3397? Or si there anythin worth saiving in it? Or maybe that's what your future PRs are for?

**Comment by fluffyfreak** [comment]
Closed it.

**Comment by salborrelli** [comment]
> @salborrelli thanks for the patch I've just merged it, how would you like to be known in the AUTHORS.txt file?

Simply adding:

Sal Borrelli 

to the AUTHORS.txt file would be ok, thank you very much!

**Comment by salborrelli** [comment]
>Then I suppose we might as well close #3397? Or si there anythin worth saiving in it? Or maybe that's what your future PRs are for?

@impaktor Don't fell like saying a definitive word on someone else's work that I probably don't know well enough, but if the PR is still open and you have tried contacting the author without getting any feedback for some time, then my opinion is that you can close it without problems.

**Comment by fluffyfreak** [comment]
@salborrelli it would be great if we could get a latest OSX build done with the git tag 20151130.

**Comment by salborrelli** [comment]
Sure no problems, will send you the link to the Install package asap.

**Comment by salborrelli** [comment]
@fluffyfreak Ok the new build if ready, you can download the Mac OS X installer at:

https://drive.google.com/file/d/0B3YT4wkIA2jjQWpqLUp1dkdmWXM/view?usp=sharing

Let me know when you have finished downloading the file.

**Comment by fluffyfreak** [comment]
yep grabbed it, I'll try to get it uploaded tomorrow - there's currently a hastily built version I uploaded but I'll replace it with yours.
Thanks :)

**Comment by salborrelli** [comment]
@fluffyfreak whatever the version you want to use I suggest that you replace the current one asap. Infact after downloading the ZIP I could'n install the APP because it seems to require Mac OS X 10.11 or above. Now I think that a very small fraction of Mac users have already upgraded to 10.11 (El Capitan) so we need to change the published version to support an earlier OS version.

Finally note that my installer package supports 10.9 (Mavericks) and above.

**Comment by fluffyfreak** [comment]
Thanks for reminding me! I've uploaded your pkg but zipped up so that it matches our usual scheme.
Hopefully that works :)

**Comment by salborrelli** [comment]
Yes it works without problems, and indeed I've already tested it with success.

**Pull request merged**
