### PR TITLE
Fix autopilot crash, when no mass in frame of reference

### LINKED ISSUE #5535: Pioneer crashes when unpausing
### Observed behaviour
Pioneer crashes when unpausing.

### Expected behaviour
Pioneer not crashing when unpausing, or not crashing at all.

### Steps to reproduce
1) Open Pioneer;
2) Wait for the game to finish booting, then click "Continue game";
3) When the save has finished loading, click any of the time acceleration buttons except for pause;
4) Watch as the game freezes for about 5 seconds and then crashes to desktop without any error messages.

__My Pioneer version (and OS):__
20230209 (b8e7e20) - Windows 10 Pro 21H2

__Previous bug-free Pioneer version:__
20230205 (df1f2a9)

[output.txt](https://github.com/pioneerspacesim/pioneer/files/10700676/output.txt)

[Affected save file (extension changed to zip to bypass upload restrictions)](https://github.com/pioneerspacesim/pioneer/files/10700974/Masuia.Mid-Travel.zip)

Screenshot of the game right before unpausing:
image

### PR DESCRIPTION
**Pull request by azieba**
Fixes #5535. The problem is for systems with no star in the main frame of reference. Are they even valid?

### CODE REVIEW

**Comment by Gliese852** [comment]
@azieba I guess any multisystem contains a root frame without stars,

**Comment by craigo-** [comment]
I have a 20230203-level [savegame](https://github.com/pioneerspacesim/pioneer/files/10776198/HS.to.Sirius.causes.CTD.zip) that when I hyperspace to Sirius:

* 20230203 release: works fine
* 20230213 master b4894e6f953357ca08563b706176fd44e5bc593f: Crashes to desktop upon arriving at Sirius (A or B)
* 20230213 master b4894e6f953357ca08563b706176fd44e5bc593f + PR #5551: works fine

Environment:
Windows 10 Enterprise 22H2
Compilations performed using Visual Studio 2019 16.11.24 using CMake instructions and x64-Release configuration

**Comment by azieba** [comment]
> * 20230213 master [b4894e6](https://github.com/pioneerspacesim/pioneer/commit/b4894e6f953357ca08563b706176fd44e5bc593f) + PR [Fix autopilot crash, when no mass in frame of reference #5551](https://github.com/pioneerspacesim/pioneer/pull/5551): works fine

So I guess we have an independent verification. Thank you!

**Comment by craigo-** [comment]
You're welcome 😄

I am still getting occasional crashes to desktop with this PR applied, typically when autopilot is engaged inbound to a starport - i.e. not immediately upon arriving at the system as previously described. This can occur in single-star systems also, e.g. my last occurrence was returning to Los Angeles, Sol (journey from arrival point to starport about 75% complete).

I'm not sure but the CTD could be occurring when the frame of reference changes..?

I'd like to supply a backtrace / call stack, but I cannot currently compile a debug version (issue #5545).

**Comment by azieba** [comment]
> I'd like to supply a backtrace / call stack, but I cannot currently compile a debug version (issue #5545).

Debug versions have asserts active so they crash much more often even though release works fine. If such assert is in a way I comment it out to proceed.
Save file would be actually more useful if you have one.

**Comment by Web-eWorks** [comment]
Apologies on waiting so long to merge this PR - it slipped my mind that this was already in-progress and waiting on review/merge.

**Pull request merged**
