### PR TITLE
Use PCG for random number generation

### PR DESCRIPTION
**Pull request by fluffyfreak**
# Description:
Since I first heard about [PCG](http://www.pcg-random.org/) I have been meaning to give it a try with Pioneer. The maths for understanding exactly how robust this is are a bit beyond me in some ways however it is supposed to be a very fast and very robust random number generator with a very long period and many other fine qualities.

# Motivation:
We used to use a Mersenne Twister RNG but it was deemed "too slow" at some point (#1893) and replaced with a faster but 'less secure' XOR based RNG along with the comment: `As an xorshift generator the worst thing about it is it gets stuck on zero input`.

Recently we've had a lot of comments about objects, seemingly along the sector 0-axis, not being generated correctly, issues with the galaxy being regenerated incorrectly, and the startling similarity between characters at stations. 

So I picked up the `pcg-cpp-0.98` implementation, fixed the VS2015 issues and whipped this up to get us started.

# Results:
It still works.
I don't notice any speed difference personally but I would bet that it's slower than the XOR rng.

# Todo:
I haven't finished yet, although the actual code is in and the Random class uses it and works I haven't done the following:
- [x] Fix Linux build
- [x] Test
- [x] Bump save-game version

Andy

### CODE REVIEW

**Comment by impaktor** [comment]
So to solve this problem, described here:
dilbert

My suggestion would be something like:
xkcd

No, but seriously, this builds fine on GNU/Linux for me. I haven't tested it any further than this.

Also, does this close #2108? (which links to http://xorshift.di.unimi.it/)

**Comment by fluffyfreak** [comment]
Essentially yes :)

I'd forgotten about #2108 but hopefully it will fix some of those issues. It would be nice to get better brains than mine to look at it!

**Comment by fluffyfreak** [comment]
ON my PC this turns the current startup time of : `29339.304202 milliseconds` into `27841.688087 milliseconds` ... which is nagging at me as not-quite-right since it was reporting `34000.etc` a few minutes ago.

What I'm saying I guess is that the difference is negligible and is probably more affected by HDD performance than RNG.

**Comment by impaktor** [comment]
I know of another PR with a savegame bump. Would be practical to merge them at the same time.

Please don't finish this too soon. :wink: 

> It would be nice to get better brains than mine to look at it!

Your brain seems pretty fine to me (grey and mushy I assume?). But more eyes doesn't hurt, maybe @johnbartholomew would care to look at it some?

**Comment by johnbartholomew** [comment]
I have no strong feelings one way or the other

I don't have anywhere near enough statistical knowledge to judge the relative merits of these PRNGs. If it fixes a bug with generation of bodies along the zero axis then that seems worthwhile.

**Comment by joonicks** [comment]
my opinions, if anyone wants them;

startup time, a better way to do it would be to compile original and modified, do 10 startups with each, discard the first two of each and do an average on the remaining eight.

breaking the galaxy continuum, hey, whatever, Pioneer is still Alpha, if you want continuioty - dont upgrade. otherwise I think devs are free to break the galaxy every day if they wanted to.

merge - test - analyze. more testers can only give better end results (even if it means reverting)

**Comment by fluffyfreak** [comment]
OK, bumped the save version, flown around a bit, landed at various places, looked at ships on offer, BB, etc.

No problems as far as I can tell.

**Comment by impaktor** [comment]
Btw, this changes the starting station type in London. The reason we switched from LA to London was to get the nice octagonal stations as a first player experience.

So either change starting station on Earth, or #790, or we are not as excited by the octagonal stations anymore. I have no strong feelings one way or the other, I'm just pointing it out.

**Comment by impaktor** [comment]
Also, does this require any testing on Mac?

**Comment by fluffyfreak** [comment]
This should produce the same output in each platform, though you are right that I haven't tried it on that due to the existing issues with building on OSX.

**Comment by impaktor** [comment]
OK, I just thought I should mention it.

I do wonder if there was some way to release the next savebumping pioneer as "unstable/test"-version? On SSC only?

**Comment by fluffyfreak** [comment]
Well built and tested using the cmd line on OSX and it works fine :)

How would I identify the start location for Los Angeles on Earth? It uses the Octagonal station.
At some point we must get rid of the 6 pad station that I hacked together!!!

**Comment by impaktor** [comment]
> How would I identify the start location for Los Angeles on Earth?

 82075ea30e179d96172b66dfd5d8905729383bc7

**Comment by fluffyfreak** [comment]
Yeah I did it by looking at the ordering of the stations in the system info screen... and counting up from London to LA :)

**Comment by impaktor** [comment]
Does this branch conflict with something?

@fluffyfreak I've written up an "announcement"-post for SSC, where I blatantly assume we've merged this PR as well as the following:

#3498
#3505
#3254
#3504
#3503

I'm feeling in the mood to get this merge started, and throw the players in the deep end, either now, or tomorrow. Hm, either way, our build bot robn wont be able to start anything now, seeing how it's in the middle of the night over there.

@fluffyfreak what was your plan? To test and merge today? If not, are you fine with me merging everything tomorrow?

**Comment by fluffyfreak** [comment]
It was conflicting with an unchanged line in `Game.cpp` for some reason, odd.

I was planning on testing and merging but today didn't go to plan :) I'm fine with you doing it tomorrow evening.

**Comment by impaktor** [comment]
OK, I've started merging now, will test all on my local system before I push.

Hold on to your hats people!

**Pull request merged**
