### PR TITLE
Update AppStream destination and filename

### PR DESCRIPTION
**Pull request by reinerh**
the old path is deprecated.
See: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location

### CODE REVIEW

**Comment by Web-eWorks** [comment]
CC @pcercuei regarding flatpak etc. packaging requirements.

**Comment by pcercuei** [comment]
I didn't know about that. Is it just the path that changed, or the format as well?

**Comment by reinerh** [comment]
The format is still the same, only other paths are now used.

**Comment by pcercuei** [comment]
See also: https://docs.flatpak.org/en/latest/conventions.html#appdata-files

So LGTM.

**Pull request merged**
