### PR TITLE
More music

### PR DESCRIPTION
**Pull request by WKFO**
I recreated (and edited a bit) some classical (public domain of course!) music to fill up our music directories! (ah,  s20dan really knew what he was doing with classical pieces)
And guess what... I think I have original stuff on the way so don't merge this yet! No promises though, I just think I have. I can keep you waiting for some time.

Oh, and there was... Uhh... That guy on the dev forum... Who was it... Ha, Gouldenberg! I think we can include some of his work too. I don't know what he is thinking at the moment though.

### CODE REVIEW

**Comment by impaktor** [comment]
Cool!

Please let us know when you're happy with this.

Also, please feel free to open a pull request with Gouldenberg's music. I've listened to it several times, good ambient music for work.

**Comment by WKFO** [comment]
I exported Gouldenberg's tracks in 44100Hz (otherwise Pioneer freaks out) and added the appropriate metadata before uploading so don't worry.

This type of ambient music will make a good change IMO. Extra variation of music + slower and deeper ambiance compared to the current ones. I can include the last track of his album too if Gouldenberg agrees to remove the speech part.

Other tracks are pretty damn nice too but I hesitated a bit because they have a... thing, a feeling... Like they would better fit a surrealist 3D platformer game or sth instead of space ambiance. Or perhaps it is just me. We should discuss.

And if everyone interested takes a look at the PR and says that there is nothing more to do, I think we can merge this.

**Comment by nozmajner** [comment]
One important thing. Those Gouldberg tracks are licensed as CC-BY-NC-SA (non-commercional share-alike), so it should be indicated somehow, that those tracks aren't CC-BY-SA (,commercial sharalike, our default license)

**Comment by WKFO** [comment]
I will add the license info to the metadata. I can also add the entire license text as a file in the /licenses directory.

**Comment by impaktor** [comment]
I think I woudln't mind seeing all the tracks (assuming last track has voice removed) added.

**Comment by impaktor** [comment]
question: ...but how would transitions from non-Gouldenberg music to Gouldenberg tracks contrast?

**Comment by WKFO** [comment]
I think the best way to learn this is actually playing the game with the new tracks added. We can delay the merge as long as we want (right?), just find some time to play the game (like I did before opening the PR) and you will have opinions. We can add any track people like, I like them, but like I said I just hesitated a bit because of the new kind of music.

**Comment by WKFO** [comment]
I imported all of Gouldenberg's album and added the CC-BY-NC-SA-3.0 license to the project and the metadata.

**Comment by laarmen** [comment]
We should not merge non free stuff in the repo. The NC clause is
particularly problematic IMHO as most people aren't really clear as to how
it applies.

Le ven. 26 janv. 2018 à 16:11, Arda Güler <notifications@github.com> a
écrit :

**Comment by WKFO** [comment]
What exactly will we do?

**Comment by laarmen** [comment]
The way I see it, the CC-BY-SA stuff can be merged, but the Gouldberg
tracks should not. If you want them you can add them as a mod (Or can you?
I dunno, I hope so.)

Beside the whole ideological thing, distributing non-free stuff would be a
disservice to our downstream. And we *have* downstream users: IIRC, there
are packages in Arch Linux and Fedora.

**Comment by nozmajner** [comment]
I didn't thought of upstream. I'll ask him on the forum, maybe he would allow it as BY-SA.

**Comment by WKFO** [comment]
No matter what, I want to make a separate PR for Gouldenberg so I removed his work from this PR.

**Comment by laarmen** [comment]
Thanks. Would it be possible to edit your history so that those tracks
don't appear in it at all? If you don't know what I'm talking about, don't
worry about it. Whoever merges this should be able to do it.

Le sam. 27 janv. 2018 à 23:54, Arda Güler <notifications@github.com> a
écrit :

**Comment by WKFO** [comment]
Umm... Yeah, I don't know how to do that.

**Comment by nozmajner** [comment]
[Gouldenberg chimed in on the forum](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=542&p=5523#p5522). His music could be put on the wiki as a mod.

**Comment by WKFO** [comment]
I've uploaded a zip with 44100Hz re-exported tracks to the dev forum.

**Comment by WKFO** [comment]
Umm... If you don't have any other problems with this PR, this is still waiting to be merged. Just wanted to draw attention :)

**Comment by impaktor** [comment]
@WKFO sorry, we move with the lightning speed of a snail. We'll get this merged before next release (which might take a few weeks/months)....

**Comment by WKFO** [comment]
Thanks, it is ok for me to wait as long as it takes, I was just worried that you might have completely forgot about it.

**Comment by WKFO** [comment]
OK, I wanted to tuck in a fifth track to the PR, which will be the second track in ship-nearby (the directory that holds suspensing track(s)).

The only music we currently have in this directory is Gustov Holst's Mars and I didn't want to wander away from the music style, so with majestic french horns and stuff it kind of creates the same atmosphere.

**Comment by fluffyfreak** [comment]
So we have a pile of new music sitting here that looks like it should be ready to merge.

Anyone object to it being merged?

**Comment by impaktor** [comment]
I'm listening to the files now.

For some reason the waltz.ogg file doesn't play for me. Is it corrupt?

**Comment by WKFO** [comment]
I triple checked everything but if someone else confirms the problem I can reupload them.

**Comment by nozmajner** [comment]
VLC plays them on my end, but when it opens in firefox, it only plays the first second or so.

**Comment by WKFO** [comment]
Anything I need to do?

**Comment by nozmajner** [comment]
ping @impaktor: still happens on your end?

**Comment by impaktor** [comment]
Files work when I don't use githubs web gui stuff.

I'll merge shortly.

**Comment by impaktor** [comment]
@WKFO I took the liberty to rebase your branch to master and force push to here, so if you'll get conflicts if you try to push more commits to this branch, (why you would like to do that, I don't know). 

Just letting you know. I assume you'll scrap this branch now that it's merged. 

Thanks for the contribution!

**Comment by WKFO** [comment]
Thanks for help

**Pull request merged**
