### PR TITLE
Ship market

### PR DESCRIPTION
**Pull request by vakhoir**
Added the Ship Market view.
Also contains a minor fix for the model spinner, and a fix for the alignment of the Request Launch button.
Based off the ModalWindow fix branch (#4767)

ShipMarket

### CODE REVIEW

**Comment by impaktor** [comment]
Most excellent! Slowly we're moving closer to be exclusively pigui in our UI.

I've tested it, and seems to work as advertised. I'll be running my pioneer from this branch, for other work, to see if all is well.

(For future: we might want to incorporate a short seller's pitch on each ship (~ a paragraph in length), like it's done for commodity market, but not sure how a string in ship.json would be put into the translation system).

**Comment by vakhoir** [comment]
>  but not sure how a string in ship.json would be put into the translation system

Just have the json contain the translation key to rather than the string itself?

**Comment by Web-eWorks** [comment]
> (For future: we might want to incorporate a short seller's pitch on each ship (~ a paragraph in length), like it's done for commodity market, but not sure how a string in ship.json would be put into the translation system).

Likely we'd make a new translation resource where the raw names of the ships (sinonatrix) is the key, and the message is the sales pitch. Could likely even have two or three variants for each ship, say one for a 'shady' second-hand ship dealer, one for the megacorp dealer, and maybe one for a rimworld chop shop ship dealer.

**Comment by impaktor** [comment]
continuing on this tangent, our current thinking is it should be possible to add ships as modules, so one would have to provide a en.json file as well for each ship (and/or fallback string for missing sales-pitch).

**Comment by Web-eWorks** [comment]
I'm not 100% sure it doesn't already function like this, but it's very easy to allow mods to provide .patch.json extensions to a language resource, whether that's adding additional key-value pairs, changing an existing value, or removing one or more entirely.

So the 'base mod' would provide the translation resource 'ship-sales/en.json' with strings for all the vanilla ships, and mods would include a file with the extra messages that gets merged with the original json file by the loading process.

**Comment by Web-eWorks** [comment]
Everything looks good to me, sorry it's taken so long to merge!

**Pull request merged**
