### PR TITLE
Fix for #3602 and #3517

### PR DESCRIPTION
**Pull request by robothauler**

### CODE REVIEW

**Comment by impaktor** [comment]
Fast and sweet, great!

I'd like to run it by @nozmajner before merge, if the different size of buy/sell (to mark which is  selected) is a feature?

screenshot-20160123-145627

Nothing to sell:
screenshot-20160123-145704

**Comment by nozmajner** [comment]
Yeah, that small/big button looks a bit odd, but other than that it looks good in my opinion.

**Comment by impaktor** [comment]
I wonder if "we" could implement an invisible/borderless button type so it would look like in:
Buy "tab"

I guess, just check what makes a gray button gray, and make it look invisible (background blue) instead? I expect that to (maybe) be on the C++ side. Perhaps for another day. This PR was just opened afew hours ago, so let's se what others say.

**Comment by robothauler** [comment]
The different size of the buttons should be a visual indicator of the mode (buy/sell).
Just for completeness, the sell mode.

screenshot-20160123-152621

**Comment by impaktor** [comment]
I've implemented the Invisible state, here is in-game screen shot:
screenshot-20160123-165942
screenshot-20160123-165920

screenshot-20160123-165922

PR on the way.

**Comment by fluffyfreak** [comment]
@impaktor So is this for review or will you merge it at the same time as #3605?

**Comment by impaktor** [comment]
We could either merge it now, or if #3605 goes in first, this PR should make use of that feature and be updated. I'm fine with this being merged now. It does fix a bad bug, so it has that going for it.

**Comment by fluffyfreak** [comment]
done :)

**Pull request merged**
