### PR TITLE
Consider thruster upgrade

### PR DESCRIPTION
**Pull request by robothauler**
Uses methods from LuaPlayer.cpp to calculate acceleration and delta v.
Fixes also the atmo shield info.

### CODE REVIEW

**Comment by impaktor** [comment]
Code looks OK to me.

Have you tested that you get the same DeltaV now as before? (suggestion: use `print()` on version of script that has both old and new way of computing it). Asking as a way to make sure the Get method does the same thing as the manual calculation.

**Comment by mike-f1** [comment]
There's plenty of those methods, but evidently not all are working: see #4545

**Comment by robothauler** [comment]
The Get method and the manual calculation return the same DeltaV.

**Comment by mike-f1** [comment]
> The Get method and the manual calculation return the same DeltaV.

@robothauler , may I ask if you have time/will to update methods used in "comm screen"?
Thus with this PR issue #4545 can be closed :wink: ...not a "must", anyway.

**Comment by robothauler** [comment]
> > The Get method and the manual calculation return the same DeltaV.
> 
> @robothauler , may I ask if you have time/will to update methods used in "comm screen"?
> Thus with this PR issue #4545 can be closed wink ...not a "must", anyway.

Sorry, I think this is beyond my skills at the moment.

**Comment by mike-f1** [comment]
Ops, I didn't understand what happen here... But not a problem:
I did some investigation and it seems that the "right" method cited in [that](#4545) issue is:
https://github.com/pioneerspacesim/pioneer/blob/3a314cf28ba1ecbd97c4c2a9d8c638d58a3d89bb/src/SectorView.cpp#L1169-L1171

Thus I feel is worth to check if this should be used instead.

>Sorry

For what? I give the wrong hint, I should be sorry :wink:

**Pull request merged**
