### PR TITLE
Show surface starports in the system map

### LINKED ISSUE #5058: System viev: Destinations on ground are not marked
### Observed behaviour

Set a starport on ground as destination, switch to system view: no destination is marked
(but works if the body is the destination)

### Expected behaviour

Same as if an orbital starport is the destination

__My pioneer version (and OS):__
20201206 on SuSE Linux

### PR DESCRIPTION
**Pull request by Gliese852**
surf-starport
Fixes #5058

### CODE REVIEW

**Comment by fluffyfreak** [comment]
@Gliese852 well done! There needs to be a little applause emoji 👏oh there is! 😂

**Comment by Gliese852** [comment]
@fluffyfreak this is very nice!

**Comment by Gliese852** [comment]
Corrected something, namely, determining the distance to the center of the planet. If the current system is viewed, the height is taken from the physical body

**Comment by Bodasey** [comment]
Many many thanks, tested this function a bit, can be played as used to, no new bugs found.

**Comment by impaktor** [comment]
People have started playing with this in IRC, so I say this is play/bug-tested for merge. @fluffyfreak you want to glance over the code (32 lines) before we merge?

**Review by fluffyfreak — APPROVED** [review]
All looks good to me

**Review by Web-eWorks — APPROVED** [review]

**Pull request merged**
