### PR TITLE
Smaller orbital station

### PR DESCRIPTION
**Pull request by nozmajner**
I played around with the existing station parts and made a smaller orbital station using them.
It has one section of docks, with 18 bays: 1 large, 8 medium and 9 small.
The diameter is about 4km, and it spins at 0.6 rpm, providing 0.8G at the outter rim.
I made a new, smaller habitat ring for it, using the already existing textures. Same goes for the whole model, I just shifted around parts, to avoid making any new textures.
On my copy Eagle's Nest in Epsilon Eridani and the Barnard's starting point is this station.
screenshot-20150628-163546
screenshot-20150628-163648
screenshot-20150628-163751
screenshot-20150628-163805
screenshot-20150628-163904
screenshot-20150628-164006

### CODE REVIEW

**Comment by impaktor** [comment]
nozmajner reported earlier today that the station was going crazy over the collision mesh.

@jmf's interpretation:
dxdo7qd

**Comment by walterar** [comment]
Looks good. But the station entrance is backwards. Static ships will must be parked at the entrance. Besides, #3344 is still there.

**Comment by nozmajner** [comment]
The above commit rotates the docking entrances so they are lined up with the static ships. For consistency's sake, because I'm not that convinced that static ships have their place only at the entrance. As in: they never enter the station, but clutter up the approach area.

Can't do anything about #3344, the autopilot still goes nuts if I rotate those markers, and tries to enter backwards from the other direction.

**Comment by fluffyfreak** [comment]
Yeah don't try to correct #3344 in the model I just need to find time to fix the code I guess.

**Comment by walterar** [comment]
@nozmajner It's OK now. :+1: 

big-pos-ok

"I'm not that convinced that static ships have their place only at the entrance"

For that, in the future, it would be good to change SpawnShipParked

ship = Space.SpawnShipParked (type, station)
to
ship = Space.SpawnShipParked (type, station, position)

@fluffyfreak 
"I just need to find time to fix the code I guess."

May you find time. This model will look much better then. :+1:

**Comment by walterar** [comment]
@nozmajner 
You have achieved ships correctly positioned in this station. With the nose pointing toward the exit. See difference with the other stations.

**Comment by impaktor** [comment]
Merged!
(rebased the last two commits, thus closing through commit message instead)

**Pull request closed without merging**
