### PR TITLE
Add GZipFormat source files to VS2015 Solution

### PR DESCRIPTION
**Pull request by The-EG**
Added following files to the Pioneer project within win32/vs2015/pioneer.sln:
  src/GZipFormat.cpp
  src/GZipFormat.h

This fixes building on Windows within VS2015.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
Thanks @The-EG and Merry Christmas :)

**Comment by fluffyfreak** [comment]
Also @The-EG what name do you want to be known in the [`AUTHORS.txt`](https://github.com/pioneerspacesim/pioneer/blob/master/AUTHORS.txt) file as?

**Comment by The-EG** [comment]
@fluffyfreak you can put my real name in: Taylor Talkington
Thanks!

**Comment by fluffyfreak** [comment]
Done and Done 😁

**Pull request merged**
