### PR TITLE
Make F3/F4 toggle instead of activating the view.

### PR DESCRIPTION
**Pull request by ecraven**
F3/F4 now switch back to the world view, if they are already active.

### CODE REVIEW

**Comment by impaktor** [comment]
I like it. Using it I realize I've wanted this a very long time. My only criticism is that the player expects F2 to also be toggable, which it isn't since you need to go F2->F1.

**Comment by ecraven** [comment]
F2 already toggles between the different tabs, so I did not touch that. Maybe later these things should be unified :)

**Comment by impaktor** [comment]
My F2 doesn't toggle, but once in F2 I can F5,F6,F7. And one or two of those toggle tabs. Not sure what would be best. Ping @nozmajner.

**Comment by ecraven** [comment]
F2 > F7 > F2 F2 F2 toggles :)

**Comment by impaktor** [comment]
Sometimes my F-keys aren't working properly. 

But since this only adds features, that will be discovered by players assuming it's there, I'll merge right away. As I said in the first post, I'm one of them, constantly pressing wrong button to get back to Worldview.

**Pull request merged**
