### PR TITLE
Station Police view has tabs: 1. crime records, + new: 2. rules & regulations

### PR DESCRIPTION
**Pull request by impaktor**
I found this 4 year old branch. I figured I could fix it up and PR it.

This aims to show more clearly what rules the player need to be weary of. Changes:
- Put existing police stuff in "Crime record" tab
- New tab, lists legal offenses, and the fine at the station

(Never mind my [Evarchart](https://forum.pioneerspacesim.net/viewtopic.php?f=8&t=382) facemod)
2024-07-12-113745_1295x659_scrot
2024-07-12-113757_1280x648_scrot

### CODE REVIEW

**Comment by impaktor** [comment]
thoughts:
- I'm not sure fontsize is correct.
- Could also add illegal goods as well.

**Comment by impaktor** [comment]
Like so
2024-07-12-143455_1286x658_scrot

**Comment by Web-eWorks** [comment]
Will review this after the UI theme PR is merged. I like what I'm seeing here, but some areas could have improved formatting - I'll see if I can address that.

**Comment by zonkmachine** [comment]
Looks nice! I would consider sorting the lists.

**Comment by impaktor** [comment]
rebased to new theme on master. No changes beyond that....
(policeman have not mouth.... and he must scream)
2024-08-22-132058_1372x698_scrot

**Review by Web-eWorks — APPROVED** [review]
Going to be cheeky and approve my own changes here too - made stylistic and textual changes as needed for a uniform standard of quality across the entire tab. This PR is definitely a good change, but the whole station view UI is desperately in need of a redesign in the long term.

Final(ish) appearance:

image

image

image

**Comment by Web-eWorks** [comment]
And yes, the faces are different in each screenshot because every time you reload the police tab, the station gets a different constable :smile:

**Pull request merged**
