### PR TITLE
boot screen visuals take2

### PR DESCRIPTION
**Pull request by joonicks**

### CODE REVIEW

**Comment by fluffyfreak** [comment]
It's better to fixup a PR than to close (#3461) and open a new one because otherwise the conversation is lost and tracking progress is harder.

**Comment by fluffyfreak** [comment]
Also what has a1c5f30 got to do with the lading screen? Has it mistakenly made it's way into this commit?

**Comment by joonicks** [comment]
yeah. guys have patience with me ok? Im new to pioneer, msvc, C++, blender, github... gimme a week to learn a little bit, ok?

**Comment by fluffyfreak** [comment]
Don't worry you're doing good, I was all ready to merge the other #3461 PR as I thought it was good enough to start with. Just commenting so that you know you don't have to close and restart PRs (unless you want too).

**Comment by joonicks** [comment]
yes I closed it because I wanted to withdraw that pull request and replace it with the new one. and I tried to split the other thing from the request as well but apparently it still got attached.

**Pull request closed without merging**
