### PR TITLE
The Great Disinheritance: make Propulsion a component

### PR DESCRIPTION
**Pull request by ecraven**
This is the start of an effort to remove the inheritance relationships and replace them by composition.

### CODE REVIEW

**Comment by mike-f1** [comment]
Well, probably a lack of knowledge by my side, but I have 2 question:
a) what are the pros (I mean: the criteria you use to decide if composition is better here)?
b) why right now immediately after your great work on UI (I mean, seems like you're in a big hurry to change this...)?

**Comment by ecraven** [comment]
My main reason is that inheritance feels totally wrong to me here, a Ship *is* *not* a propulsion or a fixed guns, it just has those (maybe even multiple).
I'd like to clean up the general codebase, not just work on UI (I actually like other things more than UI, but can't implement them without UI parts, so....)

**Comment by mike-f1** [comment]
> My main reason is that inheritance feels totally wrong to me here, a Ship is not a propulsion or a fixed guns, it just has those (maybe even multiple).

...probably you're right, but a *feel* could or could not be right: there're symptoms anyone can see.
Would you explain more deeply the reason behind your feel?

> I'd like to clean up the general codebase, not just work on UI (I actually like other things more than UI, but can't implement them without UI parts, so....)

Oh: so you're "able&free" to change things like that here and there in code, nice!
...There's a hint, if I may: #22

**Comment by ecraven** [comment]
> Would you explain more deeply the reason behind your feel?

Well, in the far future, I think we should move to an entity component system, which means splitting up things into "components". Then some c++ code could just loop over all the propulsions and calculate their new values (which should be much faster due to cache coherence and data locality) than iterating over everything (as happens now). Read up on ECS for the benefits.
Also, with the current deep inheritance hierarchy, it can be a bit hard to tell where (= which of the ten base classes) a function actually comes from :-/

**Comment by mike-f1** [comment]
>Well, in the far future, I think we should move to an entity component system, which means splitting up things into "components"

...as I did... but... inheriting :P
By the way I think it was an interesting issue to solve (#2012), opened years ago... Nobody care, nobody read... For years.
Then I ask on IRC, I listen answers, I spent my (free) time coding, ending up with a solution.

>Then some c++ code could just loop over all the propulsions and calculate their new values (which should be much faster due to cache coherence and data locality) than iterating over everything (as happens now)

Do you think it's a task impossible to do with current code?

> Also, with the current deep inheritance hierarchy, it can be a bit hard to tell where (= which of the ten base classes) a function actually comes from :-/

...Yeah: this is the reason I leave the majority of function name with Propulsion::* : to avoid misleading.
But again: if your're worried by the deep of class hierarchy, then please note I shorten it by 1 (one) and there's an issue (the one I told you above) opened years ago (...as the one I solved...)
..10? Where?

...Just to better share thoughts, I found this article in GameDev:
https://www.gamedev.net/resources/_/technical/game-programming/understanding-component-entity-systems-r3013, is this your source? ...or at least: you agree it's a valid source?

**Comment by laarmen** [comment]
Skimming through the article, I'd say it is a fair description of what's
going on here.

All in all, I'm personally in favor of using composition. And @ecraven
didn't say the iteration was impossible today, just that it wasn't really
cache-friendly.

**Comment by fluffyfreak** [comment]
@ecraven so how is this branch? Does it still need the WIP tag?

**Comment by ecraven** [comment]
WIP removed. I'm good to go with this, I'll try to do similar things to other places where I notice this.

**Comment by mike-f1** [comment]
> All in all, I'm personally in favor of using composition

UaO, @laarmen : another people coming up with feels, don't know but at this stage I would expect a deeper judge on my work :P

>And @ecraven didn't say the iteration was impossible today, just that it wasn't really cache-friendly.

Well, probably I didn't explain my thought so well, so I would try again: I'm stating that you can obtain the same also with inheritance.

...Conclusion: you aren't unable to provide a technical reason to replace inheritance with composition.

More: you have to forward every method from "so called components" to obtain the same

More: you haven't realized that ship "is-an" object that needs an interface to provide some propulsion.

More: you aren't worried to modify code provided from coders around for... no reason.

Thus: you aren't talking, you are dictating.

But (and now I speak about how *I* feel), it seems you (guys) are in a need of
help by coders around: and, as a "coder around", I think I can give you a feedback
about my experience with you.

Well, I don't want or think my code will survive to eternity, but if someone do something
for you (wasting its free time), then I don't think he will be happy seeing you have any
respect for his work: changing his code in *no time* (hurry up @fluffyfreak & have fun! ;)
for nothing more than just *feels*...

Your aren't telling people this, and this at least for me, is not right.

**Comment by fluffyfreak** [comment]
@mike-f1 it's not a comment on your work, which is great.
This PR is just about the fact that it increases the depth and complexity of the inheritance for these classes.

A way of avoiding that complexity to use an entity component system which this does.
The use of the word "feels" isn't avoiding discussion of the technical situation, it's the answer too it: _the inheritance is complex, the component system **feels** better to use in this case because it is less complex._

Also I don't know why you keep referencing me in comments like:
> changing his code in no time (hurry up @fluffyfreak & have fun! ;) for nothing more than just feels...

Did I do something to annoy/wrong you? I respond to questions and I answer everything that I can although I don't always understand some of what you have written.

**Comment by fluffyfreak** [comment]
@mike-f1 also you shouldn't expect code you've done to be left unchanged.
When you change code and add features, people want to use them, it shows interested people areas of code that might need other work doing to them.

As a consequence of that I've had code completely rewritten within days of a PR being submitted.

I've also learned over the years to work on Pioneer at the pace that **_I_** am happy with and not what others would prefer. This is my hobby, and whilst my personal life is in turmoil it will get less attention.

**Comment by mike-f1** [comment]
> I'll try to do similar things to other places where I notice this.

:P ...@ecraven do you heard about OOP or you *really* want to end up with "structs" & C?
You could start changing "class Object" into "struct Object" :D

**Comment by fluffyfreak** [comment]
@mike-f1 that's not a very friendly tone.
Also entity component systems are a well established programming paradigm, OOP isn't a paradigm to be slavishly followed and deep inheritance of objects have well documented drawbacks.

I can't tell if you're joking/trolling here or not.

**Comment by mike-f1** [comment]
@fluffyfreak :
> @mike-f1 it's not a comment on your work, which is great.

False: you *feel* the need to change it after a couple of months...

> This PR is just about the fact that it increases the depth and complexity of the inheritance for these classes.

False :P ...read carefully: it is the opposite

> A way of avoiding that complexity to use an entity component system which this does.
The use of the word "feels" isn't avoiding discussion of the technical situation, it's the answer too it: the inheritance is complex, the component system feels better to use in this case because it is less complex.

False: I don't think you could escape complexity, you could do a good job in managing it....
For example avoiding forwarding *all* methods of "so called components" for every object:
that is complex!

> so I don't know why you keep referencing me in comments like:

...Because "Working on Pioneer should be fun!", and seeing you asking to shorten the talk
and pushing for merge is all but not fun :P

> @mike-f1 also you shouldn't expect code you've done to be left unchanged.

But I hope if it needs to be changed, it should be for good reason...

**Comment by mike-f1** [comment]
> @mike-f1 that's not a very friendly tone.

"The Great Disinheritance: make Propulsion a component"

**Comment by fluffyfreak** [comment]
> ...Because "Working on Pioneer should be fun!", and seeing you asking to shorten the talk and pushing for merge is all but not fun :P

So you don't want your work merging?
I don't say that something is good and would like to see it merged becuase I want you to rush, it is **encouragement** to show you that **we like what you're doing**.

> "The Great Disinheritance: make Propulsion a component"

We come up with funny titles for PR's #4005 was originally titled "_Pop goes the weasel_", it is for fun.

**Comment by fluffyfreak** [comment]
@mike-f1 also I did reply in this comment https://github.com/pioneerspacesim/pioneer/pull/3952#issuecomment-298762921 saying to take as much time you needed and that we've had long running PR's in the past.

I'm trying to be as nice and helpful as I can.

**Comment by mike-f1** [comment]
@fluffyfreak : I think your teammate deliberately choose this title to be offending: this is a kind of "Wall of Shame" in which he want to change my code.

A proof is that after you (aware of not, I don't know or care) ask for merge, he comment
> I'll try to do similar things to other places where I notice this

WTF?

And he feels "ok with this", even if he (...and finally you guys) don't provide nothing to prove this is better.

WTF?

So: I spent time working on code (and *I*'m sure is good, you still have to prove the opposite),
for what? To see someone ruining all for... nothing?

...Don't know: if you think that merging this is "polite" or "fun"... merge it, I'm leaving

No offense but Good bye

**Comment by ecraven** [comment]
@mike-f1 I'm sorry for any misunderstanding I might have caused, I'll try to address a few points here:

>  I think your teammate deliberately choose this title to be offending: this is a kind of "Wall of Shame" in which he want to change my code.

That was absolutely not my intention, I thought it sounded funny, in the tradition of other PRs as @fluffyfreak mentioned.

I also did not just pick *your* code to change, but looked for a place where not a lot of changes were necessary (for example making Ship a component of Player is a much larger change, but still one I would like to make).

> ...Conclusion: you aren't unable to provide a technical reason to replace inheritance with composition.

I don't think that is exactly the case, I've tried to address the questions, and I'll try some more.

 > More: you have to forward every method from "so called components" to obtain the same
Yes, this is not a good thing to do, ideally the component should be mostly self-contained, and only be referenced by its "systems". However, it is hard to do this in an existing codebase with few changes, so we'll need time to actually get there :-/

> More: you haven't realized that ship "is-an" object that needs an interface to provide some propulsion.

As far as I understand (and I might be totally wrong here), in an ECS, that is not actually what you want. You want an entity (a ship in this case) to have multiple components (one of which is a propulsion). The *entity* does not provide any methods, but the *component* does. The reason for this is performance in iterating over the components, which is definitely faster than iterating over larger objects, due to cache sizes and locality (given that components are stored correctly, which we do not currently do, but can only do if we actually *have* components). 

> More: you aren't worried to modify code provided from coders around for... no reason.

Yes, I'm definitely not worried about moving code around. I haven't actually *changed* any code, just moved it to a different place. I also have absolutely no problems with others changing my code. This project has seen a lot of people working on it, and will see a lot more.

You are correct that there is no urgent reason to change this right now, nothing bad will happen if we don't merge this, but I honestly believe that for the future development of pioneer, this is not a bad change.

I am truly sorry if I have offended you, it was not my intention at all. You have contributed great ideas and code to Pioneer, I haven't picked your code on purpose to pick on you. I hope we can find a way to continue working together!

**Pull request merged**
