### PR TITLE
Fix for medical emergency mission

### LINKED ISSUE #4601: Medical emergency is broken
### Observed behaviour
Landing next to the target ship where medical attention is needed does trigger a "please allow 0.0 minutes for transfer" message, and then nothing happens.

### Expected behaviour
Something happens.

### Steps to reproduce

Start a new game on Mars. Accept a medical emergency mission. Navigate to the ship in distress. Land asides it.

This is my savefile to make it easier to reproduce the bug: https://app.box.com/s/m0t8kx4mlq7pk9obutgynmwtsshtch74

__My pioneer version (and OS):__
master branch (4c51f4eff), Debian 9 64-bit

### PR DESCRIPTION
**Pull request by robothauler**
Fixes #4601

### CODE REVIEW

**Comment by impaktor** [comment]
Looks like a no-brainer, so should be safe to merge.

The second fix, is just a forgotten debug line, I take it.

Good work!

Btw, from a code symmetry perspective, there's not a similar bug with `pickup_crew`? (I haven't checked thoroughly, but just seems like those three variables are set/loaded together, but not in that if-statment).

**Comment by robothauler** [comment]
Indeed. Looks like there is also something missing. But at the moment there are no missions with a fixed number of crew people to pick up.

**Comment by mike-f1** [comment]
If I may, I would suggest to glance again https://github.com/pioneerspacesim/pioneer/pull/4579#issue-276010655...

Here the relevant line:

>error: [string "[T] @modules/SearchRescue/SearchRescue.lua"]:544: attempt to perform arithmetic on local **'pickup_crew'** (a nil value)

...Just to pin & share toughts...

**Comment by robothauler** [comment]
OK, just in case. Last commit should work. Not tested. :-)

**Pull request merged**
