### PR TITLE
Fix audio quality of a music track

### PR DESCRIPTION
**Pull request by WKFO**
Fixing the audio quality of a music track.
Docking to space stations should feel like coming home.

Again, my compliments to @s20dan :) (Is he even alive?)
EDIT: Firefox doesn't play the file on my end no matter what I did. You may need to download it.

### CODE REVIEW

**Comment by impaktor** [comment]
Cool. My headphone jack lives a life of its own, I'll have a listen when I'm not at work...

**Comment by WKFO** [comment]
Yes, we could use some music for near-planets, I am aware.

But for undocking, IMHO we should leave it empty. Changing music so often can be disturbing. I sometimes stop at space stations like they are pit-stops, just to get fuel and keep jumping towards my destination. Not anything like this: https://youtu.be/-p1hxvPOIhE?t=1m4s

**Comment by richardpl** [comment]
Are you going to make more changes to this PR? I do not want to make extra git history for binary files.

**Comment by WKFO** [comment]
No, this is it. Just a fix.

**Pull request merged**
