### PR TITLE
 Split the flightstate DOCKING into an UNDOCKING state as well

### LINKED ISSUE #3480: Undocking is called "Docking"
during undocking at an orbital space station, it displays "Docking" in the control status

### PR DESCRIPTION
**Pull request by impaktor**
The UNDOCKING state behaves identical to DOCKING for now, except it shows the text "UNDOCKING" when so doing.

Thus this cosmetic modification fixes #3480.

Also, some indentation fixes (some were space indented, others were not-width-4 indented), which of course looks a bit wonky in github diff since it uses tab 8, which is also the default for git, unless you've done:

    git config --global core.pager 'less -x1,5'

Which I recommend all contributors to do.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
@impaktor this looks fine code wise but you'll have to test the docking/undocking behaviour for ground & orbital stations for yourself and AI ships. That whole system is very finicky.

**Comment by impaktor** [comment]
I've tested ground and orbit station for player ship, but not AI (yet)

**Comment by impaktor** [comment]
OK, I've tested Undocking AI ships as well now, both from ground, (London), and Orbital (Barnard's).
Works. 

Code I used for testing was put in a module:

```lua
local onestation
local onShipUndocked = function (ship, station)
	onestation = station
end

local Space = import("Space")
local oneship
local onJettison = function (ship, cargo)
	oneship = Space.SpawnShipDocked("natrix", onestation)
	oneship:Undock()
end
Event.Register("onJettison", onJettison)
Event.Register("onShipUndocked", onShipUndocked)
```

**Comment by impaktor** [comment]
(The only change in my last commit that I just updated is I reworded the commit message)

**Comment by fluffyfreak** [comment]
Cool then mergy mergy time!

**Pull request merged**
