### PR TITLE
Search&Rescue module: stop tracking destroyed ships

### LINKED ISSUE #3694: Save and land bug - game show error and exit
Hello.

I have a mission, from Pluto research base to Sirius. But when I do hyperjump to Sirius system and try to land, game says there is a problem with serializing 'Ship' object. I tried to jump into Sirius system and save game, but same error happend.
I run Pioneer under Linux, from top of git reposity. Last git fetch and merge - today morning (7th May).

My save from Pluto Research base: http://147.229.208.36/pioneer/SIRIUS_LAND_SAVE_BUG

I tried both of target mission bases. No one works.

### PR DESCRIPTION
**Pull request by clausimu**
This fixes #3694. References to mission target ships that were put on the "discard pile" were kept for serialization even if they got destroyed in the meantime. This caused a game crash during serialization.

@walterar figured this out (thanks!!). I am using a different approach to solve the issue than in his Scout+ version of the Search&Rescue module though. He considers it a serialization bug and would discard the references to destroyed ships within the serialization function. He did remove my "discard pile" approach altogether from his script version. I consider it a weakness of the script itself to track destroyed ships and have therefore included the cleanup in the "onShipDestroyed" function.

### CODE REVIEW

**Comment by impaktor** [comment]
Sweet.

I took the liberty to edit your first sentence, so that it will [auto-close](https://help.github.com/articles/closing-issues-via-commit-messages/) the original bug report.

**Comment by clausimu** [comment]
@impaktor - you are right, #3769 is included here because I created this branch out of the other (instead of the master branch). I need to submit more code so I remember these things :). Thanks for closing #3769.

**Comment by walterar** [comment]
:+1:

**Comment by impaktor** [comment]
OK, it's up to this branch to resolve the merge conflict.

Either update your master, and merge it into this branch, and resolve the conflict that is to follow, or reset this branch with a `git reset --hard uppstream master` (after a `git pull` on master) or something similar, and then redo the two commits. Last commit can be cherry-picked I think. Anyway, if you need help, you'll probably find me on IRC.

**Comment by impaktor** [comment]
Merged it, but I ended up doing a rebase, to merge the trailing space commit in the other commit, thus this says "closed" rather than "!merged". 

Thanks for the fix and cleanup!

**Pull request closed without merging**
