### PR TITLE
Deny docking requests too far from station

### PR DESCRIPTION
**Pull request by WKFO**
I thought reserving a docking port from 11AU was insane and space stations' air traffic controllers shouldn't grant such clearances. If I were them, I wouldn't. Would you? (I would be suprised if someone requested clearance from 500.000km away and made it in time.) I might just need a more proper excuse to deny those requests, though (current message is a placeholder). Come up with a good excuse and I will change the message :)

'Too far' as in 'more than 100km'. Which is a long enough braking/slow-travelling distance in my opinion.

### CODE REVIEW

**Comment by WKFO** [comment]
WHOA! Conflict?

**Comment by fluffyfreak** [comment]
@WKFO Nothing to worry about, just that the language files got updated.

**Comment by WKFO** [comment]
Okay, it was just unexpected.

**Comment by nozmajner** [comment]
@WKFO: does the 'Dock with" autopilot knows about it?

**Comment by WKFO** [comment]
'Dock with' autopilot doesn't know about it on the code side but it requests for docking at 15km distance.
Tested it tens of times, had no problem so far.

**Comment by nozmajner** [comment]
Cool.

**Comment by richardpl** [comment]
This can not be merged as branch have conflicts.

**Comment by WKFO** [comment]
Okay, will try to fix.

**Comment by WKFO** [comment]
I don't know what I just did but it showed like the entire files was replaced. Reverting...

**Comment by richardpl** [comment]
Merged.

**Pull request closed without merging**
