### PR TITLE
Make modelcompiler handle custom data dir

### PR DESCRIPTION
**Pull request by Web-eWorks**
This PR adds logic to handle a custom, command-line specified data directory when the modelcompiler is being used as a build tool. The new syntax is `modelcompiler -b /path/to/data`.

CC @orbea

### CODE REVIEW

**Comment by fluffyfreak** [comment]
Looks good to me

**Comment by impaktor** [comment]
fluffy is the only gatekeeper for this change, so I won't ask about your favourite colour...

Nice, both Travis and appveyor building it now.

**Comment by pcercuei** [comment]
Would it also be possible to specify a custom destination directory? That way it can be set to output to the build directory and not the source one.

**Comment by Web-eWorks** [comment]
@pcercuei That would require changes to `scenegraph/BinaryConverter.cpp`, which is beyond the time and ability I have available right now. Additionally, we don't maintain two different data directories, so it's not particularly worth the effort to have it output into a different directory.

**Comment by impaktor** [comment]
ready to merge?

**Comment by orbea** [comment]
@Web-eWorks I noticed now that this was merged, was this ever investigated further?

**Comment by Web-eWorks** [comment]
@orbea I have not had the chance to take a look at it yet. Refactoring the internals of the model / scenegraph system is a fairly large task, and I just haven't had the motivation yet.

**Comment by orbea** [comment]
Fully understandable, thanks for the update!

**Pull request merged**
