### PR TITLE
isFile check for ReadFile (fix for macos crash)

### PR DESCRIPTION
**Pull request by ColdSpirit0**
For posix now, I'll test win32 and then will be possible to merge.

### CODE REVIEW

**Comment by ColdSpirit0** [comment]
That bug does not exists on windows 7, but better to test it also on other windows versions.

**Comment by Philbywhizz** [comment]
Tested under MacOSX and it works as designed.

**Comment by jaj22** [comment]
Minor bug: This code doesn't call fclose if it opens a directory.

I think it's cleaner to use stat_path before opening rather than stat_fd after opening.

**Comment by ColdSpirit0** [comment]
All edits done

**Comment by impaktor** [comment]
@jaj22 do you have any further objections, or good to merge?

@ColdSpirit0 was this bug reported on the tracker somewhere? (Doesn't look like it.)

**Comment by ColdSpirit0** [comment]
@impaktor no, it was not reported as a separate issue, but you can see some info about that bug in #4174

**Comment by jaj22** [comment]
@impaktor good to merge.

@ColdSpirit0 I would also recommend a related fix to LuaUtils.cpp: If ImportInfo.isFullName is false, it shouldn't attempt to open the file as if it's a full name. That's the i==0 part of the loop at line 342.

**Comment by ColdSpirit0** [comment]
@jaj22 im think i did not understand you. When isFullName is true, that means import should load only by given name, when it's false, means import should build relative paths and try to load each of them.

**Pull request merged**
