### PR TITLE
New transifex config, yaml

### PR DESCRIPTION
**Pull request by impaktor**
New transifex config file, as old seems to have been deprecated, and new strings are not being pushed back to github.

## Reason
Since I pushed f0478a57c adding scout module, three days ago, transifex hasn't updated - neither the `module-scout/*json` nor any other module that has been translated since then (e.g. `ui-core/*json`).

## cause?
Transifex deprecated their API [November 30th](https://community.transifex.com/t/reminder-deprecated-transifex-apis-and-transifex-client-to-be-discontinued-on-nov-30-2022/3079) last year, possible the github link figured out it should break now?

I note, when I added the scout en.json on the transifex side, the UI had changed and there was less setting up, possibly, because these settings should now be in yaml file?

## fix
Either way, this removes the old config, and adds the new config in the project root, since it's the new default transifex path (but I could place it anywhere, doesn't matter).

With this change, I might break things more, or fix them.

I've read through the [docs](https://help.transifex.com/en/articles/6265125-github-via-transifex-ui#h_de29ef5cec), but one thing that's unclear to me: in some of their example yaml files, `git:` is the top node in the yaml file. Sometimes not. I don't know what's right or wrong, but when I link it in transifex, it will validate the file, so might find out then.

Maybe @ecraven, as transifex adm, wants to be pinged?

### CODE REVIEW

**Comment by impaktor** [comment]
Spoke to ecraven, and things are comming back to me know. I think he inherited a script from rob, that pulls and pushes new strings (03:00 CET every day):
```
#!/bin/bash
# add to config
# Host pioneer-transifex-github
#   Hostname github.com
#   User git
#   IdentityFile ~/.ssh/pioneer-transifex.id_rsa

set -x
set -e

cd /home/nex/pioneer

if [ "$1" = "init" ]
then
    git clone --depth=1 git@pioneer-transifex-github:pioneerspacesim/pioneer
    cd pioneer
    git config user.name 'Pioneer Transifex'
    git config user.email 'pioneer-transifex@pioneerspacesim.net'
else
    cd pioneer
    git fetch
    git reset --hard origin/master
    tx push -s
    tx pull -a
    for i in $(find data/lang -name '*.json')
    do
        jq -S . < $i > /tmp/${i//\//_}
        mv /tmp/${i//\//_} $i ;
    done
    git add data/lang/
    git commit -m 'auto-commit: translation updates'
    git push
fi
exit 0
```

probably when he made the initial move from newui to pigui, we needed to push finished translations back to transifex to new location.

Anyway, current situation:
```
<ecraven> tx pull and tx push fail 
<ecraven> I don't have time tonight, can we talk tomorrow during the day?
```

**Comment by Web-eWorks** [comment]
Merging this - it can be reverted in a follow-up commit if necessary.

**Comment by impaktor** [comment]
# Post-merge report:

For documenting purpose, this PR caused - upon merge & validation of the yaml file - Transifex to pull all our en.json files to new modules prefixed by `data..<name>` on transifex side:

```
- data..commodity/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-commodity-en-json--master/
- data..core/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-core-en-json--master/
- data..equipment-core/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-equipment-core-en-json--master/
- data..input-core/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-input-core-en-json--master/
- data..module-advice/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-advice-en-json--master/
- data..module-aiwarning/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-aiwarning-en-json--master/
- data..module-assassination/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-assassination-en-json--master/
- data..module-breakdownservicing/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-breakdownservicing-en-json--master/
- data..module-cargorun/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-cargorun-en-json--master/
- data..module-combat/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-combat-en-json--master/
- data..module-crewcontracts/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-crewcontracts-en-json--master/
- data..module-deliverpackage/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-deliverpackage-en-json--master/
- data..module-donatetocranks/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-donatetocranks-en-json--master/
- data..module-fuelclub/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-fuelclub-en-json--master/
- data..module-goodstrader/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-goodstrader-en-json--master/
- data..module-newseventcommodity/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-newseventcommodity-en-json--master/
- data..module-policepatrol/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-policepatrol-en-json--master/
- data..module-rondel/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-rondel-en-json--master/
- data..module-scoop/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-scoop-en-json--master/
- data..module-scout/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-scout-en-json--master/
- data..module-searchrescue/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-searchrescue-en-json--master/
- data..module-secondhand/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-secondhand-en-json--master/
- data..module-soldout/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-soldout-en-json--master/
- data..module-stationrefuelling/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-stationrefuelling-en-json--master/
- data..module-stationtrafficcontrol/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-stationtrafficcontrol-en-json--master/
- data..module-statstracking/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-statstracking-en-json--master/
- data..module-system/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-system-en-json--master/
- data..module-taxi/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-module-taxi-en-json--master/
- data..quitconfirmation-core/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-quitconfirmation-core-en-json--master/
- data..ui-core/en.json (master) https://www.transifex.com/pioneer/pioneer/data-lang-ui-core-en-json--master/
```

thus doubling our number of strings, but translations are in memory, so they were auto-translated, so no big issue. However, the real big problem is that it then starts pushing the strings back to github, but not to the `data/lang/module-<name>/` folder as was intended, but to `module-<name>/` folder, where we have the lua code.

I've un-linked the transifex bot, and we will pursue getting the tx/config file to work, and this commit has been removed from the repo, as we had to clean up git history from hundreds of transifex commits.

## Appendix
Btw, the yaml file that was merged, was initially invalid, due to missing top level `git:`-node, and a typo. In case this is of interest to the future me, or someone else, below is the valid version:

```yaml
git:
    filters:
        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/core/en.json
          translation_files_expression: 'data/lang/core/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/ui-core/en.json
          translation_files_expression: 'data/lang/ui-core/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/equipment-core/en.json
          translation_files_expression: 'data/lang/equipment-core/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/input-core/en.json
          translation_files_expression: 'data/lang/input-core/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/commodity/en.json
          translation_files_expression: 'data/lang/commodity/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/quitconfirmation-core/en.json
          translation_files_expression: 'data/lang/quitconfirmation-core/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-advice/en.json
          translation_files_expression: 'data/module-advice/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-aiwarning/en.json
          translation_files_expression: 'data/module-aiwarning/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-assassination/en.json
          translation_files_expression: 'data/module-assassination/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-breakdownservicing/en.json
          translation_files_expression: 'data/module-breakdownservicing/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-deliverpackage/en.json
          translation_files_expression: 'data/module-deliverpackage/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-donatetocranks/en.json
          translation_files_expression: 'data/module-donatetocranks/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-cargorun/en.json
          translation_files_expression: 'data/module-cargorun/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-combat/en.json
          translation_files_expression: 'data/module-combat/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-crewcontracts/en.json
          translation_files_expression: 'data/module-crewcontracts/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-easteregg/en.json
          translation_files_expression: 'data/module-easteregg/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-fuelclub/en.json
          translation_files_expression: 'data/module-fuelclub/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-goodstrader/en.json
          translation_files_expression: 'data/module-goodstrader/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-newseventcommodity/en.json
          translation_files_expression: 'data/module-newseventcommodity/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-policepatrol/en.json
          translation_files_expression: 'data/module-policepatrol/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-rondel/en.json
          translation_files_expression: 'data/module-rondel/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-scoop/en.json
          translation_files_expression: 'data/module-scoop/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-scout/en.json
          translation_files_expression: 'data/module-scout/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-searchrescue/en.json
          translation_files_expression: 'data/module-searchrescue/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-secondhand/en.json
          translation_files_expression: 'data/module-secondhand/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-soldout/en.json
          translation_files_expression: 'data/module-soldout/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-stationrefuelling/en.json
          translation_files_expression: 'data/module-stationrefuelling/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-stationtrafficcontrol/en.json
          translation_files_expression: 'data/module-stationtrafficcontrol/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-statstracking/en.json
          translation_files_expression: 'data/module-statstracking/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-system/en.json
          translation_files_expression: 'data/module-system/<lang>.json'

        - filter_type: file
          file_format: CHROME
          source_language: en
          source_file: data/lang/module-taxi/en.json
          translation_files_expression: 'data/module-taxi/<lang>.json'

```

**Comment by impaktor** [comment]
Furthermore, when transifex pushed hundreds of commits, github started building new artifacts for each (batch?), so sturnclaw shut it down with, this command that should be saved to back of the brain:
`gh run list -L 200 --json status,databaseId -q '.[] | select(.status != "completed") | .databaseId' | xargs -n 1 gh run cancel`

**Pull request merged**
