### PR TITLE
I synced to the upstream and I added a Sponser Butten

### PR DESCRIPTION
**Pull request by Burnsedia**

### CODE REVIEW

**Comment by impaktor** [comment]
Again, how is this different from #4677, or #4679 for that matter?

**Comment by Burnsedia** [comment]
I didn't update my form before adding the sponsor button, the sponsor button is the same as the USD button on the main site, goes to the same URL

**Comment by impaktor** [comment]
Yes, so this is just a duplicate of #4677, but done over 4 commits, for some reason...

**Comment by Web-eWorks** [comment]
@Burnsedia thank you for contributing to Pioneer! At this time we are not accepting pull requests to add funding methods to the Github repository; however, if you'd like to join the discussion about funding you can do so on Freenode IRC, in the `#pioneer` channel, or via the relevant issue: #4677.

**Comment by Burnsedia** [comment]
I am going to start adding my custom planets and weapon types to the upstream if that is fine

**Comment by fluffyfreak** [comment]
@Burnsedia we have a forum where it would be a good idea to discuss things like that: https://pioneerspacesim.net/forum/

We also have a modding system so ideas like that can be tested and shared before becoming part of the core game. It also allows people to mod the game to include content that cannot be included in the core game for copyright or other reasons. https://pioneerwiki.com/wiki/Mods

**Comment by impaktor** [comment]
I just added a "Design philosophy" to the wiki, with general guide lines for getting a system included in the game. @fluffyfreak / @nozmajner please feel free to change/edit if you disagree with what I wrote there:
https://pioneerwiki.com/wiki/Custom_Systems#Design_philosophy

**Comment by impaktor** [comment]
@Burnsedia we definitely want more custom systems, so contributions on that is very welcome, given the constraints above (see link).

However, I'm skeptical to adding more weapons, unless they bring something genuinley good / make the game more fun. That is to say: if you just copy-paste some existing weapon, rename it to "The Master-Blaster", and change some of the stats, it is maybe not very likely to be included. However, you can always share it on the player forum for others to play with.

**Pull request closed without merging**
