### PR TITLE
Add some flare for black market, through flavoured slogans.

### LINKED ISSUE #3732: Add flavor texts for black markets
It would be nice to add a few flavor texts for the black markets, just for fun.
The texts could more or less allude to the fact that they're illegal without directly mentioning it.
Also, with the typical bullshit bingo we all know and love from advertising. xD

I suggest the following texts (where “Black Market Inc.” ( ;-) ) should be replaced with the real name, of course).

* Welcome to Black Market Inc., your trader of inconventional goods.
* We at Black Market Inc. trade the most unusual goods.
* Welcome to Black Market Inc., the market without restrictions.
* Black Market Inc.: The only really free market.
* Trade top-quality goods at Black Market Inc.
* Black Market Inc. fills the gap of the conventional market. We buy and sell unusual goods.
* Trade premium products at premium prices!
* Black Market Inc.: Because sometimes, you need more.
* Welcome to our free marketplace.
* Welcome to our little marketplace, where people come to trade what others don't dare to trade.
* Black Market Inc. takes the principle of the free market very serious.
* Buy and sell without restrictions at Black Market Inc.
* Do you feel the conventional market is lacking? Then you have come to the right place at Black Market Inc.!
* Black Market Inc. is your trustworthy market for special commodities.
* Welcome to Black Market Inc.! We buy and sell special commodities.

Feel free to come up with your own silly texts. ;-)

### PR DESCRIPTION
**Pull request by impaktor**
Closes #3732.

I'm not over-enthusiastic about it, either we merge it or we don't, either way we get to close #3732.

Also 100% untested, so no merge yet.

- [x] Test that it works, and how it looks.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
Adds a little character :)

**Comment by impaktor** [comment]
OK, fixed some minor error.

Please check the 7 `SLOGAN` strings, if they sound sane.

Also, I'm not sure about punctuation in these strings. The welcome message doesn't have "." or "!". I put the slogan on new line, since it looks (perhaps?) better.

screenshot-20160627-132107

**Comment by Wuzzy2** [comment]
Please use proper punctation In English sentences look very dumb if you don't use punctation There I did it again

**Comment by impaktor** [comment]
Fixed in code: @da47e6a947a3a6053a50f4550c823f3fa4397254

Although, I should point out that in adverts, slogans and headlines you often don't use full stop. This might seem "wrong", but it's been that way since before there were any rules for how to write.

**Pull request merged**
