### PR TITLE
New bodyscanner and SensorType. fixes #3287

### LINKED ISSUE #3287: Planet Scanner equipment type (ideal for newcomers)
This is a feature asked for by @impaktor. I was supposed to write it, but it occurs to me that it would be a nice way to start contributing to Pioneer. I have ironed out a specification document, and I would of course be willing to mentor anyone interested.

Here's a quick dump of the specs (it was written quickly on a PiratePad, so it lacks a bit structure.)

Design document for the scout thingy.

Goal of the document ?
For me (laarmen): design an API that is generic enough so that we wouldn't have to reinvent it every time a similar request comes along.

Usage:
A general equipment that draws a progress bar. -> The equipment shouldn't draw the bar, only provide the data needed to draw it.

Problem: the client needs to check that the object is actually our thingy, otherwise it would call a nil value, which results in mayhem.

Proposal:
* New slot "sensors"
  * Each equipment in sensors must have a method "BeginAcquisition" with 1 parameter
    * "progress_callback": a function taking two parameter, "progress" (a number between 0 and 100 indicating the progress of the acquisition, or the actual result when "DONE"), and a string defining the current state of the acquisition (actual values to be determined, "RUNNING", "DONE", "HALTED", "PAUSED" ?). This function will get called regularly.

  * method "PauseAcquisition"

  * method "ClearAcquisition"

  * method "GetLastResults" ? Can always be useful, I guess

* New equipment "BodyScanner" :
    * When starting the acquisition, it stores a reference to the closest body as well as the current distance to it (altitude, to be more precise)
    * Every N seconds, it increments the progress by X% if the altitude remains the same as the starting one, with a 5% margin of error. If it strays out, it passes in mode "HALTED". If the percentage gets above 100, set the state to DONE and the progress to a simple table containing a field "body" with the systempath of the body and "altitude" with the altitude of the scan.

Bonus points:
- draw a progress bar, of how much time (of total required), the player needs to fly below (between) a certain altitude (range).

### PR DESCRIPTION
**Pull request by cccpxx78**
This implements the bodyscanner sensor for #3287

### CODE REVIEW

**Comment by cccpxx78** [comment]
after connecting it to the UI locally I noticed there are still several issues with the scanner starting and stopping

**Comment by laarmen** [comment]
I guess I would have split it in two commits, one for the general SensorType and one for the specific bodyscanner instanciation, but that's mostly personal preferences.

I'll have a glance whenever I have time (which will probably not be before Friday)

**Comment by cccpxx78** [comment]
Hi @laarmen I amended some fixes that I did after the ui integration (on another branch).
I think this is ready for a first review. 
There are still a few problems I know off which I marked with TODO in the code
One of them is surviving a reload, the function pointers are missing in the table for the bodyscanner.do you have an idea on how to reconstruct them?

**Comment by laarmen** [comment]
Yeah, that's a tough one. Turns out my idea of using a single class for all
sensors might have come back to bite us in the rear.

You could implement this as a singleton class on top of the SensorType
class, though, and declare this new class to the serializer.
This way the class reloading would take care of your problem.

**Comment by cccpxx78** [comment]
this fix is included in #3396

**Pull request closed without merging**
