### PR TITLE
Preparation for trade computer information in commodity market screen

### PR DESCRIPTION
**Pull request by joonicks**
These are the icons to be used for inclusion of trade computer extra information in commodity market screen. Script changes are waiting pending merge of existing commodity market change as more changes would conflict.

Icons by noz

screenshot-20171227-205721

### CODE REVIEW

**Comment by impaktor** [comment]
We usually don't merge "dead code" or unused assets, such as icons that aren't used. It's better if these go in together with the code that will actually use them.

I usually give commit authorship of assets to the creator:
`git commit --amend --author=nozmajner`

**Comment by joonicks** [comment]
I cant commit the code changes until the already existing changes are merged.

im not saying merge this now. its open for feedback and once its possible ill commit the code

**Comment by joonicks** [comment]
you can tag this WIP if you so desire

**Comment by joonicks** [comment]
ready to merge

**Comment by joonicks** [comment]
final appearance
screenshot-20180105-204450

**Comment by impaktor** [comment]
Oh, very cool!

Maybe also have the icon infront or behind the "Major import" text in top right corner of screen shot? Mainly to "teach" player what each icon means. Ideally, we would have mouse over tooltip, but that's not possible until we move this screen to pigui.

@nozmajner thoughts on visuals?

**Comment by nozmajner** [comment]
Yeah, showing the icon on the top right makes sense.

**Comment by joonicks** [comment]
exporticon

**Comment by fluffyfreak** [comment]
This is now review(ed) ready to go?

**Comment by joonicks** [comment]
its ready from my side.

**Comment by impaktor** [comment]
Looking at it now.

**Comment by impaktor** [comment]
The eternal problem of things not working on all resolutions:
2018-01-09-083345_228x118_scrot

@nozmajner which resolutions aught it to look good on? Above is the result at 1200x900, (same with 1200x800).

**Comment by joonicks** [comment]
damn, the old gui is a fucking bitch.

**Comment by joonicks** [comment]
on 800x600

screenshot-20180109-150938

**Comment by impaktor** [comment]
Cleaned up commit history, and made @nozmajner author of icon-commit. (thus merged, under different commit hash)

**Pull request closed without merging**
