### PR TITLE
Fixed text (Italian language)

### PR DESCRIPTION
**Pull request by LordStephen77**
Correct some errors in the Italian translation.

### CODE REVIEW

**Comment by nozmajner** [comment]
Thanks! But we can't merge this, because translations are pulled from Transifex, and would overwrite your changes.
[Translations are handled there, and pulled regularly to the source.](https://www.transifex.com/pioneer/pioneer/) Could you please bring these fixes over there? (You need to register, but it's free).
Thank you :)

**Comment by LordStephen77** [comment]
I thank you for the answer. I ask forgiveness, I have discovered Pioneer recently, I am a user of the glorious Commodore Amiga, and independent developer of small projects.

I record and follow your precious tips. It is a pleasure to contribute to this masterpiece.

**Comment by nozmajner** [comment]
No need to appologize, it's not prominently displayed here in the readme. (Which I'm fixing right now).
Thank you for your contribution and welcome aboard.
And don't hesitate to come by to IRC, there are some Amiga enthusiasts there.

**Comment by LordStephen77** [comment]
Registered and I understand how to make translation changes! My thirty-year experience seems to work. Thanks friend! I correct the translation and then study the modding guide, I'm going to model some objects with Blender. I will be happy to attend your forum.

Thank you very much for your welcome.

**Comment by nozmajner** [comment]
If you wan't do do some modeling, even better! And especially drop by on IRC then, I can help you with that part a lot!

**Comment by impaktor** [comment]
👍

**Comment by Tichy** [comment]
Hi @LordStephen77 ! I'm the other Italian translator. I'm glad to see someone else's contribution. If you find something weird on transifex, feel free to fix it. I'll do the same. 😉

**Comment by LordStephen77** [comment]
@Tichy Thank you. I'm happy to meet you. You did a great job. I found only minor errors, but nothing serious. I have already corrected the first strings I discovered. Thank you.

**Comment by nozmajner** [comment]
@LordStephen77 It seems we missed each other on IRC. :).

**Pull request closed without merging**
