### PR TITLE
Fix crash in modelcompiler and add missing DESTDIR.

### PR DESCRIPTION
**Pull request by orbea**
This fixes the crash in modelcompiler described in comment https://github.com/pioneerspacesim/pioneer/issues/4506#issuecomment-451266374. The solution is thanks to sturnclaw in irc.

It also adds a missing `${DESTDIR}` to `CMakeLists.txt` so the data files are installed to the correct location.

The remaining problem is that the modelcompiler doesn't have a way to specify an output directory and doesn't respect `${DESTDIR}` as a result.

### CODE REVIEW

**Comment by Web-eWorks** [comment]
Specifically, the issue is that the modelcompiler doesn't have a way to process an arbitrary directory. The output directory (especially for an inplace build) is the same as the input directory, which assumes that the `data/` dir has already been installed to it's final resting place.

**Comment by Web-eWorks** [comment]
@impakor: I'll be addressing the modelcompiler issue in another PR; this one's good to merge.

**Comment by orbea** [comment]
I think this might of also fixed the gcc travis build, only the static check is failing.

**Comment by pcercuei** [comment]
From my tests, and confirmed by @orbea over IRC, the addition of ```${DESTDIR}``` is not needed, as:

- the data files properly installed to the expected directory when running ```DESTDIR=/tmp/foo ninja install``` even before this addition;
- ```${DESTDIR}``` probably resolves to an empty string, as it is an environment variable and not a cmake variable (it should have been ```$ENV{DESTDIR}```

Therefore I suggest that we revert b97fe6147.

**Comment by Web-eWorks** [comment]
Can confirm that `${DESTDIR}` does not produce any observable result and is contrary to the way the DESTDIR functionality works. +1 for revert.

**Comment by pcercuei** [comment]
Reverted in #4513.

**Pull request merged**
