### PR TITLE
Updated Xcode project for MacOS X

### PR DESCRIPTION
**Pull request by salborrelli**
The Xcode project for MacOS X has been updated to include all the latest changes since April 3 to date.

### CODE REVIEW

**Comment by salborrelli** [comment]
@fluffyfreak @impaktor @johnbartholomew @robn @nozmajner  In this version I intended to upgrade the Assim library from the current 3.0.0 version to the latest version 3.3.1. Unfortunately the upgrade doesn't seem to work fine. With version
[pioneer_exception_report.txt](https://github.com/pioneerspacesim/pioneer/files/972937/pioneer_exception_report.txt)
 3.3.1 I can build the project without problems but as soon as I try to run the App it crashes and I get the exception report that is logged in the attached file.

Does someone have an idea of what the cause of this problem might be? From the report I see there is a missing symbol, so might it be an problem of compatibility with version 3.3.1? 

Note that I have had to build the new Assimp library myself because there is no ready made binary for OS X Sierra. I don't think this might be the cause because I've very carefully been following the instruction for building the library, but who knows ...

Of course I've reverted the Assump library back to 3.0.0 for the time being, but any idea that could help me resolve this problem and upgrade to 3.3.1 would be really appreciated.

**Comment by fluffyfreak** [comment]
I just checked and `pioneer-thirdparty` is on Assimp 3.2.0 so there might be compatibility issues with newer version. Although if you've built and compiled against the 3.3.1 headers and libs then it might be working.

What is the newest version of Assimp available to users on OSX/XCode?

**Comment by salborrelli** [comment]
I don't think there is a ready made version of the Assimp library for MacOS X, on SourceForge I see that the only available binaries are for Windows.

Anyway I will try to compile version 3.2.0 and see if the application works. Will keep you posted ...

**Comment by salborrelli** [comment]
No relief! I've downloaded Assimp 3.2.0 source code from https://github.com/assimp/assimp/releases/tag/v3.2/ and compiled it on my Mac but if I try to use it in the Pioneer build (in place of 3.0.0) I still get the same runtime error attached in the previous post.

The problem seems to be a missing symbol (__ZN6Assimp8Importer18SetPropertyIntegerEPKciPb) and the problematic line seems to be n.257 in Loader.cpp.

Does anyone have a clue of what the cause for this problem might be?

In the meantime I'm now switching back to 3.0.0 for May release.

**Comment by fluffyfreak** [comment]
That would implicate the lines around https://github.com/pioneerspacesim/pioneer/blob/master/src/scenegraph/Loader.cpp#L330 which do set a couple of properties, but the fact that it's not finding the symbol indicates that it must be using the wrong library/dll at runtime. I.e. linking against one but running against another and the symbol lookup is failing.

XCode's library handling I find truly bizarre I'm afraid so I don't know where to start figuring that out.

**Comment by salborrelli** [comment]
@fluffyfreak yes I agree that the Xcode's library handling is weird. I will make some further analysis just to make sure that the runtime exception doesn't depend on my own system settings.

In the meantime I've uploaded the latest install package for Mac to SourceForge.

**Comment by impaktor** [comment]
@salborrelli great to see you here. Pioneer is going through heavy development and improvements now, so nice to see Mac side is still maintained.

**Comment by salborrelli** [comment]
@impaktor Well ... I like to play the game on my Mac and maintaining the Install package seems the only way to get the very latest version 😄 

Seriously I'm sorry I can't help you with some coding too but, apart of the chronic lack of time, a big problem for me is that the great majority of Pioneer development seems to be running on the Lua side at the moment. I might be wrong but I only see one issue marked with "C++ code" in the repo, that is the perennial "Separate Ship and Player" issue #38. That said I'll keep browsing the issues from time to time, in search of something that is pure C/C++.

**Comment by impaktor** [comment]
@salborrelli Well, just mission scripting and (soon) all UI is on Lua side. Rendering and physics engine is all C++, and more. There's no lack of things to do on C++ side. 

If you're looking for ideas, you could go through other dev's branches. Like [lwho](https://github.com/lwho/pioneer) was mainly C++ guy, I think, (although he helped me with some lua just before he left / became dormant) and he has branches that might need saving. His last PRs aimed to allow multiple galaxies, by untangling galaxy/universe generation code.

Also, @fluffyfreak has a lot of branches (all pure C++ I'm willing to bet), I'm sure he wouldn't mind if you wanted to take over one of them. Going through them might give you ideas of what to do on C++ side.

But don't feel pressured to do anyting, "just" providing Mac builds is of great value to us, as we're Mac illiterates.

**Comment by fluffyfreak** [comment]
@salborrelli time is the eternal enemy :)
What you're doing by keeping the OSX version going is marvellous, if you want to work on other things then feel free to ask on IRC or here, or via email if you've got one of our details.

You don't have to do any C++ stuff though, just the OSX stuff is massively appreciated.

**Comment by salborrelli** [comment]
@impaktor @fluffyfreak Hi guys thank you for the tips and no worries I don't feel pressured to do anything, it's only that in this "web era" we all have someway had to switch to more web-friendly technologies (Java, PHP etc.). I like the idea of taking a break from those "simple" (but very remunerative I've to admit) technologies and do some "real" programming every now and then, even if only as a hobby 😄 

@fluffyfreak Andrew let me know if you have one or two small branches that I could look at to get an idea of what is going on the C++ side and see if / how I can help. Being able to communicate via email would be useful too but I haven't got your email address(es) yet and of course posting them here doesn't seem wise (the IRC is probably safer).

**Comment by salborrelli** [comment]
@fluffyfreak @impaktor @johnbartholomew @robn @nozmajner FYI I've been eventually able to figure out what the problem was with upgrading the Assimp library on my Mac. I can now run Pioneer against v.3.2.0 without problems, see PR #4011

**Comment by fluffyfreak** [comment]
@salborrelli sure, I had a TODO issues list: https://github.com/fluffyfreak/pioneer/issues/45

Although you can also look at my personal [issues](https://github.com/fluffyfreak/pioneer/issues) in general. A lot of mine are terrain / rendering /proc-generation based since those are the things I'm most interested in but there's a few other bits.

**Pull request merged**
