### PR TITLE
Ship nearby optimise

### PR DESCRIPTION
**Pull request by fluffyfreak**
Only update the list of nearby ships for every ship once per second.

Split out of #3320

### CODE REVIEW

**Comment by laarmen** [comment]
By definition, a Bite-sized tag applies to issues, not PRs, since it is supposed to qualify issues that a newcomer could tackle on his own :-)

Cf OpenHatch (the Pioneer page is still buggy, but that's another story)

**Comment by laarmen** [comment]
What happens if one tries to access a ship that was nearby and has been destroyed ? Glancing at the diff, I don't see this taken into account.

**Comment by fluffyfreak** [comment]
It would probably crash, I'll need to handle that.

**Comment by fluffyfreak** [comment]
@laarmen nah actually it's ok.

That list is only accessed within the loop where it is also updated.

**Comment by laarmen** [comment]
No way to access it from Lua ?

**Comment by fluffyfreak** [comment]
Nope :)

**Pull request merged**
