### PR TITLE
Improve Joystick / Input Handling

### LINKED ISSUE #27: 3D thruster control with joystick
I think the 3D thruster control already available by keys on keypad should also be available from the joystick, in the following way:
The main thruster/break thruster control might be bound to custom keys, or the joy's thruster controls, but the thrusters controlling the thrusters in the plane perpendicular to the axis of the main thrusters, should be controllable by the "hat switch" of the joy. Possibly inverse config should be available for those who would like it that way...

### PR DESCRIPTION
**Pull request by Web-eWorks**
The goal of this PR (or series of PRs, as needed) is to fix the input handling. We're moving from a statically-defined key-binding system that requires hard-coding everything in KeyBindings.inc.h to a dynamic, extensible binding system that is much easier to use and maintain.

Fixes #27, #3362.

Done:
- [X] Move the input handling subsystem into its own module, decoupling it from the monolithic main class as much as possible.
- [x] Rework the input system to support inversion, deadzone, and sensitivity on a per-axis/binding level.
- [x] Allow defining and handling key / axis bindings without having to hard code them in C++ - this needs to die as soon as possible.
- [x] Update the Lua-side key-binding logic to use the new system.

I've split the input subsystem out so that I can more efficiently implement the rest of the features without adding to the horrible bloat of the main class.

### CODE REVIEW

**Comment by impaktor** [comment]
I guess you've seen:
https://github.com/pioneerspacesim/pioneer/labels/Input

**Comment by Web-eWorks** [comment]
I've gotten the new binding system functional on the C++ side, and I'm now going to handle the Lua implementation. Fixing joystick hats is an optional target at this point - I'm starting to run out of steam.

CC @fluffyfreak for code review while I'm still working in the C++ side of things.

I also had a question - why are the `Binding::FromString` methods using C-style string operations instead of C++? Any performance boost seems to be entirely lost by the fact that they're only called about once per session.

**Comment by impaktor** [comment]
Maybe @kuroneko wants to be aware of this PR? If you have any thoughts on this, please share.

**Comment by fluffyfreak** [comment]
@Web-eWorks two reasons, first is C-style is usually more recognised by people or the C++ is usually verbose and ugly. The second is that the whole code base is like that, usually referred too as C-with-classes rather than true C++.

There's a lot of legacy stuff in here that's been in place for 10+ years and is endlessly repurposed. So even if it appears to be new code it might well have been copied/moved from elsewhere in the code.

**Comment by fluffyfreak** [comment]
Only had chance to skim read it now but it looks good so far!

Been needing moving out out Pi for ages so glad that you're doing all this.

**Comment by fluffyfreak** [comment]
@impaktor I think it should. the CMakeLists just grabs all cpp files in the src folders, then removes a few specific one. This should just be picked up automatically.

**Comment by Web-eWorks** [comment]
I think I'm done here. Everything is hooked up and working, joystick sensitivity works fine, deadzone is confirmed working, inputs are working perfectly.

There are a few things which will need to be taken care of by another PR / maintainer:
- The input system is designed so that localizations of page/group/binding names are looked up by the binding ID, instead of including the localization strings in the binding info. This is not yet implemented on the Lua side, but I have left TODOs where this needs to be handled. It shouldn't be difficult, but I don't have enough experience with the Lang system to set it up right now.
- Axis events are currently not triggered, nor are Action events from anything other than a key binding. This is an artifact of the old implementation and I'd be more than happy to address it in another PR, but as it's currently not used by anything, I'm leaving it alone.
- The UI needs some better styling to distinguish the last line of an Axis binding from an Action binding; just a simple margin underneath should work.

Since this PR is sitting at +1300 insertions and it significantly affects a core system, I added myself to the AUTHORS.txt. I also added CMake compilation instructions to COMPILING.txt, because I didn't know that the codebase was CMake compatible until you said something.

**Comment by Web-eWorks** [comment]
I forgot to mention it, but I left the old binding system in, as the old UI makes use of it in a few places. Once that is fully converted to the new UI, the old binding system can be deleted.

**Comment by fluffyfreak** [comment]
Only thing i would say is to try and keep each PR to a distinct purpose.
So this one is about input, there shouldn't be changes to document CMake or fixup other things since we'dd add those separately to keep a PR easier to review.

Not a problem this time, just making sure that you know for future 😄

**Comment by Web-eWorks** [comment]
Moved the CMake stuff to a new PR.

**Pull request merged**
