### PR TITLE
LuaShip accessors for a ships position and velocity.

### PR DESCRIPTION
**Pull request by fluffyfreak**
For @nozmajner to play with :)

@laarmen, @impaktor, @johnbartholomew I'm not sure if this is the right way to do this, should these just be properties of each ship instead?

### CODE REVIEW

**Comment by impaktor** [comment]
Is it velocity relative to the current selected frame?

**Comment by fluffyfreak** [comment]
Whatever a Ship::GetVelocity is :)
So yes, relative to current frame.

**Comment by walterar** [comment]
And... if we make a SetVelocity too? :)

Maybe we can do this?
```
local min = 10-- km
local max = 20--km
local ship = Space.SpawnNear("viper_police_craft", Game.player, min, max)
local vel = Game.player:GetVelocity()
local plus = 450--mts
vel = vel + plus
ship:SetVelocity(vel)
ship:AIKill(Game.player)
```

**Comment by laarmen** [comment]
I'd rather have properties, indeed. It is pretty easy to imagine UI elements responding to velocity and/or position, which, IIRC, is what properties were initally all about. Plus, it makes the Lua code easier on the eyes.

**Comment by fluffyfreak** [comment]
@walterar I think for that we'd be better of adding the velocity to the `SpawnNear` command, or indeed modifying the command to spawn ship with the targets velocity. It seem like a bug that it doesn't do that already in fact.

@laarmen I'll swap it to be a property instead them.

**Comment by fluffyfreak** [comment]
Swapped to be `Ship` properties

**Comment by laarmen** [comment]
OK, having had a meeting for the last 2 and a half hour, I guess I'll have
done little enough programming for me to review and merge this tonight :)

**Comment by fluffyfreak** [comment]
Yay for meetings?!? ;)

**Comment by laarmen** [comment]
Can anybody merge this? I'm fine with it, but github won't let me push...

**Pull request merged**
