### PR TITLE
Fixed broken screenshots links

### LINKED ISSUE #5747: Broken links in net.pioneerspacesim.Pioneer.metainfo.xml
Hi all.

The links
https://github.com/pioneerspacesim/pioneer/blob/3ebceca6514bed515b276cc54f739252d6cb81e4/metadata/net.pioneerspacesim.Pioneer.metainfo.xml#L42
https://github.com/pioneerspacesim/pioneer/blob/3ebceca6514bed515b276cc54f739252d6cb81e4/metadata/net.pioneerspacesim.Pioneer.metainfo.xml#L45
https://github.com/pioneerspacesim/pioneer/blob/3ebceca6514bed515b276cc54f739252d6cb81e4/metadata/net.pioneerspacesim.Pioneer.metainfo.xml#L48
...

are missing

### PR DESCRIPTION
**Pull request by VasanthBalguri**
Fixed broken screenshots links in metainfo.xml file
Fixes #5747 issue

### CODE REVIEW

**Review by Web-eWorks — CHANGES_REQUESTED** [review]
These images should not be sourced from a link to the file in the source tree, as they're unlikely to embed properly at all (Github serves an HTML document at that link rather than a PNG file).

These images are available as `https://pioneerspacesim.net/carousel/ss1.png` etc. and should be linked to using links of that form instead.

**Comment by impaktor** [comment]
Sorry, might have been me that sent @VasanthBalguri down the wrong track.

**Comment by VasanthBalguri** [comment]
Hi, I made changes according to comments.
I observed that release is still pointing to old one, is it intentional?

`<releases>`
`<release version="20190203" date="2019-02-03" />`
`<release version="20180203" date="2018-02-03" />`
`</releases>`

**Comment by Web-eWorks** [comment]
That's not intentional, the metainfo file just hasn't been updated since then.

**Comment by VasanthBalguri** [comment]
Oh okay, then I will update, is it okay?

**Comment by impaktor** [comment]
> Oh okay, then I will update, is it okay?

Yes please

**Comment by VasanthBalguri** [comment]
It is done @impaktor  and @Web-eWorks, pleas check.

**Review by Web-eWorks — APPROVED** [review]

**Pull request merged**
