### PR TITLE
Reduce hydrogen price back to 1 credit

### PR DESCRIPTION
**Pull request by WKFO**
̷R̷a̷i̷s̷i̷n̷g̷ ̷l̷o̷c̷a̷l̷ ̷d̷e̷l̷i̷v̷e̷r̷y̷ ̷r̷e̷w̷a̷r̷d̷s̷.̷
After countless protests across the galaxy, fuel prices are reduced again.

### CODE REVIEW

**Comment by WKFO** [comment]
Drafted because still not profitable.

**Comment by impaktor** [comment]
Ah, yes, I've been planning to do this. In Frontier the rewards were typically: 
- Package delivery ~ 100-500 (no time limit)
- Taxi missions ~ 1000-5000
- Assassination ~ 7000-20,000

I'd like to see the actual rewards generated from these new levels. E.g. put each code snippet in a for loop and generate 1000 rewards for each, and show distribution for each (or mean/median/variance). (I have code for that, although it's trivial.)

but as you've pointed out (elsewhere), fuel cost is too high, as I've assumed using ~1t fuel per travel, i.e. ~10 credits in travel cost. The way I see it, fix is to either lower in-system fuel consumption e.g. 10 fold, or put fuel price (temporarily) back to 1 credit / tonne, until we've come up with something better.

**Comment by Zireael07** [comment]
I think the latter makes more sense, as I've pointed out elsewhere, hydrogen is the most abundant element in the universe. Even if it's processed somehow to become fuel, 10cr/tonne is too much.

**Comment by nozmajner** [comment]
@Zireael07 Yes, but storing Hydrogen is anything but trivial. It seeps trough the wall of tanks even in cryogenic form.

**Comment by Zireael07** [comment]
What year is Pioneer set in? Somewhere in 22nd century or even 23rd? I'm sure it's a solved problem by then, if it's widely used as fuel.

**Comment by WKFO** [comment]
Pioneer is in 3200's.

**Comment by WKFO** [comment]
So would you rather have this PR reduce the hydrogen price until we balance everything and re-implement the new economy, or...?

**Comment by Zireael07** [comment]
By reducing hydrogen price, you both make it more sensible from a point of view of a galaxy-spanning economy, AND don't have to change fuel consumption.

**Comment by impaktor** [comment]
@WKFO yes. I think putting Hydrogen back to 1 credit, would again bring cost to ~10 credits per trip, which is what the trade is scaled for. And missions as well.

I'm not against hydrogen at 10 credits, but then either ship fuel consumption needs to go down, or trade and mission rewards need rebalancing, the latter of which seems to be the most work, which I'll gladly stay a way from.

**Comment by WKFO** [comment]
Makes my job a lot easier :)
Side note, trade is still broken because of #4858

**Comment by WKFO** [comment]
please review this, thanks

**Pull request merged**
