### PR TITLE
Add imgui gauges and planetary information 

### PR DESCRIPTION
**Pull request by ecraven**
Updated Screenshot:
gauges

Video: https://nofile.io/f/RmxMJxqKkWL/gauges.mp4

### CODE REVIEW

**Comment by radcapricorn** [comment]
Would the inner text on those progress bars be readable in lower resolutions?

**Comment by ecraven** [comment]
Not ideal, but still readable to me ;) 1024x768
small

**Comment by impaktor** [comment]
Just gave it a quick spin. Looks good. Here's what I noticed:

1. the temperature window is still visible when in options menu

2. I'm not sure, but I suspect the position of the bars move if one of the bars isn't needed and therefore not drawn? I'd expect the xy of each bar relative the screen be fixed regardless if, say preassure, is drawn or now. I might be wrong, but I thought something moved when I went into space.

**Comment by ecraven** [comment]
I can't reproduce 1., seems to be fixed ;)
As for 2., I'd prefer a neatly stacked list of gauges to one with holes in it (especially if modules start adding their own gauges). Is that incorrect reasoning?

**Comment by fluffyfreak** [comment]
It looks good! Also I'd prefer continuous gauges instead of gaps too.

**Comment by impaktor** [comment]
Just looking in pigui, your tabs are 2 big?

@laarmen what tab width do we use for lua?

Personally, I use 2, but for pioneer, I think it's 4 on C++ side?

Sorry, don't mean to go into the most boring part of coding...

Tested this. I can no longer tell if the temperature/planet info window is on top of the options window, as they no longer overlapp (and it's not movable by default), so I assume it's good.

**Comment by ecraven** [comment]
> Just looking in pigui, your tabs are 2 big?
> @laarmen what tab width do we use for lua?
> Personally, I use 2, but for pioneer, I think it's 4 on C++ side?

I'd be glad if we could decide on *one* indentation width for lua and
C++, I'd like to put in a cleanup PR that fixes indentation of all files
some time in the future ;) clang-format is a great tool for getting
C++ code in line ;)

**Comment by fluffyfreak** [comment]
1 tab = 4 spaces in C++

**Pull request merged**
