### PR TITLE
Server agent

### PR DESCRIPTION
**Pull request by robn**
I've been talking about this for two years. Finally time to add it to master so I can think about building on top of it.

Basic usage is documented at http://pioneerwiki.com/wiki/ServerAgent

This is deliberately disabled to start with, to allow us to experiment. At some later time we'll work out the process for enabling it, where the server is, privacy concerns, etc. I don't want to this PR to get bogged down in those details.

It needs build stuff for MSVC. http://curl.haxx.se/download.html has libcurl binaries.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
That's cool, I guess I'll need to make sure we have a version of libcurl in thirdparty for VS2013 users.

[Appropriate XKCD](http://xkcd.com/1481/)

**Comment by fluffyfreak** [comment]
@robn [web-agent](https://github.com/fluffyfreak/pioneer/tree/web-agent) branch has vs2013 fixes on it and PR for https://github.com/pioneerspacesim/pioneer-thirdparty/pull/12

**Comment by robn** [comment]
Thanks @fluffyfreak. I'll merge pioneer-thirdparty when this is merged.

And on that note, any particular objections to this? If not, I'll merge this evening!

**Comment by fluffyfreak** [comment]
I might update the `libcurl.dll` but that can wait until it's merged.

I have no objections but I think it might need some documentation on what you can use it for :)

**Comment by robn** [comment]
Well at this point nothing, because there's no server. Or from another angle, EVERYTHING, just a simple matter of programming :)

I have some ideas for a kind of player/community site with hooks into the game, but its nothing more than ideas and some paper notes. There's also things like querying for updates, sending in hardware info, that sort of thing. But obviously, needs server and client code.

Its a building block :)

**Pull request merged**
