### PR TITLE
Replace import() with require(); allow hot reloading of lua files

### PR DESCRIPTION
**Pull request by Web-eWorks**
This is a whopper of a merge, I realize. 90% of it is simply rewriting our existing `import()` calls into the new `require ''` calls, and the rest are changes that have already been reviewed in other PRs.

To summarize, after this PR:
- We won't be using `import()` or `import_core()` in new code - use `require ''` or `package.core[]`
- All lua-related files go in `src/lua/` or a topical subfolder like `src/pigui`.
- Reloading files is possible with `package.reload()`, but you'll have to arrange for the reloaded file to manually register / unregister the code that is the subject of the reloading. This is mostly related to the pigui modules, where we need to implement `gameView.unregisterModule` and related functions.
- Throwing an error inside of lua pigui modules is theoretically possible to recover from, but not 100% fully tested. Tread carefully and watch for bugs, please!

Note: not all of our lua files have received a makeover yet. Everything dealing with newUI has been left alone; I'm letting @vakhoir decide whether they're worth upgrading or if he wants to proceed full-steam-ahead on getting rid of newUI instead.

**Achtung! Attention!** Until this PR has been merged, we will be *freezing* the master branch. No direct commits, no PR merges. This is for my sanity and so I don't have to merge into this PR again.

I'll be leaving this pull request open for a few days and then swiftly merging if no major bugs arise. All of the major changes have been reviewed in isolation in other PRs, so I won't be requesting any in-depth looks at the code.

### CODE REVIEW

**Comment by impaktor** [comment]
Cool. If all has been reviewed separately before, I assum there's not much for @laarmen to complain about.

**Comment by laarmen** [comment]
Please. I don't complain, I whine.

**Comment by Web-eWorks** [comment]
Everything is compiling fine, but appveyor is throwing a fit over not being able to upload the mingw builds and there's a minor clang-format issue. I'll bring the new code into stylistic compliance later when I fix the clang-format script; for now I just want to get everything merged.

**Comment by vakhoir** [comment]
I missed this getting merged - nice work!

**Pull request merged**
