### PR TITLE
Use ffmpeg to record video realtime.

### PR DESCRIPTION
**Pull request by fluffyfreak**
We've had the ability to record video, after a fashion, by saying a lot of screenshots to disk. This however it bound by IO and processing requirements, it's also a pain.

I stumbled upon [this blog post](http://blog.mmacklin.com/2013/06/11/real-time-video-capture-with-ffmpeg/) that suggested a way of capturing directly from the game using ffmpeg.

To record video directly from Pioneer you will need to add the line `RecordVideo=1` somewhere within your `config.ini` file.

Then once ingame you can press `Ctrl`+`ScrLk` to start or stop recording. 
There is currently no feedback as to whether or not you're actively recording since I didn't want to indicate on-screen and spoil the recording itself!

For this to work you will need to have [ffmpeg](https://ffmpeg.org/) installed and accessible on your system PATH. I would also recommend doing this only on a reasonably decent PC since it is compressing it to H.264 in realtime.

### CODE REVIEW

**Comment by impaktor** [comment]
> To record video directly from Pioneer you will need to add the line RecordVideo=1 somewhere within your config.ini file.

How/where do we put this information? On wiki? Or have a default RecordVideo=0 option inserted in config?

> There is currently no feedback as to whether or not you're actively recording since I didn't want to indicate on-screen and spoil the recording itself!

Have a message to Output buffer/terminal?

**Comment by fluffyfreak** [comment]
I've inserted a default `RecordVideo=0` in the config.
Hopefully fixed up the Linux build issue but I'm just going to test that now at home.
Outputting the start/stop of video recording to the `Output` file.
Also given each mp4 recorded a unique filename similar to how we timestamp the screenshots.

**Comment by impaktor** [comment]
I was scared to test this, as ffmpeg surely pushes my computer beyond what is healthy, and running it _with_ pioneer at the same time? foggeddaboutit.

I'll try i t a few seconds though.

**Comment by fluffyfreak** [comment]
@impaktor try it on the new one 😁

**Comment by ecraven** [comment]
Works fine for me on both OpenGL 3.x and 2.1. See https://github.com/ecraven/pioneer/tree/record-video for a simple change to only start ffmpeg when necessary (so we don't need RecordVideo in config.ini any longer).

**Comment by impaktor** [comment]
Also, me removing the review-request for robn was a miss-click. Sorry. Add it back in if you still want it.

**Comment by fluffyfreak** [comment]
ecraven, you can do a PR if you retarget it against my fork/branch

**Comment by ecraven** [comment]
is this ok to go?

**Comment by fluffyfreak** [comment]
I think so, I can't quite figure out how to check if ffmpeg is available which might cause a crash though if it isn't.

**Comment by fluffyfreak** [comment]
It should be ok because `ffmpegFile` will be `NULL` and there's a guard against that though.

**Pull request merged**
