### PR TITLE
Fixed a crash pumping fuel into full tank

### PR DESCRIPTION
**Pull request by shammyx**
Added a missing import to data/libs/Ship.lua

### CODE REVIEW

**Comment by laarmen** [comment]
LGTM

**Comment by fluffyfreak** [comment]
Hi @shammyx I'm about to merge this, what name do you want us to use for you in the AUTHORS.txt file?

**Comment by shammyx** [comment]
Hi @fluffyfreak you can use my real name: Alexander Noack, thanks mate! I didn't know this one-lner is already sufficient to appear on that list :D but I plan to contribute more, after my holidays in 6-8 weeks!

**Comment by fluffyfreak** [comment]
@shammyx you've committed code so you're an author :)

Looking forward to more in the future!

**Pull request merged**
