### PR TITLE
New music for ship-destroyed

### PR DESCRIPTION
**Pull request by WKFO**
Hungarian Dance No. 5 with minor modifications from me. Could also be a docking music with slower speed and no strings.

I am just bored of hearing the same things over and over in the game so I will keep throwing things in the dev forum post. I can't bring back s20dan or emajogi but I will do my best.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
I'm not familiar with music licensing but do you know the origin of the piece? Who performed it etc? 

It's very discordant to my ears but then we all have different tastes and it's is for the tombstone loop! :)

**Comment by WKFO** [comment]
The piece is royalty free like classical pieces we already have in Pioneer. Composed by Johannes Brahms at the end of 19 ceuntry. The stuff we use is digitally produced by us so it is impossible for any orchestra to claim rights.

**Comment by nozmajner** [comment]
Shouldn't we merge this?

**Comment by fluffyfreak** [comment]
Yes

**Comment by impaktor** [comment]
I realized what sound I'd like for the death scene in pioneer: 
https://www.youtube.com/watch?v=ji2Wcc2ZHJY&t=1m39s
😉 

Honestly, would be a fun easter egg, like 5% chance of playing that, instead of actual?

**Pull request merged**
