### PR TITLE
Do not spawn unarmed pirates

### LINKED ISSUE #3902: Police ship spawned as pirate
The "pumpkinseed_police" ship appears sometimes as pirate ship.
Also, sometimes an unarmed Varada is attacking.

I assume it is because the Police Pumkinseed is hyperdrive capable contrary to the other police ships.
And the front laser slot isn't checked in all missions.

### PR DESCRIPTION
**Pull request by robothauler**
Closes #3902 
I did not touch the police pumpkinseed. Some say it could be a corrupt police officer or it's a stolen police craft.

### CODE REVIEW

**Comment by impaktor** [comment]
This looks OK.

> I did not touch the police pumpkinseed.

I'd like to know _how_ that happens, so to me that's a bug, (although I'm not sure I even understand the description of  the bug, as you saw in that issue). A fix for that bug should be a separate commit, (or PR), assuming you can track it down.

**Comment by robothauler** [comment]
For example:
return def.tag == 'SHIP' and def.hyperdriveClass > 0 and def.hullMass <= 150
does not preclude the police pumpkinseed because it has hyperdrive.
Maybe a 'def.price > 0' can preclude all special ships.

**Comment by nozmajner** [comment]
What if there would be a tag in each ship.json, that would make it available or unavailable for pirates? Like how the static ships are handled.

**Comment by robothauler** [comment]
Something like
"role" : {"pirate", "merchant", ...}

**Comment by nozmajner** [comment]
Hmm, a role field could be handy in the future for other stuff for sure.

**Comment by impaktor** [comment]
Wait, are you talking about the fact that pumpkinseed ins't _exclusivley_ reserved for police? Because, neither is kanara, right? So I don't considet that a bug.  Pirates should be able to fly pumpkinseed and kanara, if those ships fulfils the filter conditions.

**Comment by HybridDog** [comment]
Could you add Tokko ships, they don't shoot you but when you land somewhere or fly quietly (or use autopilot) they perform a kamikaze attack?

**Comment by laarmen** [comment]
That... Might be a good idea for a mod?

Le lun. 27 févr. 2017 à 16:30,
̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄
̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄ <notifications@github.com> a
écrit :

**Comment by HybridDog** [comment]
Yes, the assassins could behave like usual ships waiting at stations but when you land they suddenly drive into you. They could also block you from taking off by flying above.

**Comment by laarmen** [comment]
Could you perhaps expand on those ideas on our dev forum? Link on our
homepage, if the inscriptions are closed (happens sometimes due to
spammers) poke @impaktor

Le lun. 27 févr. 2017 à 17:10,
̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄
̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄ <notifications@github.com> a
écrit :

**Pull request merged**
