### PR TITLE
Keepers orbital station texture update

### PR DESCRIPTION
**Pull request by fluffyfreak**
Keepers [orbital station texture update](https://pioneerspacesim.net/forum/viewtopic.php?f=6&t=539) with pattern textures converted to DDS

### CODE REVIEW

**Comment by impaktor** [comment]
Will this then double the amount of "unique" stations, as there will be a 50-50 chance if they use these textures or original?

**Comment by fluffyfreak** [comment]
I cannot honestly remember right now. I think it will always use a pattern if there is one available.

**Comment by fluffyfreak** [comment]
@nozmajner what do you think?

**Comment by nozmajner** [comment]
I think it's good. Are they the ones made from the dds textures? Those were quite artifact-laden.

**Comment by fluffyfreak** [comment]
@nozmajner they're from whatever was used in that zip file

**Comment by nozmajner** [comment]
Then that's from the dds-es. The artifacts were quite obvious on the hud, so maybe we shouldn't merge them yet.

**Comment by fluffyfreak** [comment]
So, what's going with this one?

**Comment by nozmajner** [comment]
I think so

**Pull request closed without merging**
