### PR TITLE
Change laser to weapon in some core en.json

### PR DESCRIPTION
**Pull request by nozmajner**
It changes "Fire laser" to "Fire weapon" in the key bindings options screen and
changes "Laser fire detected" HUD message to "Weapons fire detected".
Made with the builtin editor of github, but I'm not sure if it created the branch here or on my fork.

### CODE REVIEW

**Comment by impaktor** [comment]
> Made with the builtin editor of github, but I'm not sure if it created the branch here or on my fork.

Looks like the branch is on "our" fork, rather than yours. Not a problem as such. 

I wonder what the "right way" to make PR in github is? 
- make new branch on __own fork__
- (switch to branch)
- edit
- open PR? 

I don't know, as I haven't tried. Yet.

This PR looks good to me :+1:

**Comment by laarmen** [comment]
GH seems to create the branch on the closest repo it can access within the
user's right. Seem all 3 of us have write access to the upstream repo,
that's where the editor creates the branch. If you wanted the branch to be
on your own repo you'd have needed to do the editing on its own page (
https://github.com/nozmajner/pioneerspacesim I guess). I had the same
problem once, aggravated by the fact that my own repo wasn't up to date
with master and there's no way I can see on the web interface to update
one's master branch.

Dumb question : is the alert displayed when there are missile fired ?

Otherwise, :+1:

**Comment by nozmajner** [comment]
I don't know if it's displayed on missile fire too. Does the AI even fire them at all?

**Comment by laarmen** [comment]
That's another good question :)

**Comment by fluffyfreak** [comment]
I'm ok with this.

**Pull request merged**
