### PR TITLE
Fix sqrt exception

### LINKED ISSUE #3996: Crash - exact same time each reload
### Observed behaviour
Current master ([9c8c112](https://github.com/pioneerspacesim/pioneer/commit/9c8c11276eaa10b7db020790093798ce150143c2)) crashes sometimes. It seems random, sometimes I can play for 10-20 minutes, sometimes it happens after a few minutes. Sometimes it only happens if you jump out to another system.
And if it happens, it will happen the exact same time, if you load back the save you did before the crash.
Win7 64bit, Decent nVidia GPU. Latest thirdparty, building with VS2015. No mods.

crash_tradeship

### Steps to reproduce
[Here's a save that should crash](https://www.dropbox.com/s/ni0itw54eqgcy6s/_quicksave_crash?dl=0) at 14:17:07 Jan 1. Just time accelerate and let the autopilot fly to Ceres (the already issued command). The crash happens exactly the same time, down to the second, if you just enable time acceleration. It differs a little if you alter the course to somewhere else, or force time acceleration.

I tried jumping to Epsilon Eridani - no crash there.
If I jump back to Sol, it crashes again, but at different times each time.

I tried removing the Tradeships.lua module. This only postponed the crash, and the crash also happens around the same time, but with little differences in this case, especially with forced time accel (around 06:25 Jan3).

If I remove the Tradeships.lua, jump out and jumped back, then the crash doesn't happen.
(I issued a goto to Ceres at each try for consistency)

Also tried removing every modul that would generate a ship, but that made no difference.

Output.txt seem to end on different stuff each time, and no error message.

I tried watching the other ships from the orbital map, but didn't saw anything out of ordinary. One ships achieving escape velocity seem to coincide, (PI-5143), but I guess that's just coincidence.

### PR DESCRIPTION
**Pull request by fluffyfreak**
Fixes #3996

### CODE REVIEW

**Comment by fluffyfreak** [comment]
Doh! Just realised this is #4000

**Comment by impaktor** [comment]
Looks like you included a commit too much.

`git reset HEAD~2`

**Comment by mike-f1** [comment]
I would add 2 things:

1. It seems there's a "pre-division" by mass in Propulsion.h (so it's better to use `GetThrustUp`)... And this lead to improvements because in "pre-merge" of d2aab0530b there aren't members to GetThrust*

2. GetThrust* is even positive or negative, because mass is even positive: so the problem is on value parsed from ShipType (`m_linThrust[THRUSTER_UP]`): I don't know but to me it seems more logical let `GetThrust*` member family to return positive values, although this is more complicate to obtain

**Comment by fluffyfreak** [comment]
@mike-f1 I'll leave cleanup to another PR to restrict this to just the fix but thanks for the suggestions 😄

**Comment by mike-f1** [comment]
@fluffyfreak: No problem: I agree with you also because *I* did the mess, and I should solve it...

Only tell me if you think there's reasons to not ever return only positive value on GetThrust*...
Because (working on Propulsion) I get little confused (evidently :/ ) by the way this work and a step
ahead is to simplify it...

**Comment by jaj22** [comment]
Thrust values should always be positive. Paired negative values may work accidentally for some routines, but others will react very poorly. I wouldn't have recommended merging this "fix", as it's just covering up another bug and other less visible problems will be caused elsewhere.

**Comment by mike-f1** [comment]
Hi @jaj22 , nice to see you again... Has been time I miss you :/

> Paired negative values may work accidentally for some routines, but others will react very poorly

I'm afraid but I don't think it was like you say: before (evidently poorly designed) #3914 thrust values were in m_linThrust[] and (you can check) 3 of them were negative. More: they *are* negative... :/
...This probably cause an headache to me while I was coding, and *evidently* I did something wrong...

> another bug and other less visible problems will be caused elsewhere

I'm sorry for the troubles...

**Comment by jaj22** [comment]
Yeah ok, forgot that forward/left/down were set negative in ShipType.cpp. It corresponds to the axis directions: x-right, y-up and z-backwards are the positive directions in the coordinate system.

Either way, if the convention changes then nothing will work correctly :P

**Pull request closed without merging**
