### PR TITLE
Custom systems continued

### PR DESCRIPTION
**Pull request by SpifforOmnivore**
**Ayizan/Lacaille 8760**
Impoverished outdoor world
Solar Federation

More description and discussion on the [forum](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=578&start=10#p5843) :)

### CODE REVIEW

**Comment by impaktor** [comment]
Code / git-sanity it looks nice. I haven't checked the system yet, but I'm sure it's fine.

If you want to add more systems to this PR you can just:
`git add <path to system file>`

I think I remembered you saying you were new to git, so:

## option 1

And if you want this PR to still be a single commit, or if fixing a problem with the last commit, you do:

`git commit --amdend`
`git push --force` 

and it will add your changes to the last commit and update.

## option 2

if you want any new system as a separate commit "Added Trantor system", you can just do a normal
`git add <files> ; git commit -m "Added Trantor system"`
`git push`
and this PR will be updated with a second commit.

**Comment by impaktor** [comment]
> I think I'll add one new system per PR (seems easier to follow).

Remember to switch back to master after creating each branch, so they're all branches of master, and not each other: master -> A, master -> B, and not master -> A -> B

> If I change data/systems/02_local_stars.lua in two separate PRs, won't it be conflicting?

Not unless you change the same line, I think. _If_ you change the same line in two PRs the second one will complain there's a "merge conflict" after the first one is merged.

**Comment by SpifforOmnivore** [comment]
More about the Wolf 1061 / Noril system [on the forum](https://pioneerspacesim.net/forum/viewtopic.php?f=3&p=5859#p5859) :)

**Comment by SpifforOmnivore** [comment]
More info and screenshots about Tau Ceti in the [wiki](https://pioneerwiki.com/wiki/Tau_Ceti), and discussion on the [forum](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=578&start=30#p5867) :)

**Comment by impaktor** [comment]
Nice I've left some comments on it on the forum: https://pioneerspacesim.net/forum/viewtopic.php?p=5868#p5868

**Comment by SpifforOmnivore** [comment]
Thanks Impaktor, I've read them and I'll include them all.
By the way, I changed my email adress on the forum, and I didn't get the new activation email. I cant't post there anymore :cries:

**Comment by impaktor** [comment]
> Anybody can send the new activation email?

Your account should be activated now, please try again.

**Pull request merged**
