### PR TITLE
Lua sanity and bug fixes

### PR DESCRIPTION
**Pull request by impaktor**
Some minor bugs fixed. 
Some sanity instilled.

### CODE REVIEW

**Comment by walterar** [comment]
You're using an old version of Equipment.lua?

**Comment by impaktor** [comment]
I did this from my old master (20141118), so yes, files are old, but only the changes will be merged, so it should not be a problem. I just did a test merge into current master, to make sure, and it worked fine.

**Comment by walterar** [comment]
:+1:

**Comment by walterar** [comment]
I think Game.player: SetMoney (100) needs local Player = import ("Player") in MainMenu.lua

**Comment by laarmen** [comment]
I haven't looked at the code, but syntactically from what you said, Game.player only needs the global "Game", all other symbols are then defined from within the imported module.

Technically, you don't need to import the module where a method is defined to use it. It is just the most straightforward way to access it, but access may be leaked from other objects (for instance, Game leaks a bit of the Player module via its "player" object). Usually, the leak is either intended, or harmless.

**Comment by impaktor** [comment]
@laarmen You're absolutely right, what was I thinking! 
"Cure gender bugs" is much better!

**Comment by walterar** [comment]
Theoretically it should not happen, but it happens.

error: ui/MainMenu.lua:30: attempt to call method 'SetMoney' (a nil value)

**Comment by impaktor** [comment]
I just tried running it, and yes, there are some things happening that should not, so I'll need to fix them first.

**Comment by impaktor** [comment]
I reverted the changes that didn't work, thus logic suggests that it should work now.
Merged.

**Pull request merged**
