### PR TITLE
Make Autopilot purchasable from everywhere.

### PR DESCRIPTION
**Pull request by fluffyfreak**
The most useful piece of equipment in the game, essential for all newbie players, and for some rason we make it a pain to find?

That's dumb in fact I don't think it should even be equipment, just something that any ship can always do but that's debateable.

### CODE REVIEW

**Comment by impaktor** [comment]
:+1:

**Comment by impaktor** [comment]
> The most useful piece of equipment in the game, essential for all newbie players, and for some rason we make it a pain to find?

From table in #3505 I read that it was like that in Frontier. That was the reason.

**Comment by fluffyfreak** [comment]
Yeah I didn't think that it was done with deliberate thought :)

**Comment by walterar** [comment]
Piloting with human hands became obsolete in the early 21st century more than a thousand years ago. Although for some it is a hobby today. I know because I was there.

**Comment by Brianetta** [comment]
Years ago I suggested a very hard game start, where the player started in a ship with no shields, no atmospheric shielding, no jump drive and no autopilot, in an orbital station. A different station sold atmospheric shielding, and an autopilot and jump drive were available from the planet's surface.

This gives the additional challenge of having to actually pilot your space ship before you're allowed to sit back and let it fly itself, including orbital rendezvous and planetary landing.

As long as it's possible to specify, in a custom system, the availability of specific items, this remains possible.

**Comment by impaktor** [comment]
> I don't think it should even be equipment, just something that any ship can always do

I might be late to the party, but some players want autopilot to be _removed_ (based on conversations on IRC), as they find manual flying the true joy of pioneer.

**Pull request merged**
