### PR TITLE
vs2017 solution and project files

### PR DESCRIPTION
**Pull request by fluffyfreak**
MS have released their biennial Visual Studio release with vs2017 and it has a new Community (free) edition.

As usual I'm being forced to update for work reasons (_console stuff_) and so I'm spreading the cheer for people using the new one.

Builds fine with vs2015 DLLs in thirdparty so far.

I'll continue to support both vs2015 and vs2017 for ... well I dunno, quite a while probably.

### CODE REVIEW

**Comment by impaktor** [comment]
Well, this is all on you. No one else can review it, I guess.

But this only adds the configuration files for vs2017, right? So why are there gif-icons in there?

**Comment by fluffyfreak** [comment]
Yeah that's fine, it's just I like to go through review 😄 

Also debugging doesn't work yet, might need new DLLs for vs2017 specifically 😞

**Comment by impaktor** [comment]
@fluffyfreak I'm thinking a big merge tonight, with imgui branch. Are you happy with this as is?

**Comment by fluffyfreak** [comment]
No this is WIP as it cannot be debugged etc, it relies on using the vs2015 libraries, which works for doing a build but not for useful things like debugging etc 😢 

Hence the WIP tag at moment.

**Comment by laarmen** [comment]
BTW, I had to use the integrated CMake support in VS 2017 for work, and it works quite nicely. Might be worth a(nother) try.

**Comment by fluffyfreak** [comment]
I think I'll close this for now and redo it in another way.

**Pull request closed without merging**
