### PR TITLE
Search & Rescue mission script

### PR DESCRIPTION
**Pull request by clausimu**
##### Primary Goal

My initial goal was to provide some incentive to the player to actually go and explore some of those beautiful uninhabited worlds and places in space you would normally not go. In addition, I also wanted to have to get close to the cool ship models. At least that is how the idea was born...

##### What It Does

I have tried to make the framework of the script easy to add on to. What it currently does is provide seven different flavors (with several randomly adjusted sub-flavors) of search & rescue missions where you have to:

* deliver fuel to stranded ships
* deliver replacement crew
* pickup crew and passengers from damaged ships

at different locations, such as:

* same planet the ground base is on
* vicinity of the orbital base the player is docked with
* an uninhabited planet within the same system
* orbit of a planet in an uninhabited system.

Some missions require going back to the base where you came from. Others will be finished once the target ship is found.

##### What I Need Feedback On / Current Limitations

The biggest game-breaker right now is the in-space transfer system this script employs. As soon as you reach a distance of 50 m to the target ship a transfer is initiated. If you hold this distance for the requested time, all items/personnel are "beamed" between both ships. I've tried to make this as descriptive as possible for the player in game using comms messages. I don't know of any other way right now because we can't dock ships to each other yet. It feels very "non-Pioneer" though...

I also don't know if I hit the right tone for the ad texts. If it does not "feel right" - please feel free to criticize.

The finally intended frequency of ad generation has not been set yet. For testing purposes each station gets a chance for 3 ads of each major flavor right now.

##### Some Screenshots With Examples
lat_lon_17
lat_lon_16
lat_lon_28
lat_lon_20
lat_lon_21
lat_lon_22
lat_lon_24
lat_lon_26

### CODE REVIEW

**Comment by fluffyfreak** [comment]
This is really good, you've added a whole new type of gameplay to Pioneer!

We'll definitely try and review this asap. Thanks in advance @clausimu, great job.

**Comment by impaktor** [comment]
Sweet!

Suggestion for the first screen shot: "We will pay $ _on their behalf_ to anyone... ". Or not. 

I'm mostly thinking about the translators when reading it. Generally, see if you can break up the mission text in 2-3 sub-paragraphs, or else any future change will require re-translation to the whole string.

Also, it's easy to get carried away with many flavours, but when adding a giant module they tend to go untranslated for many months. Perhaps not a reason to not add awesome stuff to pioneer, but something to keep in the back of your head.

I might have time to look at the code in the weekend, but cant promise anything.

**Comment by nozmajner** [comment]
Nice! I'll make an icon for it ASAP.

**Comment by clausimu** [comment]
> it's easy to get carried away with many flavours, but when adding a giant module

That is why I decided to present a working model of what is possible right now - and I might have gotten carried away as it is already... :). I have many more ideas and we can steer this in any direction you desire. Maybe even cut down on the number of flavors and cherry-pick the really interesting ones.

I will look into shortening/breaking up introductory paragraphs.

My ultimate dream is to embed this (and other missions) into a background of corporations and influential figures per system/faction that are permanent and procedurally generated with their own conflicts and goals. But that is for another time.

> I might have time to look at the code in the weekend, but cant promise anything.

No rush.

> Nice! I'll make an icon for it ASAP.

Can't wait to see what you will come up with. I really like your artwork.

**Comment by nozmajner** [comment]
Thanks :)

I've just tried out a local rescue mission.
I agree with @fluffyfreak, it adds quite a lot to the game. I've only did close one rescue yet, but I really liked it.
It's a quite nice touch, that the ship flies away to the nearest spaceport, I really liked that. (I followed him with autopilot)
One thing I noticed, that you can transfer the hydrogen while floating near the grounded ship. I assume this is the same when you need to transfer crew or something.
It might be nice to have the player land near the ship to be able to transfer what's needed for grounded ships. 

Also I saw missions to uninhabited systems. One thing to note that there's no direct FTL communications in the Pioneer Universe, only couriers and such. So we might want to figure out, how they were able to get the message out from an uninhabited system. Not that it's a problem, and it's purely a background fiction question, but it is usefull to be consistent later. And also important for writing the flavour texts. Which I could be able to help with a bit. 
One way could be some kind of hyperspace capable comms drone/bouy ships can send out (small drone, so a really small hyperdrive and Hydrogen amount would be sufficient), which would broadcast the distress call in a habited system.

**Comment by nozmajner** [comment]
Icon proposal: 
searchrescue
Justificatin: these are distress calls, so it's fitting to have an eye chatching red icon among all the white icons. It would look odd though, if these distress calls are dime-a-dozen, but I guess we don't really want that. And a suggestion I already told clausimu on IRC (but let's actually write it down for future reference): these distress calls could be more frequent in systems with low lawlesness.

**Comment by nozmajner** [comment]
White icon with red !: 
searchrescue2
Over non_transparent, so it's actually visible here: searchrescue2_nontransparent

**Comment by corundscale** [comment]
Haven't yet tried it (it already sounds beyond awesome) but I have a few points of my own:

* giving distance to the ship seems pointless - unless the ship is on a planet, it's going to be in freefall and will probably be moving quite fast. Orbital parameters - parent body, periapsis (unless on colision course with parent), apoapsis (unless on hyperbolic escape trajectory), time before/after periapsis as a measure of ship's position along orbit (unless having players, myself included, ask wtf is true anomaly is preferable ;)), inclination seem like a better idea.
* would it be possible to have distress calls arrive while traveling, not just as BBS ads? Then it would be possible to change trajectory to intercept the ship (possibly dumping cargo to shed as much mass as possible - decisions, decisions...), randezvous, transfer crew and any propellant you can fit (because you're likely to be dry after such intercept, distress call should specify ship's condition along with amount of propellant it has left)
* also, from what I understand a ship is specifically spawned for this mission - how about having one of the existing ships emit a distress call? It might call for having more ships doing things other than travel, though, like doing stuff in orbit, etc.
* there should be a chance, based on lawlessness of the system, of distress call being a spoof - on arrival the supposedly damaged ship would turn out to be a pirate ambush (either the ship itself, possibly with buddies, or having wreckage of previous victim and a bunch of pirates around it doing the impersonation).
* even without docking crew transfer could be made more physical - how about having suited-up crew leaving the ship (basically having people-shaped cargo jettisoned in terms of mechanics) once player approaches and having to be gently scooped up?
* I think the more flavours the better, Pioneer will always have repetitiveness as its arch-nemesis, like every other open-world game. Apart from normal S&R you could, for example, have forensics where you'd have to get a detective to a wreckage to determine what happened to it.
* I would love to eventually see a sort of procedural mission chaining: for example you travel and receive distress call -> you rescue the crew, transfer propellant and go to the port -> now abandoned ship generates a salvage mission on BBS where you need to transfer crew, engineers, repair supplies and fuel to it, to reclaim the ship and cargo -> in parallel the ship can also generate an event where it attracts pirates/looters -> once you arrive you may already find aggressive looters at the ship, or transfer crew and supplies and have them inform you that it will take (approximately) certain amount of time to get the ship running back again, during which time pirates may arrive and the ship may request assistance, etc. Alternatively the engineers might announce that the ship is fubar and request cargo transfer and ride back home. In general player should never know **exactly** what would happen during mission and events should have a chance of triggering one another.
* once docking is implemented there could be missions to tow a ship or boost immobilized ship in decaying orbit to buy crew more time. Or, on a more nefarious side, to deorbit a shot-up ship into a gas-giant to get rid of witnesses or evidence (of course then you might become a loose end yourself).
* I agree that background fiction is important as it ties everything, including gameplay, together. Drone buoys sound like sensible idea, they wouldn't even need "full" hyperdrive, just a simplified, non-reusable model (something akin to a bomb-pumped laser).

**Comment by impaktor** [comment]
> distress calls arrive while traveling, not just as BBS ads

Yes, but current comms is not well suited for that. This was discussed on the forum. It can be implemented as such a mission when there's support for it.

> One thing to note that there's no direct FTL communications in the Pioneer Universe

Although orbital view already breaks FTL transfer of information, I agree. So for these missions, wouldn't just a message saying that "reports from system X...." bla bla. suffice, as long as one doesn't say that it was through radio transmission or anything. Could be from probes, or other pilots.

Flavours is good, but my point is (without having looked at the strings for this module) that adding 10 strings that all say almost the same thing, will for the end player read pretty much like the same string. For instance: _"Please help me!"_, _"Help me Please!"_, _"Would you help me please!"_ at least the first two strings are almost identical, and I think the player wouldn't notice them as two different ones.

**Comment by corundscale** [comment]
>>distress calls arrive while traveling, not just as BBS ads

>Yes, but current comms is not well suited for that. This was discussed on the forum. It can be >implemented as such a mission when there's support for it.

Would just dropping the mission and non-interactive distress call on player's lap and letting it time-out and clear itself if they don't do it work? The way I understand it responding to a distress call doesn't really require any specific arrangements, just being there to help.

**Comment by nozmajner** [comment]
Since it only would show up on the comms log for a couple of seconds, most of the time they would go unnoticed. Even if it drops out the player from time accel, because messages aren't showing for that long.
You could try picking up @robn's comms log work, add some notification features to it  (if not already present) to help building the infrastructure for what you mentioned.

**Comment by corundscale** [comment]
>Since it only would show up on the comms log for a couple of seconds, most of the time they would go unnoticed. Even if it drops out the player from time accel, because messages aren't showing for that long.

But then the player would already be notified of the distress call and could review the details in mission log.

**Comment by nozmajner** [comment]
If the player happens to know where to look, or that there's something to look for. Which information isn't really presented anywhere for the player, but only in a very hacky way.

**Comment by corundscale** [comment]
Repeat calls? Besides, forced time compression drop seems guaranteed to attract attention and several seconds is plenty of time to notice that there has been something.

Maybe general notification mechanics where mission log button would flash when there would be unread information in it?

**Comment by fluffyfreak** [comment]
Ok, this has gone off-topic, future work is cool but unless it a minor change to this PR lets focus on what's here now please.

**Comment by corundscale** [comment]
Why not just merge it and then keep merging any additional features added in this branch?

**Comment by fluffyfreak** [comment]
Well first I'd like to test it ;)

**Comment by impaktor** [comment]
> Why not just merge it and then keep merging any additional features added in this branch?

Because @clausimu explicitly said it is WIP (Work In Progress), and I know he's been working on this for several months, so I suspect he want's it done _right_ rather than _fast_, and he probably wants to be happy with it and give the players a nice first experience than us merging something that he wanted to work more on.

He opened this PR so we could give feedback on code and test it out. When he believes he's done with it, and that it is ready for full review and testing, we'll do that, as time permits, and _then_ merge.

**Comment by clausimu** [comment]
>He opened this PR so we could give feedback on code and test it out.

Thank you for the advance trust in my work, @corundscale ;) - but @impaktor is right on this one. There are still some things I'm not sure are good/right (for example the way I'm doing ship-to-ship transfer). Should it be done via pods and scooping? Should we hold off until ship-ship-docking is possible?

I also need to make the text more translator friendly.

I really opened this PR to get a feel of where it should be taken. Suggestions (such as procedural mission chains, figuring out how it fits with communications across systems, etc.) are very welcome.

**Comment by impaktor** [comment]
Some notes below (because I can't comment on code that's a new file in github?):

L244, the count variable should be local? Also in `calcReward` there should be a local declaration.

Your `round` function isn't used.

`removeCrew` has a for loops that only runs one iteration, is that right?

This: `for i,shipdef in pairs(shipdefs) do` looks dangerous. Two variables with the same name in the same function.

Also, in `createTargetShip` you define `shipdef` twice.

Here, you also have shadowing variables (`body). It works because Lua guesses right when in such a conflicting situation.
```
local findNearbyStations = function (vacuum, body)
...
nearbystations_raw = Space.GetBodies(function (body)
```

`makeAdvert` defines `reward` twice, and in `closeMission` the variable with the same name is defined but not used, and `delta_reputation` should be local

**Comment by clausimu** [comment]
Thank you for the code-comments! I will work on those.

I guess my biggest question is if the current transport model (stay within x m of target ship to transfer) is okay or if this script should stay in "hibernation" until ship-to-ship docking is possible? Or port everything to transport via release and scoop of cargo (personnel?) containers?

**Comment by nozmajner** [comment]
I think there's no need to keep it in hibernation, it works nicely and adds a lot to the game. In space it isn't much of a hassle anyway to get close to the ship. Maybe the player should land near grounded ship for the transfer to be possible, instead of just floating next to it.

**Comment by corundscale** [comment]
I agree with @nozmajner 
merging it now would greatly improve gameplay and have more eyes looking at it in case it doesn't work like intended or in case there are some improvements to suggest, while it's not as if it can break anything that isn't broken every few versions anyway.

Release and scoop of personnel as cargo (while in space) mechanics would be nice and possibly interesting enough to happen in some situations even after docking mechanics is implemented, but it would require art assets and I just can't see any problems with doing it separately - S&R missions don't specifically depend on how the transfer is performed so the mechanics in place is already good - it doesn't need to be perfect in the first iteration, if it can be made better later on then it can be made better later on.

**Comment by fluffyfreak** [comment]
@corundscale well let @clausimu change or rework the code based on that feedback first, but yes I basically agree that once those bits are cleaned up we could merge it.

**Comment by clausimu** [comment]
I just updated the script:

1. Fixed script syntax using luacheck (thank you @impaktor for pointing this out!).
2. Added the requirement of having to land within interaction distance of target ship if the mission happens on a planet surface (as per request by @nozmajner)
3. Broke up long advertisement texts into dialog bits (see screenshots below):

lat_lon_29
lat_lon_30
lat_lon_31
lat_lon_32
lat_lon_33
lat_lon_34
lat_lon_35

At this point I still need to change the frequency at which ads appear (I was thinking 20% chance in regular systems?) - right now it is still 3 ads per flavour for testing purposes.

The reputation change has been set to:

* +0.5 for missions on the same planet as the player is on
* +0.75 for missions within the same system as the player is in
* +1 for missions out of system

I am debating whether to increase the reputation - especially since money has been removed from some missions.

Other than that I think it can basically be merged - or at least should be looked at from that point of view. I did not include

* missions outside of BBS yet
* procedural missions (as @corundscale had suggested)

These will come at a later time when this script is final. 

I really need a native English speaker to look over the en.json file and make sure it is correct.

**Comment by nozmajner** [comment]
Already a couple of issues for it, #3509 and #3128, and @clausimu already knows about it, but I thought I mention it here. The ship I had to rescue from orbit was displayed in the Sun in the orbit view.

Is it possible to add a target button or something in the mission description? So you don't need to blindly click on a zoomed-in Sun until you find the ship you need to help out. As a hacky workaround until the orbit display is fixed?

**Comment by clausimu** [comment]
This is a big problem, I know. If the ship display in the orbit view is here to stay, I wish someone with the right brains (and time...) could fix it. I have tried to take a look at the code but am not smart enough to figure out what is wrong.

I am also taking a look at what the tradeships module is doing and how to improve it. A functioning ship display in orbit view would make this much easier.

If it is just too buggy and has to be removed I will have to come up with a different way of localizing ships in space. It should be something not specific to this script though. I'm sure there will be other cases (assassinations?, responding to mayday?, etc.) where a specific ship will have to be found within the system.

**Comment by fluffyfreak** [comment]
It's buggy and needs to be fixed but don't let it interfere with this PR.

**Comment by clausimu** [comment]
Ad frequency is now dependent on system lawlessness. Minimum frequency = 20%, maximum frequency = 90%. This leads to a single ad in 20% of stations of very lawful systems (Earth) and a single ad in almost all stations of very lawless systems.

I also fixed a few more bugs discovered while testing (reload, text, etc.)

This is ready for merging (if the devs agree).

**Comment by impaktor** [comment]
OK, I just realized we forgot to add this new module to the transifex side. This is now done. 151 new strings to translate. Might take a whilte before all languages are updated, depending on translator activity.

**Comment by impaktor** [comment]
Which icon do we want? I think the white-red one is more discrete, and fits a bit better with general pioneer "low contrast icon theme". The red one stands out very much.
screenshot-20151210-104330
screenshot-20151210-104211

**Comment by jmf** [comment]
I like the red one. 
It's easy to spot and that's what an emergency BBS message should be.

**Comment by fluffyfreak** [comment]
I agree with @jmf that since it is a search and rescue you don't want it to be discreet.
However I'll let @nozmajner override me on that one ;)

**Comment by nozmajner** [comment]
I agree, it should be quite eye-chactching if they are distress calls, or similar. They are also quite rare, and also interesting missions, so they shouldn't be hidden among similar icons in my opinion.

**Comment by clausimu** [comment]
I was going to vote for the white one (with red exclamation mark) - just to resist any upcoming trend of multicolored bb icons. But I defer to the wisdom of the artist in charge :). I think either one will be fine.

**Comment by nozmajner** [comment]
I won't make or suggest any other colored icon apart from this, I can promise that. :)

**Comment by impaktor** [comment]
#3558 
Thus this conversation is: 
Done. Closed, Fin. Schluss. Slut.

(No the last part there was not an outburst of having everyone turn against me, but rather my [native](https://translate.google.com/#sv/en/Slut) word in the cannon).

**Comment by fluffyfreak** [comment]
Slut means final in Swedish? This is excellent news!
> "No this is my Slut beer tonight"
> "That's my Slut time estimate"
> "This is my Slut wife"

Oh god I'm going to get dumped, fired and drunk this weekend :)

**Comment by impaktor** [comment]
"end wife"? Doesn't work. Regarding the first one: There's a word for the leftover beer in the bottom of the glass and it is called "slatt" (derived from "slut") and almost pronounced like the English word "slut".

I saw an interview with a Swedish band who explained to an American journalist that at parties they always stay to the end to "take all the slatts" (meaning leftover beer). Language confusion and misunderstandings followed.

Also, there's [bra](https://translate.google.com/#sv/en/bra) and [fart](https://translate.google.com/#sv/en/fart)

**Comment by impaktor** [comment]
@clausimu this just came up, `FLAVOUR_3_INTROTEXT` lacks a `{cash}`, do you, as author of the module, want to suggest a new string that includes it?

**Comment by clausimu** [comment]
Originally, I had decided against a proposed cash reward for this mission flavor for two reasons: (i) it spices things up a bit, and (ii) I felt that a medical emergency hopefully appeals to a higher motive than money to respond. If you feel a proposed cash reward is necessary I can add one though.

**Comment by Web-eWorks** [comment]
It came up for consistency reasons, though there's no reason we can't add a separate advert option to ask specifically about the pay for a rescue mission.

**Pull request merged**
