### PR TITLE
Update to whole new Assimp

### PR DESCRIPTION
**Pull request by fluffyfreak**
This updates us to use the new Assimp library in pioneer-thirdparty.

Then I added dumping the warnings found when the modelcompiler is used, then I fixed up the bowfin and orbital station `.model` material names.
There are [many warnings](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=27&start=50#p4692)

**EDIT:** Also it's a fix for #3654

### CODE REVIEW

**Comment by nozmajner** [comment]
Do I have to change anything about the models, or in the ways I export them?

**Comment by fluffyfreak** [comment]
@nozmajner I'll get back to you on that, but so far seems to just be the name used in the `.model` file.

**Comment by fluffyfreak** [comment]
@nozmajner when/if this gets merged the `modelcompiler` will output warnings so a good way to find errors and problems with *all* the models is `modelcompiler -b` and then look in the `output.txt` to see what it's said.

Most of the stuff is benign and the engine just silently handles it but you can then check them in the viewer and see whihc ones are real problems or not.

**Comment by fluffyfreak** [comment]
@robn this is the companion code/data update to the pioneer-thirdparty stuff https://github.com/pioneerspacesim/pioneer-thirdparty/pull/19

**Comment by fluffyfreak** [comment]
@robn this has data fixes which might be necessary for an Assimp 3.2 release.

**Comment by robn** [comment]
I'm ready to do a test build against assimp 3.2. I will merge this and @pioneer-thirdparty#19 for the Linux builds in the next hour or two unless there's any objections.

**Comment by fluffyfreak** [comment]
That'd be great, thanks @robn :)

**Pull request merged**
