### PR TITLE
Put imgui.ini into user config dir

### PR DESCRIPTION
**Pull request by ecraven**
Put imgui.ini into UserConfig.

### CODE REVIEW

**Comment by fluffyfreak** [comment]
I don't think it leaking is a problem. It'll be cleaned up on shutdown anyway and it's only allocated the once.

**Comment by ecraven** [comment]
I agree, just wanted to comment that this is something we know, but chose to ignore :)

**Comment by impaktor** [comment]
I'm fine if @ecraven wants to make this his first self-merge.
http://pioneerwiki.com/wiki/Using_git_and_GitHub#How_to_merge_a_PR_the_propper.2Fpedantic_way

**Comment by laarmen** [comment]
Likewise, the leak doesn't bother me much.

**Pull request merged**
