### PR TITLE
Search&Rescue missions update

### PR DESCRIPTION
**Pull request by clausimu**
## What Is It

This is an update to the Search & Rescue mission script.

## Detailed Changelog

1. Decrease the frequency of restocking the BBS with new mission ads. The ad frequency is now dependent on the system's lawlessness and the number of stations in the system. That way the player will meet a certain number of ads while in the system. This ranges from an average of 3 per station (very lawless) to one every third station (very lawful).

2. Gracefully discard ships not needed any more. Ships that have been rescued will ultimately hyperjump away for a "graceful" exit before discarding from the script.

3. Corrections in text and new text snippets needed for the new mission screen.

4. mission.dist and ad.dist have been changed to meters (except for "FAR_SPACE" missions) to improve consistency.

5. Updated mission screen with more details (adapted from what walterar had done for Scout+) (see screenshots).

6. Rescue missions on planets within the same system will be limited to planets without stations (exception: missions that happen on the same planet as the station where the ad is found). This will provide more incentive to visit those beautiful, otherwise shamefully neglected, uninhabited planets. (Original idea from walterar at Scout+)

snapshot1
snapshot2

I have not been able to reproduce the bug where missions don't get closed and removed properly. I will continue to investigate.

### CODE REVIEW

**Comment by walterar** [comment]
Consider this: 

 	Timer:CallAt(Game.time + Engine.rand:Integer(1,10), function ()
-			ship:AIEnterLowOrbit(ship:FindNearestTo("PLANET") or ship:FindeNearestTo("STAR")) end)
-	Timer:CallAt(Game.time + 5, function () ship:InitiateHyperjumpTo(nearbysystems[1], 3, 10) end)
+			ship:AIEnterLowOrbit(ship:FindNearestTo("PLANET") or ship:FindeNearestTo("STAR"))
+	Timer:CallAt(Game.time + 5, function () ship:InitiateHyperjumpTo(nearbysystems[1], 3, 10) end) end)

**Comment by clausimu** [comment]
Thanks, walterar, I will look into that - and also the other suggestions you made in the forum. I changed the title to WIP so it doesn't get merged just yet.

**Comment by impaktor** [comment]
Looks like github doesn't recognize you as author of your commits. I'd check my github settings if I were you.

**Comment by walterar** [comment]
Claudius. These timers will not work if you not fix it.

**Comment by clausimu** [comment]
impaktor: I just setup my computer again - I will look into it. Thank you for pointing out.

walterar: Thank you! This week has been very busy for me, no time to work on Pioneer. But I will definitely take a closer look at the timer functions you pointed out.

**Comment by clausimu** [comment]
It should be fixed and working now. Thank you walterar for the input and suggestions. I have updated the first post with added details of what has been changed.

**Comment by impaktor** [comment]
Seems to have a merge conflict. I haven't looked into it though.

**Comment by walterar** [comment]
I have not seen clausimu in AUTHORS.txt
Did you enter a different name, or forgotten?

**Comment by impaktor** [comment]
I was going to merge this but there are too many conflicts. @clausimu tells me it might be another week bfore he can look at it agan, just so we know where we stand on this.

I think he is in Authors. If not, he'll have to tell us.

**Comment by walterar** [comment]
It's in an old master with problems:

pioneer: TextureGL.cpp:292: virtual void Graphics::TextureGL::Update(const Graphics::TextureCubeData&, const vector2f&, Graphics::TextureFormat, unsigned int): Assertion `m_target == 0x8513' failed.

But at the last master it works well. Although problems will be see over time, may occur. I do not think anyone here test it in depth really.

**Pull request merged**
